begin;
create extension if not exists pgtap with schema extensions;
select plan(19);
select has_function('public','world_npc_memory_summary_plan_v2',array['uuid','uuid'],'v2 runtime plan RPC exists');
select ok(not has_function_privilege('authenticated','public.world_npc_memory_summary_plan_v2(uuid,uuid)','EXECUTE'),'authenticated cannot plan v2 runtime work');
insert into auth.users(id,email,role,aud) values ('19600000-0000-4000-8000-000000000001','plan-v2@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='19600000-0000-4000-8000-000000000001'; select public.create_tavern(); reset role;
create temporary table pg_temp.f as select (x#>>'{save,id}')::uuid save_id,(x->'roster'->0->>'instanceId')::uuid instance_id,(x->'roster'->0->>'npcId')::uuid npc_id,(x->'roster'->0->>'versionId')::uuid version_id,(x#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() x) q;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at) select ('19600000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid,save_id,instance_id,npc_id,version_id,'19600000-0000-4000-8000-000000000001','plan unicode '||chr(0+65+g),g,revision,1,'completed',clock_timestamp()+interval '5 minutes',jsonb_build_object('reply','中文 🦉 '||g),clock_timestamp() from pg_temp.f cross join generate_series(1,2) g;
select private.world_npc_memory_project_source('dialogue_turn',('19600000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid) from generate_series(1,2) g;
insert into private.world_npc_memories(id,turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id) select ('19600000-0000-4002-8000-'||lpad(g::text,12,'0'))::uuid,('19600000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid,instance_id,'interaction','unicode evidence '||g,'quote '||g,'npc',3,'{}',save_id,('19600000-0000-4003-8000-'||lpad(g::text,12,'0'))::uuid,1,'dialogue_turn',('19600000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid,1,private.world_npc_memory_source_hash('dialogue_turn',('19600000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid),1,g,1,g,'attributed','npc_known',instance_id from pg_temp.f cross join generate_series(1,2) g;
create temporary table pg_temp.s as select (private.world_npc_memory_register_summary_set('episode_summary','runtime-plan',(select max(ledger_sequence) from private.world_npc_memory_sources where source_kind='dialogue_turn' and disclosure_class='npc_known'),'npc_known',jsonb_build_array(jsonb_build_object('ordinal',0,'sourceKind','dialogue_turn','sourceId','19600000-0000-4001-8000-000000000001'::uuid,'sourceVersion',1),jsonb_build_object('ordinal',1,'sourceKind','dialogue_turn','sourceId','19600000-0000-4001-8000-000000000002'::uuid,'sourceVersion',1)),jsonb_build_array(jsonb_build_object('batchOrdinal',0,'firstLeafOrdinal',0,'lastLeafOrdinal',0,'leafCount',1),jsonb_build_object('batchOrdinal',1,'firstLeafOrdinal',1,'lastLeafOrdinal',1,'leafCount',1)),'npc-memory-summary-v2')).*;
create function pg_temp.new_set(p_key text,p_version text default 'npc-memory-summary-v2') returns uuid language plpgsql security definer set search_path='' as $f$
declare sid uuid; begin
 select id into sid from private.world_npc_memory_register_summary_set('episode_summary',p_key,(select max(ledger_sequence) from private.world_npc_memory_sources where source_kind='dialogue_turn' and disclosure_class='npc_known'),'npc_known',jsonb_build_array(jsonb_build_object('ordinal',0,'sourceKind','dialogue_turn','sourceId','19600000-0000-4001-8000-000000000001'::uuid,'sourceVersion',1),jsonb_build_object('ordinal',1,'sourceKind','dialogue_turn','sourceId','19600000-0000-4001-8000-000000000002'::uuid,'sourceVersion',1)),jsonb_build_array(jsonb_build_object('batchOrdinal',0,'firstLeafOrdinal',0,'lastLeafOrdinal',0,'leafCount',1),jsonb_build_object('batchOrdinal',1,'firstLeafOrdinal',1,'lastLeafOrdinal',1,'leafCount',1)),p_version);
 return sid;
end $f$;
set local role service_role; set local request.jwt.claim.role='service_role'; create temporary table pg_temp.c as select public.world_npc_memory_claim('summary','npc-memory-summary-v2') claim; select set_config('test.job',(select claim->>'id' from pg_temp.c),true); select set_config('test.fence',(select claim->>'fence' from pg_temp.c),true); select set_config('test.plan',public.world_npc_memory_summary_plan_v2(current_setting('test.job')::uuid,current_setting('test.fence')::uuid)::text,true); reset role;
select is(current_setting('test.plan')::jsonb->>'version','npc-memory-summary-v2-runtime-plan-1','plan version is fixed');
select is((current_setting('test.plan')::jsonb->>'batchCount')::integer,2,'plan returns exact batch count');
select is(current_setting('test.plan')::jsonb->'batches'->0->>'ordinal','0','plan batches are ordinal ordered');
select is((current_setting('test.plan')::jsonb->'batches'->0->>'maxSummaryChars')::integer,5999,'plan derives exact per-batch summary budget');
select is((current_setting('test.plan')::jsonb->'batches'->0->>'maxCitations')::integer,64,'plan derives exact per-batch citation budget');
select ok((current_setting('test.plan')::jsonb->>'planHash')~'^[0-9a-f]{64}$','plan carries canonical immutable metadata hash');
select ok(private.world_json_keys_exact(current_setting('test.plan')::jsonb,array['version','jobId','fence','set','prompt','batchCount','maxSummaryChars','maxCitations','batches','planHash']) and private.world_json_keys_exact(current_setting('test.plan')::jsonb->'set',array['id','setVersion','setHash','summaryKind','cutoffLedgerSequence','disclosureClass']) and private.world_json_keys_exact(current_setting('test.plan')::jsonb->'prompt',array['releaseId','key','revisionId','contractId','contractHash']) and private.world_json_keys_exact(current_setting('test.plan')::jsonb->'batches'->0,array['ordinal','firstLeafOrdinal','lastLeafOrdinal','leafCount','maxSummaryChars','maxCitations']),'plan has strict top-level and nested metadata allowlists');
select set_config('test.before',(select jsonb_build_object('jobStatus',status,'leaseUntil',lease_until,'fence',fence,'receipts',(select count(*) from private.world_npc_memory_summary_dispatches where job_id=j.id),'artifacts',(select count(*) from private.world_npc_memory_artifacts where instance_id=j.instance_id and source_hash=j.source_hash))::text from private.world_npc_memory_outbox j where id=current_setting('test.job')::uuid),true);
set local role service_role; set local request.jwt.claim.role='service_role'; select public.world_npc_memory_summary_plan_v2(current_setting('test.job')::uuid,current_setting('test.fence')::uuid); reset role;
select is((select jsonb_build_object('jobStatus',status,'leaseUntil',lease_until,'fence',fence,'receipts',(select count(*) from private.world_npc_memory_summary_dispatches where job_id=j.id),'artifacts',(select count(*) from private.world_npc_memory_artifacts where instance_id=j.instance_id and source_hash=j.source_hash))::text from private.world_npc_memory_outbox j where id=current_setting('test.job')::uuid),current_setting('test.before'),'plan is read-only for job, receipts, artifacts, and timestamps');
select ok(not (current_setting('test.plan')::jsonb ? 'leaves') and position('unicode evidence' in current_setting('test.plan'))=0 and position('中文' in current_setting('test.plan'))=0,'plan leaks no evidence prose');
set local role service_role; set local request.jwt.claim.role='service_role'; select throws_ok($$select public.world_npc_memory_summary_plan_v2(current_setting('test.job')::uuid,extensions.gen_random_uuid())$$,'PT409',null,'wrong fence rejects'); reset role;
update private.world_npc_memory_outbox set lease_until=clock_timestamp()-interval '1 second' where id=current_setting('test.job')::uuid;
set local role service_role; set local request.jwt.claim.role='service_role'; select throws_ok($$select public.world_npc_memory_summary_plan_v2(current_setting('test.job')::uuid,current_setting('test.fence')::uuid)$$,'PT409',null,'expired lease rejects'); reset role;

-- Runtime planning is v2-only, and refuses any job/set/prompt pin whose
-- immutable context no longer describes an eligible live v2 work item.
select set_config('test.v1_set',pg_temp.new_set('runtime-plan-v1','npc-memory-v1')::text,true);
set local role service_role; set local request.jwt.claim.role='service_role'; create temporary table pg_temp.v1_claim as select public.world_npc_memory_claim('summary','npc-memory-v1') claim;
select throws_ok($$select public.world_npc_memory_summary_plan_v2((select (claim->>'id')::uuid from pg_temp.v1_claim),(select (claim->>'fence')::uuid from pg_temp.v1_claim))$$,'PT409',null,'explicit v1 summary job cannot obtain a v2 runtime plan'); reset role;

select set_config('test.malformed_set',pg_temp.new_set('runtime-plan-malformed')::text,true);
set local role service_role; set local request.jwt.claim.role='service_role'; create temporary table pg_temp.malformed_claim as select public.world_npc_memory_claim('summary','npc-memory-summary-v2') claim; reset role;
alter table private.world_npc_memory_outbox disable trigger world_npc_memory_summary_job_pin;
update private.world_npc_memory_outbox set prompt_release_id=(select prior_release_id from private.prompt_releases where id=(select release_id from private.prompt_registry_active_release)) where id=(select (claim->>'id')::uuid from pg_temp.malformed_claim);
alter table private.world_npc_memory_outbox enable trigger world_npc_memory_summary_job_pin;
set local role service_role; set local request.jwt.claim.role='service_role'; select throws_ok($$select public.world_npc_memory_summary_plan_v2((select (claim->>'id')::uuid from pg_temp.malformed_claim),(select (claim->>'fence')::uuid from pg_temp.malformed_claim))$$,'PT409',null,'v2 job with a legal but v2-incomplete prompt release cannot plan'); reset role;

select set_config('test.invalidated_set',pg_temp.new_set('runtime-plan-invalidated')::text,true);
set local role service_role; set local request.jwt.claim.role='service_role'; create temporary table pg_temp.invalidated_claim as select public.world_npc_memory_claim('summary','npc-memory-summary-v2') claim; reset role;
update private.world_npc_memory_summary_sets set closure_status='invalidated',invalidated_at=clock_timestamp() where id=(select source_id from private.world_npc_memory_outbox where id=(select (claim->>'id')::uuid from pg_temp.invalidated_claim));
set local role service_role; set local request.jwt.claim.role='service_role'; select throws_ok($$select public.world_npc_memory_summary_plan_v2((select (claim->>'id')::uuid from pg_temp.invalidated_claim),(select (claim->>'fence')::uuid from pg_temp.invalidated_claim))$$,'PT409',null,'invalidated v2 set cannot obtain a runtime plan'); reset role;

select set_config('test.purged_set',pg_temp.new_set('runtime-plan-purged')::text,true);
set local role service_role; set local request.jwt.claim.role='service_role'; create temporary table pg_temp.purged_claim as select public.world_npc_memory_claim('summary','npc-memory-summary-v2') claim; reset role;
delete from private.world_npc_instances where id=(select instance_id from pg_temp.f);
set local role service_role; set local request.jwt.claim.role='service_role'; select throws_ok($$select public.world_npc_memory_summary_plan_v2((select (claim->>'id')::uuid from pg_temp.purged_claim),(select (claim->>'fence')::uuid from pg_temp.purged_claim))$$,'PT409',null,'purged resident cannot obtain a late runtime plan'); reset role;
select is((select count(*) from private.world_npc_memory_outbox where id=(select (claim->>'id')::uuid from pg_temp.purged_claim)),0::bigint,'resident purge leaves no plan-capable job behind');
set local role authenticated; set local request.jwt.claim.role='authenticated'; select throws_ok($$select public.world_npc_memory_summary_plan_v2(current_setting('test.job')::uuid,current_setting('test.fence')::uuid)$$,'42501',null,'authenticated planning is denied'); reset role;
select * from finish(); rollback;
