begin;
create extension if not exists pgtap with schema extensions;
select plan(51);

select has_function('public','world_npc_memory_summary_finalize_v2',array['uuid','uuid'],'v2 finalizer exists');
select ok(not has_function_privilege('authenticated','public.world_npc_memory_summary_finalize_v2(uuid,uuid)','EXECUTE'),'authenticated cannot finalize v2');
select ok(not has_function_privilege('authenticated','public.world_npc_memory_complete(uuid,uuid,jsonb,text)','EXECUTE'),'authenticated cannot invoke generic completion');
select ok(not private.world_npc_memory_summary_v2_content_valid(null::jsonb,null::uuid),'NULL final content fails closed');
select ok(not private.world_npc_memory_summary_v2_received_valid(null::jsonb,null::uuid,null::integer),'NULL receipt fails closed');

insert into auth.users(id,email,role,aud) values ('19500000-0000-4000-8000-000000000001','summary-v2-final@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='19500000-0000-4000-8000-000000000001';
select public.create_tavern(); reset role;
create temporary table pg_temp.f as select (x#>>'{save,id}')::uuid save_id,(x->'roster'->0->>'instanceId')::uuid instance_id,(x->'roster'->0->>'npcId')::uuid npc_id,(x->'roster'->0->>'versionId')::uuid version_id,(x#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() x) q;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at)
select ('19500000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid,save_id,instance_id,npc_id,version_id,'19500000-0000-4000-8000-000000000001','final evidence '||g,g,revision,1,'completed',clock_timestamp()+interval '5 minutes',jsonb_build_object('reply','Unicode Cafe'||chr(769)||' 中文 🦉 '||g),clock_timestamp() from pg_temp.f cross join generate_series(1,2) g;
select private.world_npc_memory_project_source('dialogue_turn',('19500000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid) from generate_series(1,2) g;
insert into private.world_npc_memories(id,turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id)
select ('19500000-0000-4002-8000-'||lpad(g::text,12,'0'))::uuid,('19500000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid,instance_id,'interaction','Exact Unicode Cafe'||chr(769)||' 中文 🦉 '||g,'Cafe'||chr(769)||' 中文 🦉 '||g,'npc',3,'{}',save_id,('19500000-0000-4003-8000-'||lpad(g::text,12,'0'))::uuid,1,'dialogue_turn',('19500000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid,1,private.world_npc_memory_source_hash('dialogue_turn',('19500000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid),1,g,1,g,'attributed','npc_known',instance_id from pg_temp.f cross join generate_series(1,2) g;

create function pg_temp.make_set(p_key text) returns uuid language plpgsql security definer set search_path='' as $f$
declare sid uuid; begin
 select id into sid from private.world_npc_memory_register_summary_set('episode_summary',p_key,(select max(ledger_sequence) from private.world_npc_memory_sources where source_kind='dialogue_turn' and disclosure_class='npc_known'),'npc_known',
 jsonb_build_array(jsonb_build_object('ordinal',0,'sourceKind','dialogue_turn','sourceId','19500000-0000-4001-8000-000000000001'::uuid,'sourceVersion',1),jsonb_build_object('ordinal',1,'sourceKind','dialogue_turn','sourceId','19500000-0000-4001-8000-000000000002'::uuid,'sourceVersion',1)),
 jsonb_build_array(jsonb_build_object('batchOrdinal',0,'firstLeafOrdinal',0,'lastLeafOrdinal',0,'leafCount',1),jsonb_build_object('batchOrdinal',1,'firstLeafOrdinal',1,'lastLeafOrdinal',1,'leafCount',1)),'npc-memory-summary-v2'); return sid; end $f$;
create function pg_temp.result(p_set uuid,p_batch integer,p_summary text) returns jsonb language sql security definer set search_path='' as $f$
 select jsonb_build_object('version','npc-memory-summary-v2','mode','model','summary',p_summary,'citations',jsonb_build_array((select jsonb_build_object('leafOrdinal',l.ordinal,'recordId',m.id,'speaker',m.speaker,'quote',m.quote,'sourceKind',m.source_kind,'sourceId',m.source_id,'sourceVersion',m.source_version,'sourceHash',m.source_hash) from private.world_npc_memory_summary_leaves l join private.world_npc_memory_summary_batches b on b.set_id=l.set_id and l.ordinal between b.first_leaf_ordinal and b.last_leaf_ordinal join private.world_npc_memory_summary_sets s on s.id=l.set_id join private.world_npc_memories m on m.instance_id=s.instance_id and m.disclosure_class=s.disclosure_class and m.source_kind=l.source_kind and m.source_id=l.source_id and m.source_version=l.source_version and m.source_hash=l.source_hash where l.set_id=p_set and b.batch_ordinal=p_batch)),'protectedRefs',(select jsonb_agg(jsonb_build_object('ordinal',l.ordinal,'sourceKind',l.source_kind,'sourceId',l.source_id,'sourceVersion',l.source_version,'sourceHash',l.source_hash,'ledgerSequence',l.ledger_sequence) order by l.ordinal) from private.world_npc_memory_summary_leaves l join private.world_npc_memory_summary_batches b on b.set_id=l.set_id and l.ordinal between b.first_leaf_ordinal and b.last_leaf_ordinal where l.set_id=p_set and b.batch_ordinal=p_batch),'leaves',(select jsonb_agg(jsonb_build_object('ordinal',l.ordinal,'sourceKind',l.source_kind,'sourceId',l.source_id,'sourceVersion',l.source_version,'sourceHash',l.source_hash,'ledgerSequence',l.ledger_sequence) order by l.ordinal) from private.world_npc_memory_summary_leaves l join private.world_npc_memory_summary_batches b on b.set_id=l.set_id and l.ordinal between b.first_leaf_ordinal and b.last_leaf_ordinal where l.set_id=p_set and b.batch_ordinal=p_batch))
$f$;

select set_config('test.set',pg_temp.make_set('final-primary')::text,true);
set local role service_role; set local request.jwt.claim.role='service_role';
create temporary table pg_temp.claim as select public.world_npc_memory_claim('summary','npc-memory-summary-v2') claim;
select set_config('test.job',(select claim->>'id' from pg_temp.claim),true); select set_config('test.fence',(select claim->>'fence' from pg_temp.claim),true);
select lives_ok($$select public.world_npc_memory_summary_prepare_dispatch(current_setting('test.job')::uuid,current_setting('test.fence')::uuid,0)$$,'first batch prepares');
select lives_ok($$select public.world_npc_memory_summary_prepare_dispatch(current_setting('test.job')::uuid,current_setting('test.fence')::uuid,1)$$,'second batch prepares');
select lives_ok($$select public.world_npc_memory_summary_mark_dispatched(current_setting('test.job')::uuid,current_setting('test.fence')::uuid,0,'provider-0')$$,'first batch dispatches');
select lives_ok($$select public.world_npc_memory_summary_mark_dispatched(current_setting('test.job')::uuid,current_setting('test.fence')::uuid,1,'provider-1')$$,'second batch dispatches');
select is(public.world_npc_memory_summary_record_dispatch_result(current_setting('test.job')::uuid,current_setting('test.fence')::uuid,0,pg_temp.result(current_setting('test.set')::uuid,0,'first model sentence'),'model-a','provider-0')->>'status','received','first result persists');
select is(public.world_npc_memory_summary_record_dispatch_result(current_setting('test.job')::uuid,current_setting('test.fence')::uuid,1,pg_temp.result(current_setting('test.set')::uuid,1,'second model sentence'),'model-a','provider-1')->>'status','received','second result persists');
select set_config('test.final',public.world_npc_memory_summary_finalize_v2(current_setting('test.job')::uuid,current_setting('test.fence')::uuid)::text,true);
reset role;
select is(current_setting('test.final')::jsonb->>'status','completed','all received batches finalize');
select is((select content->>'summary' from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.set')::uuid)),'first model sentence'||E'\n\n'||'second model sentence','model prose assembles in batch ordinal order');
select is((select content->>'mode' from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.set')::uuid)),'model','all-received artifact is model mode');
select is((select generation_manifest->>'mode' from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.set')::uuid)),'model','receipt manifest persists model provenance');
select is((select jsonb_array_length(generation_manifest->'batches') from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.set')::uuid)),2,'manifest has exact receipt ordinals');
select ok((select embedding is null and embedding_dimensions is null and prompt_key='npc_memory.summary.v2' and contract_id='npc-memory-summary-v2' from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.set')::uuid)),'v2 artifact stores pinned provenance and no embeddings');
set local role service_role; set local request.jwt.claim.role='service_role';
select is(public.world_npc_memory_summary_finalize_v2(current_setting('test.job')::uuid,current_setting('test.fence')::uuid)->>'status','reused','exact completed replay is reused');
select throws_ok($$select public.world_npc_memory_complete(current_setting('test.job')::uuid,current_setting('test.fence')::uuid,'[]'::jsonb,null)$$,'PT400',null,'generic public completion rejects v2');
select throws_ok($$select public.world_npc_memory_summary_finalize_v2(current_setting('test.job')::uuid,extensions.gen_random_uuid())$$,'PT409',null,'stale finalization fence rejects');
reset role;
select throws_ok($$update private.world_npc_memory_summary_dispatches set request_hash=repeat('a',64) where job_id=current_setting('test.job')::uuid$$,'PT409',null,'direct receipt mutation remains guarded');

-- A completed receipt may belong to a reclaimed prior fence.  The finalizer
-- validates the current claim while preserving the original receipt fence.
select set_config('test.reclaim_set',pg_temp.make_set('final-reclaim')::text,true);
set local role service_role; set local request.jwt.claim.role='service_role';
create temporary table pg_temp.reclaim_old as select public.world_npc_memory_claim('summary','npc-memory-summary-v2') claim;
select set_config('test.reclaim_job',(select claim->>'id' from pg_temp.reclaim_old),true); select set_config('test.reclaim_old_fence',(select claim->>'fence' from pg_temp.reclaim_old),true);
select public.world_npc_memory_summary_prepare_dispatch(current_setting('test.reclaim_job')::uuid,current_setting('test.reclaim_old_fence')::uuid,0); select public.world_npc_memory_summary_prepare_dispatch(current_setting('test.reclaim_job')::uuid,current_setting('test.reclaim_old_fence')::uuid,1);
select public.world_npc_memory_summary_mark_dispatched(current_setting('test.reclaim_job')::uuid,current_setting('test.reclaim_old_fence')::uuid,0,'reclaim-0'); select public.world_npc_memory_summary_mark_dispatched(current_setting('test.reclaim_job')::uuid,current_setting('test.reclaim_old_fence')::uuid,1,'reclaim-1');
select public.world_npc_memory_summary_record_dispatch_result(current_setting('test.reclaim_job')::uuid,current_setting('test.reclaim_old_fence')::uuid,0,pg_temp.result(current_setting('test.reclaim_set')::uuid,0,'reclaim first'),'model-r','reclaim-0'); select public.world_npc_memory_summary_record_dispatch_result(current_setting('test.reclaim_job')::uuid,current_setting('test.reclaim_old_fence')::uuid,1,pg_temp.result(current_setting('test.reclaim_set')::uuid,1,'reclaim second'),'model-r','reclaim-1');
reset role; update private.world_npc_memory_outbox set lease_until=clock_timestamp()-interval '1 second' where id=current_setting('test.reclaim_job')::uuid;
set local role service_role; set local request.jwt.claim.role='service_role'; create temporary table pg_temp.reclaim_new as select public.world_npc_memory_claim('summary','npc-memory-summary-v2') claim;
select set_config('test.reclaim_new_fence',(select claim->>'fence' from pg_temp.reclaim_new),true);
select isnt(current_setting('test.reclaim_new_fence'),current_setting('test.reclaim_old_fence'),'reclaim produces current fence distinct from receipt fence');
select is(public.world_npc_memory_summary_finalize_v2(current_setting('test.reclaim_job')::uuid,current_setting('test.reclaim_new_fence')::uuid)->>'status','completed','reclaimed claim finalizes original received receipts');
reset role;
select is((select generation_manifest->'batches'->0->>'fence' from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.reclaim_set')::uuid)),current_setting('test.reclaim_old_fence'),'replay manifest retains original receipt fence');

-- Every incomplete or semantically divergent receipt state produces a single
-- whole-set extractive artifact with no provider prose or citations.
create function pg_temp.claim_v2(p_key text) returns jsonb language plpgsql security definer set search_path='' as $f$ declare c jsonb; begin perform set_config('request.jwt.claim.role','service_role',true); select public.world_npc_memory_claim('summary','npc-memory-summary-v2') into c; return c; end $f$;
select set_config('test.missing_set',pg_temp.make_set('final-missing')::text,true);
set local role service_role; set local request.jwt.claim.role='service_role'; select set_config('test.missing_claim',pg_temp.claim_v2('x')::text,true);
select is(public.world_npc_memory_summary_finalize_v2((current_setting('test.missing_claim')::jsonb->>'id')::uuid,(current_setting('test.missing_claim')::jsonb->>'fence')::uuid)->>'fallback','true','missing receipts use whole-set fallback');
reset role;
select ok((select content->>'mode'='extractive-v2' and model is null and content->'citations'='[]'::jsonb and generation_manifest->>'includedUnitCount'='2' and generation_manifest->>'omittedUnitCount'='0' from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.missing_set')::uuid)),'missing fallback is provider-free with complete ordered units');
select set_config('test.missing_hash',(select content_hash from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.missing_set')::uuid)),true); select set_config('test.missing_content',(select content::text from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.missing_set')::uuid)),true); select set_config('test.missing_manifest',(select generation_manifest::text from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.missing_set')::uuid)),true);
set local role service_role; set local request.jwt.claim.role='service_role'; select is(public.world_npc_memory_summary_finalize_v2((current_setting('test.missing_claim')::jsonb->>'id')::uuid,(current_setting('test.missing_claim')::jsonb->>'fence')::uuid)->>'status','reused','fallback replay is reused'); reset role;
select is((select content_hash from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.missing_set')::uuid)),current_setting('test.missing_hash'),'fallback replay preserves content hash byte-identically');
select ok((select content=current_setting('test.missing_content')::jsonb and generation_manifest=current_setting('test.missing_manifest')::jsonb from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.missing_set')::uuid)),'fallback replay preserves content and manifest byte-identically');
select set_config('test.prepared_set',pg_temp.make_set('final-prepared')::text,true);
set local role service_role; set local request.jwt.claim.role='service_role'; select set_config('test.prepared_claim',pg_temp.claim_v2('x')::text,true);
select public.world_npc_memory_summary_prepare_dispatch((current_setting('test.prepared_claim')::jsonb->>'id')::uuid,(current_setting('test.prepared_claim')::jsonb->>'fence')::uuid,0);
select is(public.world_npc_memory_summary_finalize_v2((current_setting('test.prepared_claim')::jsonb->>'id')::uuid,(current_setting('test.prepared_claim')::jsonb->>'fence')::uuid)->>'fallback','true','prepared receipt falls back');
select set_config('test.dispatched_set',pg_temp.make_set('final-dispatched')::text,true); select set_config('test.dispatched_claim',pg_temp.claim_v2('x')::text,true);
select public.world_npc_memory_summary_prepare_dispatch((current_setting('test.dispatched_claim')::jsonb->>'id')::uuid,(current_setting('test.dispatched_claim')::jsonb->>'fence')::uuid,0); select public.world_npc_memory_summary_mark_dispatched((current_setting('test.dispatched_claim')::jsonb->>'id')::uuid,(current_setting('test.dispatched_claim')::jsonb->>'fence')::uuid,0,'dispatch-only');
select is(public.world_npc_memory_summary_finalize_v2((current_setting('test.dispatched_claim')::jsonb->>'id')::uuid,(current_setting('test.dispatched_claim')::jsonb->>'fence')::uuid)->>'fallback','true','dispatched receipt falls back');
select set_config('test.mismatch_set',pg_temp.make_set('final-mismatch')::text,true); select set_config('test.mismatch_claim',pg_temp.claim_v2('x')::text,true);
select public.world_npc_memory_summary_prepare_dispatch((current_setting('test.mismatch_claim')::jsonb->>'id')::uuid,(current_setting('test.mismatch_claim')::jsonb->>'fence')::uuid,0); select public.world_npc_memory_summary_prepare_dispatch((current_setting('test.mismatch_claim')::jsonb->>'id')::uuid,(current_setting('test.mismatch_claim')::jsonb->>'fence')::uuid,1); select public.world_npc_memory_summary_mark_dispatched((current_setting('test.mismatch_claim')::jsonb->>'id')::uuid,(current_setting('test.mismatch_claim')::jsonb->>'fence')::uuid,0,'mismatch-0'); select public.world_npc_memory_summary_mark_dispatched((current_setting('test.mismatch_claim')::jsonb->>'id')::uuid,(current_setting('test.mismatch_claim')::jsonb->>'fence')::uuid,1,'mismatch-1');
select public.world_npc_memory_summary_record_dispatch_result((current_setting('test.mismatch_claim')::jsonb->>'id')::uuid,(current_setting('test.mismatch_claim')::jsonb->>'fence')::uuid,0,pg_temp.result(current_setting('test.mismatch_set')::uuid,0,'model prose one'),'model-one','mismatch-0'); select public.world_npc_memory_summary_record_dispatch_result((current_setting('test.mismatch_claim')::jsonb->>'id')::uuid,(current_setting('test.mismatch_claim')::jsonb->>'fence')::uuid,1,pg_temp.result(current_setting('test.mismatch_set')::uuid,1,'model prose two'),'model-two','mismatch-1');
select is(public.world_npc_memory_summary_finalize_v2((current_setting('test.mismatch_claim')::jsonb->>'id')::uuid,(current_setting('test.mismatch_claim')::jsonb->>'fence')::uuid)->>'fallback','true','model mismatch falls back whole-set');
reset role;
select ok((select content->>'summary' not like '%model prose%' and content->'citations'='[]'::jsonb from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.mismatch_set')::uuid)),'model mismatch fallback contains no model prose or citations');

select set_config('test.required_set',pg_temp.make_set('final-required')::text,true);
set local role service_role; set local request.jwt.claim.role='service_role'; select set_config('test.required_claim',pg_temp.claim_v2('x')::text,true);
select public.world_npc_memory_summary_prepare_dispatch((current_setting('test.required_claim')::jsonb->>'id')::uuid,(current_setting('test.required_claim')::jsonb->>'fence')::uuid,0); select public.world_npc_memory_summary_recover_dispatch((current_setting('test.required_claim')::jsonb->>'id')::uuid,(current_setting('test.required_claim')::jsonb->>'fence')::uuid,0);
select is(public.world_npc_memory_summary_finalize_v2((current_setting('test.required_claim')::jsonb->>'id')::uuid,(current_setting('test.required_claim')::jsonb->>'fence')::uuid)->>'fallback','true','fallback-required receipt finalizes extractively');
select set_config('test.over_set',pg_temp.make_set('final-over-cap')::text,true); select set_config('test.over_claim',pg_temp.claim_v2('x')::text,true);
select public.world_npc_memory_summary_prepare_dispatch((current_setting('test.over_claim')::jsonb->>'id')::uuid,(current_setting('test.over_claim')::jsonb->>'fence')::uuid,0); select public.world_npc_memory_summary_prepare_dispatch((current_setting('test.over_claim')::jsonb->>'id')::uuid,(current_setting('test.over_claim')::jsonb->>'fence')::uuid,1); select public.world_npc_memory_summary_mark_dispatched((current_setting('test.over_claim')::jsonb->>'id')::uuid,(current_setting('test.over_claim')::jsonb->>'fence')::uuid,0,'over-0'); select public.world_npc_memory_summary_mark_dispatched((current_setting('test.over_claim')::jsonb->>'id')::uuid,(current_setting('test.over_claim')::jsonb->>'fence')::uuid,1,'over-1');
select public.world_npc_memory_summary_record_dispatch_result((current_setting('test.over_claim')::jsonb->>'id')::uuid,(current_setting('test.over_claim')::jsonb->>'fence')::uuid,0,pg_temp.result(current_setting('test.over_set')::uuid,0,repeat('🦉',5999)),'model-cap','over-0'); select public.world_npc_memory_summary_record_dispatch_result((current_setting('test.over_claim')::jsonb->>'id')::uuid,(current_setting('test.over_claim')::jsonb->>'fence')::uuid,1,pg_temp.result(current_setting('test.over_set')::uuid,1,repeat('🦉',5999)),'model-cap','over-1');
select is(public.world_npc_memory_summary_finalize_v2((current_setting('test.over_claim')::jsonb->>'id')::uuid,(current_setting('test.over_claim')::jsonb->>'fence')::uuid)->>'fallback','true','over-cap all-received model falls back');
reset role;
select is((select generation_manifest->>'reason' from private.world_npc_memory_artifacts where source_hash=(select set_hash from private.world_npc_memory_summary_sets where id=current_setting('test.over_set')::uuid)),'model_content_byte_cap','over-cap manifest records deterministic fallback reason');

-- A receipt can be syntactically received while a compromised persistence path
-- has changed one immutable field.  Every such case must reject model mode for
-- the entire set, preserving only source-backed extractive evidence.
create temporary table pg_temp.tampered_receipts(target text primary key,set_id uuid not null,job_id uuid not null,fence uuid not null);
grant select on pg_temp.tampered_receipts to service_role;
create function pg_temp.make_tampered_receipt(p_target text) returns void language plpgsql security definer set search_path='' as $f$
declare s uuid; c jsonb; j uuid; f uuid;
begin
 s:=pg_temp.make_set('final-tampered-'||p_target);
 select public.world_npc_memory_claim('summary','npc-memory-summary-v2') into c;
 j:=(c->>'id')::uuid; f:=(c->>'fence')::uuid;
 perform public.world_npc_memory_summary_prepare_dispatch(j,f,0);
 perform public.world_npc_memory_summary_prepare_dispatch(j,f,1);
 perform public.world_npc_memory_summary_mark_dispatched(j,f,0,'tampered-'||p_target||'-0');
 perform public.world_npc_memory_summary_mark_dispatched(j,f,1,'tampered-'||p_target||'-1');
 perform public.world_npc_memory_summary_record_dispatch_result(j,f,0,pg_temp.result(s,0,'tampered model prose 0'),'tampered-model','tampered-'||p_target||'-0');
 perform public.world_npc_memory_summary_record_dispatch_result(j,f,1,pg_temp.result(s,1,'tampered model prose 1'),'tampered-model','tampered-'||p_target||'-1');
 insert into pg_temp.tampered_receipts values(p_target,s,j,f);
end $f$;
set local role service_role; set local request.jwt.claim.role='service_role';
select pg_temp.make_tampered_receipt('identity_hash');
select pg_temp.make_tampered_receipt('request_hash');
select pg_temp.make_tampered_receipt('result_hash');
select pg_temp.make_tampered_receipt('result');
reset role;
alter table private.world_npc_memory_summary_dispatches disable trigger world_npc_memory_summary_dispatch_guard;
update private.world_npc_memory_summary_dispatches d set identity_hash=repeat('0',64) from pg_temp.tampered_receipts t where t.target='identity_hash' and d.job_id=t.job_id and d.batch_ordinal=0;
alter table private.world_npc_memory_summary_dispatches enable trigger world_npc_memory_summary_dispatch_guard;
alter table private.world_npc_memory_summary_dispatches disable trigger world_npc_memory_summary_dispatch_guard;
update private.world_npc_memory_summary_dispatches d set request_hash=repeat('0',64) from pg_temp.tampered_receipts t where t.target='request_hash' and d.job_id=t.job_id and d.batch_ordinal=0;
alter table private.world_npc_memory_summary_dispatches enable trigger world_npc_memory_summary_dispatch_guard;
alter table private.world_npc_memory_summary_dispatches disable trigger world_npc_memory_summary_dispatch_guard;
update private.world_npc_memory_summary_dispatches d set result_hash=repeat('0',64) from pg_temp.tampered_receipts t where t.target='result_hash' and d.job_id=t.job_id and d.batch_ordinal=0;
alter table private.world_npc_memory_summary_dispatches enable trigger world_npc_memory_summary_dispatch_guard;
alter table private.world_npc_memory_summary_dispatches disable trigger world_npc_memory_summary_dispatch_guard;
update private.world_npc_memory_summary_dispatches d set result=jsonb_set(result,'{summary}','"tampered result prose"'::jsonb) from pg_temp.tampered_receipts t where t.target='result' and d.job_id=t.job_id and d.batch_ordinal=0;
alter table private.world_npc_memory_summary_dispatches enable trigger world_npc_memory_summary_dispatch_guard;
set local role service_role; set local request.jwt.claim.role='service_role';
select public.world_npc_memory_summary_finalize_v2(job_id,fence) from pg_temp.tampered_receipts order by target;
reset role;
select ok((select a.content->>'mode'='extractive-v2' and a.model is null and a.content->'citations'='[]'::jsonb and a.content->>'summary' not like '%tampered%' and a.generation_manifest->>'mode'='extractive-v2' and a.generation_manifest->'batches'->0->>'identityHash'=repeat('0',64) from pg_temp.tampered_receipts t join private.world_npc_memory_summary_sets s on s.id=t.set_id join private.world_npc_memory_artifacts a on a.instance_id=s.instance_id and a.source_hash=s.set_hash where t.target='identity_hash'),'tampered identity hash forces provider-free whole-set fallback with receipt evidence');
select ok((select a.content->>'mode'='extractive-v2' and a.model is null and a.content->'citations'='[]'::jsonb and a.content->>'summary' not like '%tampered%' and a.generation_manifest->>'mode'='extractive-v2' and a.generation_manifest->'batches'->0->>'requestHash'=repeat('0',64) from pg_temp.tampered_receipts t join private.world_npc_memory_summary_sets s on s.id=t.set_id join private.world_npc_memory_artifacts a on a.instance_id=s.instance_id and a.source_hash=s.set_hash where t.target='request_hash'),'tampered request hash forces provider-free whole-set fallback with receipt evidence');
select ok((select a.content->>'mode'='extractive-v2' and a.model is null and a.content->'citations'='[]'::jsonb and a.content->>'summary' not like '%tampered%' and a.generation_manifest->>'mode'='extractive-v2' and a.generation_manifest->'batches'->0->>'resultHash'=repeat('0',64) from pg_temp.tampered_receipts t join private.world_npc_memory_summary_sets s on s.id=t.set_id join private.world_npc_memory_artifacts a on a.instance_id=s.instance_id and a.source_hash=s.set_hash where t.target='result_hash'),'tampered result hash forces provider-free whole-set fallback with receipt evidence');
select ok((select a.content->>'mode'='extractive-v2' and a.model is null and a.content->'citations'='[]'::jsonb and a.content->>'summary' not like '%tampered%' and a.generation_manifest->>'mode'='extractive-v2' and a.generation_manifest->'batches'->0->>'resultHash'<>encode(extensions.digest(private.world_canonical_json(d.result),'sha256'),'hex') from pg_temp.tampered_receipts t join private.world_npc_memory_summary_sets s on s.id=t.set_id join private.world_npc_memory_artifacts a on a.instance_id=s.instance_id and a.source_hash=s.set_hash join private.world_npc_memory_summary_dispatches d on d.job_id=t.job_id and d.batch_ordinal=0 where t.target='result'),'tampered result JSON forces provider-free whole-set fallback with receipt evidence');

-- A unique-key collision is safe only when the existing immutable artifact is
-- an exact replay.  A structurally legal but divergent preseed must be atomic.
select set_config('test.preseed_set',pg_temp.make_set('final-preseed-conflict')::text,true);
set local role service_role; set local request.jwt.claim.role='service_role'; select set_config('test.preseed_claim',pg_temp.claim_v2('x')::text,true); reset role;
insert into private.world_npc_memory_artifacts(save_id,instance_id,artifact_kind,source_kind,source_ids,source_versions,source_hash,processor_version,prompt_release_id,prompt_key,prompt_revision_id,model,contract_id,contract_hash,fallback,disclosure_class,content,content_hash,generation_manifest)
select j.save_id,j.instance_id,s.summary_kind,'memory_set',array[extensions.gen_random_uuid()],array[999::bigint],s.set_hash,j.processor_version,j.prompt_release_id,'npc_memory.summary.v2',(select revision_id from private.prompt_release_entries where release_id=j.prompt_release_id and prompt_key='npc_memory.summary.v2'),'preseed-model','npc-memory-summary-v2','f279a108f11e212c77e4876521e9ee47092171b6d2a820d83a245d57a3c64e03',null,s.disclosure_class,jsonb_build_object('version','npc-memory-summary-v2','mode','model','summary','preseed divergent prose','citations','[]'::jsonb),encode(extensions.digest(private.world_canonical_json(jsonb_build_object('version','npc-memory-summary-v2','mode','model','summary','preseed divergent prose','citations','[]'::jsonb)),'sha256'),'hex'),jsonb_build_object('version','v2-receipts-1','mode','model','batches','[]'::jsonb)
from private.world_npc_memory_outbox j join private.world_npc_memory_summary_sets s on s.id=j.source_id where j.id=(current_setting('test.preseed_claim')::jsonb->>'id')::uuid;
set local role service_role; set local request.jwt.claim.role='service_role'; select throws_ok($$select public.world_npc_memory_summary_finalize_v2((current_setting('test.preseed_claim')::jsonb->>'id')::uuid,(current_setting('test.preseed_claim')::jsonb->>'fence')::uuid)$$,'PT409',null,'divergent preseeded v2 artifact rejects finalization'); reset role;
select ok((select status='processing' from private.world_npc_memory_outbox where id=(current_setting('test.preseed_claim')::jsonb->>'id')::uuid),'preseed conflict leaves job processing');
select is((select count(*) from private.world_npc_memory_artifacts a join private.world_npc_memory_summary_sets s on s.instance_id=a.instance_id and s.set_hash=a.source_hash where s.id=current_setting('test.preseed_set')::uuid),1::bigint,'preseed conflict creates no second artifact');

-- 128 immutable leaves make the fixed duplicated coverage manifest too large
-- even before adding a fallback unit.  This is intentionally source-backed.
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at)
select ('19500000-0010-4001-8000-'||lpad(g::text,12,'0'))::uuid,save_id,instance_id,npc_id,version_id,'19500000-0000-4000-8000-000000000001','large manifest evidence '||g,g+100,revision,1,'completed',clock_timestamp()+interval '5 minutes',jsonb_build_object('reply','coverage '||g),clock_timestamp() from pg_temp.f cross join generate_series(1,128) g;
select private.world_npc_memory_project_source('dialogue_turn',('19500000-0010-4001-8000-'||lpad(g::text,12,'0'))::uuid) from generate_series(1,128) g;
insert into private.world_npc_memories(id,turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id)
select ('19500000-0011-4001-8000-'||lpad(g::text,12,'0'))::uuid,('19500000-0010-4001-8000-'||lpad(g::text,12,'0'))::uuid,instance_id,'interaction','fixed manifest unit '||g,'unit '||g,'npc',3,'{}',save_id,('19500000-0012-4001-8000-'||lpad(g::text,12,'0'))::uuid,1,'dialogue_turn',('19500000-0010-4001-8000-'||lpad(g::text,12,'0'))::uuid,1,private.world_npc_memory_source_hash('dialogue_turn',('19500000-0010-4001-8000-'||lpad(g::text,12,'0'))::uuid),1,g,1,g,'attributed','npc_known',instance_id from pg_temp.f cross join generate_series(1,128) g;
create function pg_temp.large_set() returns uuid language plpgsql security definer set search_path='' as $f$ declare sid uuid; begin select id into sid from private.world_npc_memory_register_summary_set('episode_summary','final-pt413',(select max(ledger_sequence) from private.world_npc_memory_sources where source_kind='dialogue_turn' and source_id between '19500000-0010-4001-8000-000000000001'::uuid and '19500000-0010-4001-8000-000000000128'::uuid and disclosure_class='npc_known'),'npc_known',(select jsonb_agg(jsonb_build_object('ordinal',g-1,'sourceKind','dialogue_turn','sourceId',('19500000-0010-4001-8000-'||lpad(g::text,12,'0'))::uuid,'sourceVersion',1) order by g) from generate_series(1,128) g),jsonb_build_array(jsonb_build_object('batchOrdinal',0,'firstLeafOrdinal',0,'lastLeafOrdinal',63,'leafCount',64),jsonb_build_object('batchOrdinal',1,'firstLeafOrdinal',64,'lastLeafOrdinal',127,'leafCount',64)),'npc-memory-summary-v2'); return sid; end $f$;
select set_config('test.large_set',pg_temp.large_set()::text,true);
set local role service_role; set local request.jwt.claim.role='service_role'; create temporary table pg_temp.large_claim as select public.world_npc_memory_claim('summary','npc-memory-summary-v2') claim; select set_config('test.large_job',(select claim->>'id' from pg_temp.large_claim),true); select set_config('test.large_fence',(select claim->>'fence' from pg_temp.large_claim),true); reset role;
select ok((select not (private.world_npc_memory_summary_v2_fallback_plan(current_setting('test.large_set')::uuid,(select jsonb_agg(jsonb_build_object('ordinal',ordinal,'sourceKind',source_kind,'sourceId',source_id,'sourceVersion',source_version,'sourceHash',source_hash,'ledgerSequence',ledger_sequence) order by ordinal) from private.world_npc_memory_summary_leaves where set_id=current_setting('test.large_set')::uuid),(select jsonb_agg(jsonb_build_object('ordinal',batch_ordinal,'firstLeafOrdinal',first_leaf_ordinal,'lastLeafOrdinal',last_leaf_ordinal,'leafCount',leaf_count) order by batch_ordinal) from private.world_npc_memory_summary_batches where set_id=current_setting('test.large_set')::uuid))->>'fits')::boolean),'large fixed manifest cannot fit 32KiB fallback');
select ok((select (private.world_npc_memory_summary_v2_fallback_plan(current_setting('test.large_set')::uuid,(select jsonb_agg(jsonb_build_object('ordinal',ordinal,'sourceKind',source_kind,'sourceId',source_id,'sourceVersion',source_version,'sourceHash',source_hash,'ledgerSequence',ledger_sequence) order by ordinal) from private.world_npc_memory_summary_leaves where set_id=current_setting('test.large_set')::uuid),(select jsonb_agg(jsonb_build_object('ordinal',batch_ordinal,'firstLeafOrdinal',first_leaf_ordinal,'lastLeafOrdinal',last_leaf_ordinal,'leafCount',leaf_count) order by batch_ordinal) from private.world_npc_memory_summary_batches where set_id=current_setting('test.large_set')::uuid))->>'canonicalContentBytes')::integer>32768),'measured minimal canonical fallback bytes exceed 32KiB');
set local role service_role; set local request.jwt.claim.role='service_role'; select throws_ok($$select public.world_npc_memory_summary_finalize_v2(current_setting('test.large_job')::uuid,current_setting('test.large_fence')::uuid)$$,'PT413',null,'unfit fixed coverage returns recoverable PT413'); reset role;
select ok((select status='processing' and not exists(select 1 from private.world_npc_memory_artifacts a where a.instance_id=j.instance_id and a.source_hash=j.source_hash) from private.world_npc_memory_outbox j where id=current_setting('test.large_job')::uuid),'PT413 is atomic: no artifact and no completion');

select set_config('test.invalidated_set',pg_temp.make_set('final-invalidated')::text,true); set local role service_role; set local request.jwt.claim.role='service_role'; select set_config('test.invalidated_claim',pg_temp.claim_v2('x')::text,true); reset role;
update private.world_npc_memory_summary_sets set closure_status='invalidated',invalidated_at=clock_timestamp() where id=current_setting('test.invalidated_set')::uuid;
set local role service_role; set local request.jwt.claim.role='service_role'; select throws_ok($$select public.world_npc_memory_summary_finalize_v2((current_setting('test.invalidated_claim')::jsonb->>'id')::uuid,(current_setting('test.invalidated_claim')::jsonb->>'fence')::uuid)$$,'PT409',null,'invalidated set cannot finalize'); reset role;
delete from private.world_npc_instances where id=(select instance_id from pg_temp.f);
set local role service_role; set local request.jwt.claim.role='service_role'; select throws_ok($$select public.world_npc_memory_summary_finalize_v2(current_setting('test.job')::uuid,current_setting('test.fence')::uuid)$$,'PT409',null,'purged resident cannot be resurrected by late finalization'); reset role;
select is((select count(*) from private.world_npc_memory_artifacts),0::bigint,'resident purge removes final artifacts and receipt paths');

set local role authenticated; set local request.jwt.claim.role='authenticated';
select throws_ok($$select public.world_npc_memory_summary_finalize_v2(current_setting('test.job')::uuid,current_setting('test.fence')::uuid)$$,'42501',null,'authenticated finalizer call is denied');
reset role;
select * from finish();
rollback;
