begin;
create extension if not exists pgtap with schema extensions;
select plan(44);
insert into auth.users(id,email,role,aud) values ('18900000-0000-4000-8000-000000000001','producer-owner@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18900000-0000-4000-8000-000000000001'; select public.create_tavern(); reset role;
create temporary table pg_temp.f as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid instance_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
insert into private.world_quest_events(id,quest_id,save_id,instance_id,day_number,step_index,action,approach,skill,difficulty,preparation_before,preparation_after,hospitality,readiness,chance,draw,outcome,narration,public_news) select '18900000-0000-4000-8000-000000000010',q.id,f.save_id,f.instance_id,1,0,'prepare','scouting',1,q.difficulty,0,1,0,0,null,null,'prepared','Prepared.',false from pg_temp.f f join lateral(select * from private.world_quests where instance_id=f.instance_id limit 1) q on true;
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.f)),0::bigint,'prepared event creates no closure request');
insert into private.world_quest_events(id,quest_id,save_id,instance_id,day_number,step_index,action,approach,skill,difficulty,preparation_before,preparation_after,hospitality,readiness,chance,draw,outcome,narration,public_news) select '18900000-0000-4000-8000-000000000011',q.id,f.save_id,f.instance_id,2,1,'attempt','scouting',1,q.difficulty,1,1,0,0,50,99,'failed','Failed.',false from pg_temp.f f join lateral(select * from private.world_quests where instance_id=f.instance_id limit 1) q on true;
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.f) and summary_kind='quest_summary'),1::bigint,'terminal quest trigger creates exactly one request after ledger trigger');
select lives_ok($$select private.world_npc_memory_request_quest('18900000-0000-4000-8000-000000000011')$$,'terminal request seam is idempotent on retry');
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.f) and summary_kind='quest_summary'),1::bigint,'terminal delivery remains idempotent');
-- Settlement producer creates an episode request from the exact day cutoff;
-- only an extract gap suppresses immediate local set/outbox registration.
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result) select '18900000-0000-4000-8000-000000000020',f.save_id,f.instance_id,i.npc_id,i.version_id,'18900000-0000-4000-8000-000000000001','Settlement source',0,f.revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Recorded."}' from pg_temp.f f join private.world_npc_instances i on i.id=f.instance_id;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18900000-0000-4000-8000-000000000020';
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id) select id,instance_id,'interaction','Settlement meaningful','Recorded.','npc',2,'{}',save_id,extensions.gen_random_uuid(),1,'dialogue_turn',id,1,private.world_npc_memory_source_hash('dialogue_turn',id),1,0,1,0,'attributed','npc_known',instance_id from private.world_npc_dialogue_turns where id='18900000-0000-4000-8000-000000000020';
insert into private.world_settlements(id,save_id,day_number,source_revision,input_fingerprint,status,deadline_at,input_snapshot,input_version) select '18900000-0000-4000-8000-000000000021',save_id,1,revision,'producer-processing','processing',clock_timestamp(),'{}','fixture-v1' from pg_temp.f;
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.f) and summary_kind='episode_summary'),0::bigint,'processing settlement creates no episode request');
update public.tavern_saves set current_day=2 where id=(select save_id from pg_temp.f);
update private.world_settlements set status='completed',completed_at=clock_timestamp() where id='18900000-0000-4000-8000-000000000021';
select is((select cutoff_ledger_sequence from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.f) and summary_kind='episode_summary' and closed_day=1), (select max(ledger_sequence) from private.world_npc_memory_sources where instance_id=(select instance_id from pg_temp.f) and occurred_day<=1),'terminal settlement uses exact same-day ledger cutoff');
select is((select count(*) from private.world_npc_memory_outbox where instance_id=(select instance_id from pg_temp.f) and source_kind='memory_set'),0::bigint,'extract gap prevents summary job creation without provider work');
update private.world_npc_memory_outbox set status='completed',completed_at=clock_timestamp(),lease_until=null where instance_id=(select instance_id from pg_temp.f) and source_id<>'18900000-0000-4000-8000-000000000020' and status='pending';
set local role service_role; set local request.jwt.claim.role='service_role';
create temporary table pg_temp.gap_claim as select public.world_npc_memory_claim('extract','npc-memory-v1') claim;
select is((select claim->>'sourceId' from pg_temp.gap_claim),'18900000-0000-4000-8000-000000000020','extract claim belongs to the settlement fixture source');
select lives_ok($$select public.world_npc_memory_complete((select (claim->>'id')::uuid from pg_temp.gap_claim),(select (claim->>'fence')::uuid from pg_temp.gap_claim),'[]'::jsonb,null)$$,'real extract completion succeeds through service seam');
reset role;
select is((select count(*) from private.world_npc_memory_outbox o join private.world_npc_memory_summary_sets s on s.id=o.source_id where o.source_kind='memory_set' and s.instance_id=(select instance_id from pg_temp.f) and s.summary_kind='episode_summary'),1::bigint,'gap completion retry creates exactly one episode summary job');
select lives_ok($$update private.world_settlements set status='completed' where id='18900000-0000-4000-8000-000000000021'$$,'repeated terminal update is a no-op');
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.f) and summary_kind='episode_summary' and closed_day=1),1::bigint,'repeated terminal state has one request');
insert into auth.users(id,email,role,aud) values ('18900000-0000-4000-8000-000000000002','producer-contiguous@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18900000-0000-4000-8000-000000000002'; select public.create_tavern(); reset role;
create temporary table pg_temp.c as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid instance_id,(snapshot->'roster'->0->>'npcId')::uuid npc_id,(snapshot->'roster'->0->>'versionId')::uuid version_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result) select '18900000-0000-4000-8000-000000000030',save_id,instance_id,npc_id,version_id,'18900000-0000-4000-8000-000000000002','Contiguous source',0,revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Done."}' from pg_temp.c;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18900000-0000-4000-8000-000000000030';
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id) select id,instance_id,'interaction','Contiguous meaningful','Done.','npc',2,'{}',save_id,extensions.gen_random_uuid(),1,'dialogue_turn',id,1,private.world_npc_memory_source_hash('dialogue_turn',id),1,0,1,0,'attributed','npc_known',instance_id from private.world_npc_dialogue_turns where id='18900000-0000-4000-8000-000000000030';
set local role service_role; set local request.jwt.claim.role='service_role'; create temporary table pg_temp.cclaim as select public.world_npc_memory_claim('extract','npc-memory-v1') claim; select is((select claim->>'sourceId' from pg_temp.cclaim),'18900000-0000-4000-8000-000000000030','contiguous extract claim belongs to its fixture source'); select lives_ok($$select public.world_npc_memory_complete((select (claim->>'id')::uuid from pg_temp.cclaim),(select (claim->>'fence')::uuid from pg_temp.cclaim),'[]'::jsonb,null)$$,'pre-terminal contiguous extract completes through service seam'); reset role;
update public.tavern_saves set current_day=2 where id=(select save_id from pg_temp.c);
insert into private.world_settlements(id,save_id,day_number,source_revision,input_fingerprint,status,deadline_at,input_snapshot,input_version) select '18900000-0000-4000-8000-000000000031',save_id,1,revision,'producer-contiguous','processing',clock_timestamp(),'{}','fixture-v1' from pg_temp.c;
update private.world_settlements set status='completed',completed_at=clock_timestamp() where id='18900000-0000-4000-8000-000000000031';
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.c)),1::bigint,'contiguous terminal creates one closure request');
select is((select count(*) from private.world_npc_memory_summary_sets where instance_id=(select instance_id from pg_temp.c)),1::bigint,'contiguous terminal immediately registers one set');
select is((select count(*) from private.world_npc_memory_outbox o join private.world_npc_memory_summary_sets s on s.id=o.source_id where s.instance_id=(select instance_id from pg_temp.c)),1::bigint,'contiguous terminal creates one memory-set job');
select lives_ok($$update private.world_settlements set status='completed' where id='18900000-0000-4000-8000-000000000031'$$,'contiguous repeated terminal update is harmless');
select throws_ok($$delete from private.world_npc_memory_closure_requests$$,'PT409',null,'producer requests retain purge-safe append-only guard');
-- Failed and expired settlements are terminal producers too.  Keep each
-- fresh instance pending so these assertions prove request creation/cutoffs,
-- not a provider or local summary path.
insert into auth.users(id,email,role,aud) values ('18900000-0000-4000-8000-000000000003','producer-terminal@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18900000-0000-4000-8000-000000000003'; select public.create_tavern(); reset role;
create temporary table pg_temp.t as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid failed_instance_id,(snapshot->'roster'->1->>'instanceId')::uuid expired_instance_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result)
select '18900000-0000-4000-8000-000000000040',t.save_id,t.failed_instance_id,i.npc_id,i.version_id,'18900000-0000-4000-8000-000000000003','Failed terminal source',0,t.revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Recorded."}' from pg_temp.t t join private.world_npc_instances i on i.id=t.failed_instance_id;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18900000-0000-4000-8000-000000000040';
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result)
select '18900000-0000-4000-8000-000000000041',t.save_id,t.expired_instance_id,i.npc_id,i.version_id,'18900000-0000-4000-8000-000000000003','Expired terminal source',0,t.revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Recorded."}' from pg_temp.t t join private.world_npc_instances i on i.id=t.expired_instance_id;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18900000-0000-4000-8000-000000000041';
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id)
select id,instance_id,'interaction','Terminal settlement meaningful','Recorded.','npc',2,'{}',save_id,extensions.gen_random_uuid(),1,'dialogue_turn',id,1,private.world_npc_memory_source_hash('dialogue_turn',id),1,0,1,0,'attributed','npc_known',instance_id from private.world_npc_dialogue_turns where id in ('18900000-0000-4000-8000-000000000040','18900000-0000-4000-8000-000000000041');
insert into private.world_settlements(id,save_id,day_number,source_revision,input_fingerprint,status,deadline_at,input_snapshot,input_version) values
 ('18900000-0000-4000-8000-000000000042',(select save_id from pg_temp.t),1,(select revision from pg_temp.t),'failed-terminal','processing',clock_timestamp(),'{}','fixture-v1'),
 ('18900000-0000-4000-8000-000000000043',(select save_id from pg_temp.t),2,(select revision from pg_temp.t),'expired-terminal','processing',clock_timestamp(),'{}','fixture-v1');
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id in ((select failed_instance_id from pg_temp.t),(select expired_instance_id from pg_temp.t))),0::bigint,'queued or processing settlements do not create closure requests');
update public.tavern_saves set current_day=3 where id=(select save_id from pg_temp.t);
update private.world_settlements set status='failed',completed_at=clock_timestamp() where id='18900000-0000-4000-8000-000000000042';
select is((select cutoff_ledger_sequence from private.world_npc_memory_closure_requests where instance_id=(select failed_instance_id from pg_temp.t)),(select max(ledger_sequence) from private.world_npc_memory_sources where instance_id=(select failed_instance_id from pg_temp.t) and occurred_day<=1),'failed settlement uses its exact authoritative cutoff');
update private.world_settlements set status='failed' where id='18900000-0000-4000-8000-000000000042';
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id=(select failed_instance_id from pg_temp.t)),1::bigint,'repeated failed terminal status is idempotent');
update private.world_settlements set status='expired',completed_at=clock_timestamp() where id='18900000-0000-4000-8000-000000000043';
select is((select cutoff_ledger_sequence from private.world_npc_memory_closure_requests where instance_id=(select expired_instance_id from pg_temp.t)),(select max(ledger_sequence) from private.world_npc_memory_sources where instance_id=(select expired_instance_id from pg_temp.t) and occurred_day<=2),'expired settlement uses its exact authoritative cutoff');
update private.world_settlements set status='expired' where id='18900000-0000-4000-8000-000000000043';
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id=(select expired_instance_id from pg_temp.t)),1::bigint,'repeated expired terminal status is idempotent');
-- Private producer/backfill helpers must remain unavailable to players.
select ok(not has_function_privilege('authenticated','private.world_npc_memory_quest_closure_producer()','EXECUTE'),'authenticated cannot invoke the quest producer');
select ok(not has_function_privilege('authenticated','private.world_npc_memory_settlement_closure_producer()','EXECUTE'),'authenticated cannot invoke the settlement producer');
select ok(not has_function_privilege('authenticated','private.world_npc_memory_backfill_closures()','EXECUTE'),'authenticated cannot invoke historical backfill');
-- Historical closure replay consumes the immutable ledger only.  These two
-- saves cover two closed days, a current-day exclusion, no-summary greeting,
-- terminal quest, a deliberately non-day-ordered ledger, and 65 leaves.
insert into auth.users(id,email,role,aud) values
 ('18900000-0000-4000-8000-000000000004','producer-history-a@example.test','authenticated','authenticated'),
 ('18900000-0000-4000-8000-000000000005','producer-history-b@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18900000-0000-4000-8000-000000000004'; select public.create_tavern(); reset role;
create temporary table pg_temp.h1 as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid instance_id,(snapshot->'roster'->0->>'npcId')::uuid npc_id,(snapshot->'roster'->0->>'versionId')::uuid version_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18900000-0000-4000-8000-000000000005'; select public.create_tavern(); reset role;
create temporary table pg_temp.h2 as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid instance_id,(snapshot->'roster'->0->>'npcId')::uuid npc_id,(snapshot->'roster'->0->>'versionId')::uuid version_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at)
select ('18900000-0000-4004-8000-'||lpad(g::text,12,'0'))::uuid,h.save_id,h.instance_id,h.npc_id,h.version_id,'18900000-0000-4000-8000-000000000004','Historical leaf '||g,g,h.revision,1,'completed',clock_timestamp()+interval '5 minutes',jsonb_build_object('reply','Leaf '||g),clock_timestamp() from pg_temp.h1 h cross join generate_series(0,64) g;
select private.world_npc_memory_project_source('dialogue_turn',('18900000-0000-4004-8000-'||lpad(g::text,12,'0'))::uuid) from generate_series(0,64) g;
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id)
select id,instance_id,'interaction','Historical meaningful '||input_sequence,'Leaf','npc',2,'{}',save_id,extensions.gen_random_uuid(),1,'dialogue_turn',id,1,private.world_npc_memory_source_hash('dialogue_turn',id),1,input_sequence,1,input_sequence,'attributed','npc_known',instance_id from private.world_npc_dialogue_turns where instance_id=(select instance_id from pg_temp.h1) and day_number=1;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at)
select '18900000-0000-4000-8000-000000000050',save_id,instance_id,npc_id,version_id,'18900000-0000-4000-8000-000000000004','Day two greeting',65,revision,2,'completed',clock_timestamp()+interval '5 minutes','{"reply":"Hello."}',clock_timestamp() from pg_temp.h1;
select private.world_npc_memory_project_source('dialogue_turn','18900000-0000-4000-8000-000000000050');
-- Project the current-day row before an older day to prove backfill derives
-- <= day cutoffs and never turns the still-open day into a request.
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at)
select '18900000-0000-4000-8000-000000000051',save_id,instance_id,npc_id,version_id,'18900000-0000-4000-8000-000000000004','Open day',66,revision,3,'completed',clock_timestamp()+interval '5 minutes','{"reply":"Later."}',clock_timestamp() from pg_temp.h1;
select private.world_npc_memory_project_source('dialogue_turn','18900000-0000-4000-8000-000000000051');
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at)
select '18900000-0000-4000-8000-000000000052',save_id,instance_id,npc_id,version_id,'18900000-0000-4000-8000-000000000005','Second-save day one',0,revision,1,'completed',clock_timestamp()+interval '5 minutes','{"reply":"Remember."}',clock_timestamp() from pg_temp.h2;
select private.world_npc_memory_project_source('dialogue_turn','18900000-0000-4000-8000-000000000052');
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id)
select id,instance_id,'interaction','Second-save meaningful','Remember.','npc',2,'{}',save_id,extensions.gen_random_uuid(),1,'dialogue_turn',id,1,private.world_npc_memory_source_hash('dialogue_turn',id),1,0,1,0,'attributed','npc_known',instance_id from private.world_npc_dialogue_turns where id='18900000-0000-4000-8000-000000000052';
alter table private.world_quest_events disable trigger world_npc_memory_quest_source_closure;
insert into private.world_quest_events(id,quest_id,save_id,instance_id,day_number,step_index,action,approach,skill,difficulty,preparation_before,preparation_after,hospitality,readiness,chance,draw,outcome,narration,public_news)
select '18900000-0000-4000-8000-000000000053',q.id,h.save_id,h.instance_id,2,1,'attempt','scouting',1,q.difficulty,1,1,0,0,50,99,'failed','Historical terminal.',false from pg_temp.h2 h join lateral(select * from private.world_quests where instance_id=h.instance_id limit 1) q on true;
alter table private.world_quest_events enable trigger world_npc_memory_quest_source_closure;
select ok(exists(select 1 from private.world_npc_memory_sources where source_kind='quest_event' and source_id='18900000-0000-4000-8000-000000000053'),'historical terminal retains its authoritative ledger source');
select ok(not exists(select 1 from private.world_npc_memory_closure_requests where terminal_event_id='18900000-0000-4000-8000-000000000053'),'historical terminal starts without a live closure request');
-- Project an open-day receipt and then a late historical day-one receipt.
-- Consequently the day-two cutoff must include a higher sequence that is
-- not stamped day two; the old grouped-max backfill query rejected this.
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at)
select '18900000-0000-4000-8000-000000000054',save_id,instance_id,npc_id,version_id,'18900000-0000-4000-8000-000000000005','Second-save open day',1,revision,3,'completed',clock_timestamp()+interval '5 minutes','{"reply":"Open."}',clock_timestamp() from pg_temp.h2;
select private.world_npc_memory_project_source('dialogue_turn','18900000-0000-4000-8000-000000000054');
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at)
select '18900000-0000-4000-8000-000000000055',save_id,instance_id,npc_id,version_id,'18900000-0000-4000-8000-000000000005','Late historical day one',2,revision,1,'completed',clock_timestamp()+interval '5 minutes','{"reply":"Late."}',clock_timestamp() from pg_temp.h2;
select private.world_npc_memory_project_source('dialogue_turn','18900000-0000-4000-8000-000000000055');
update public.tavern_saves set current_day=3 where id in ((select save_id from pg_temp.h1),(select save_id from pg_temp.h2));
create temporary table pg_temp.history_canonical as select (select count(*) from private.world_npc_memory_sources where save_id in ((select save_id from pg_temp.h1),(select save_id from pg_temp.h2))) sources,(select count(*) from private.world_npc_memories where save_id in ((select save_id from pg_temp.h1),(select save_id from pg_temp.h2))) memories,(select count(*) from private.world_quest_events where save_id=(select save_id from pg_temp.h2)) quests,(select count(*) from private.world_npc_memories where save_id in ((select save_id from pg_temp.h1),(select save_id from pg_temp.h2)) and commitment_status is not null) commitments;
select is(private.world_npc_memory_backfill_closures(),0,'historical gap pass creates durable requests without summary work');
select is((select array_agg(attempts order by id) from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.h1) and status='blocked_gap'),array[1]::integer[],'one backfill schedule call handles the first instance once');
select is((select array_agg(attempts order by id) from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.h2) and status='blocked_gap'),array[1,1,1]::integer[],'one backfill schedule call handles the second instance once');
select is((select jsonb_build_array((select count(*) from private.world_npc_memory_sources where save_id in ((select save_id from pg_temp.h1),(select save_id from pg_temp.h2))),(select count(*) from private.world_npc_memories where save_id in ((select save_id from pg_temp.h1),(select save_id from pg_temp.h2))),(select count(*) from private.world_quest_events where save_id=(select save_id from pg_temp.h2)),(select count(*) from private.world_npc_memories where save_id in ((select save_id from pg_temp.h1),(select save_id from pg_temp.h2)) and commitment_status is not null))),(select jsonb_build_array(sources,memories,quests,commitments) from pg_temp.history_canonical),'backfill does not replay source projection or mutate canonical memories, quests, or commitments');
select is((select reason from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.h1) and closed_day=2),'no_summary','historical greeting closes with no-summary');
select ok(not exists(select 1 from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.h1) and closed_day=3),'current open day is excluded from historical backfill');
select ok(exists(select 1 from private.world_npc_memory_closure_requests where terminal_event_id='18900000-0000-4000-8000-000000000053'),'historical terminal quest remains a durable closure request');
update private.world_npc_memory_outbox set status='completed',completed_at=clock_timestamp(),lease_until=null where instance_id in ((select instance_id from pg_temp.h1),(select instance_id from pg_temp.h2)) and processor_kind='extract';
select private.world_npc_memory_refresh_watermark((select instance_id from pg_temp.h1),'extract','npc-memory-v1');
select private.world_npc_memory_refresh_watermark((select instance_id from pg_temp.h2),'extract','npc-memory-v1');
select is(private.world_npc_memory_backfill_closures(),4,'interrupted historical pass resumes and schedules every contiguous closure');
select is((select count(*) from private.world_npc_memory_summary_leaves l join private.world_npc_memory_summary_sets s on s.id=l.set_id where s.instance_id=(select instance_id from pg_temp.h1)),65::bigint,'historical 65-leaf closure is not clipped');
create temporary table pg_temp.history_result as select (select count(*) from private.world_npc_memory_closure_requests where instance_id in ((select instance_id from pg_temp.h1),(select instance_id from pg_temp.h2))) requests,(select count(*) from private.world_npc_memory_summary_sets where instance_id in ((select instance_id from pg_temp.h1),(select instance_id from pg_temp.h2))) sets,(select count(*) from private.world_npc_memory_outbox where instance_id in ((select instance_id from pg_temp.h1),(select instance_id from pg_temp.h2)) and source_kind='memory_set') jobs;
select is(private.world_npc_memory_backfill_closures(),0,'completed historical replay is idempotent');
select is((select jsonb_build_array((select count(*) from private.world_npc_memory_closure_requests where instance_id in ((select instance_id from pg_temp.h1),(select instance_id from pg_temp.h2))),(select count(*) from private.world_npc_memory_summary_sets where instance_id in ((select instance_id from pg_temp.h1),(select instance_id from pg_temp.h2))),(select count(*) from private.world_npc_memory_outbox where instance_id in ((select instance_id from pg_temp.h1),(select instance_id from pg_temp.h2)) and source_kind='memory_set'))),(select jsonb_build_array(requests,sets,jobs) from pg_temp.history_result),'historical rerun leaves requests, sets, and jobs stable');
-- This deliberately fails scheduling.  The trigger must swallow that failure
-- only after persisting its durable request, so settlement authority survives.
insert into auth.users(id,email,role,aud) values ('18900000-0000-4000-8000-000000000006','producer-scheduler-failure@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18900000-0000-4000-8000-000000000006'; select public.create_tavern(); reset role;
create temporary table pg_temp.r as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid instance_id,(snapshot->'roster'->0->>'npcId')::uuid npc_id,(snapshot->'roster'->0->>'versionId')::uuid version_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result)
select '18900000-0000-4000-8000-000000000060',save_id,instance_id,npc_id,version_id,'18900000-0000-4000-8000-000000000006','Scheduler failure source',0,revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Durable."}' from pg_temp.r;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18900000-0000-4000-8000-000000000060';
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id)
select id,instance_id,'interaction','Scheduler failure meaningful','Durable.','npc',2,'{}',save_id,extensions.gen_random_uuid(),1,'dialogue_turn',id,1,private.world_npc_memory_source_hash('dialogue_turn',id),1,0,1,0,'attributed','npc_known',instance_id from private.world_npc_dialogue_turns where id='18900000-0000-4000-8000-000000000060';
update public.tavern_saves set current_day=2 where id=(select save_id from pg_temp.r);
insert into private.world_settlements(id,save_id,day_number,source_revision,input_fingerprint,status,deadline_at,input_snapshot,input_version) select '18900000-0000-4000-8000-000000000061',save_id,1,revision,'scheduler-failure','processing',clock_timestamp(),'{}','fixture-v1' from pg_temp.r;
create or replace function private.world_npc_memory_schedule_closures(p_instance_id uuid default null) returns integer language plpgsql security definer set search_path='' as $f$
begin raise exception 'fixture scheduler failure'; end $f$;
update private.world_settlements set status='completed',completed_at=clock_timestamp() where id='18900000-0000-4000-8000-000000000061';
select is((select status from private.world_settlements where id='18900000-0000-4000-8000-000000000061'),'completed','terminal settlement persists when local scheduling raises');
select is((select status from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.r)),'pending','scheduler failure leaves the durable request retryable');
select is((select count(*) from private.world_npc_memory_summary_sets where instance_id=(select instance_id from pg_temp.r)),0::bigint,'scheduler failure creates no partial summary set');
select is((select count(*) from private.world_npc_memory_outbox where instance_id=(select instance_id from pg_temp.r) and source_kind='memory_set'),0::bigint,'scheduler failure creates no partial memory-set job');
select * from finish(); rollback;
