begin;
create extension if not exists pgtap with schema extensions;
select plan(28);
insert into auth.users(id,email,role,aud) values ('18700000-0000-4000-8000-000000000001','summary-owner@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18700000-0000-4000-8000-000000000001';
select public.create_tavern(); reset role;
create temporary table pg_temp.f as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid instance_id,(snapshot->'roster'->0->>'npcId')::uuid npc_id,(snapshot->'roster'->0->>'versionId')::uuid version_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result)
select '18700000-0000-4000-8000-000000000010',save_id,instance_id,npc_id,version_id,'18700000-0000-4000-8000-000000000001','Summary fixture.',0,revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Source reply."}' from pg_temp.f;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18700000-0000-4000-8000-000000000010';
create temporary table pg_temp.s as select (private.world_npc_memory_register_summary_set('episode_summary','day:1',0,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1}]'::jsonb) ).*;
select is((select count(*) from private.world_npc_memory_summary_sets),1::bigint,'registration creates one immutable set');
select is((select count(*) from private.world_npc_memory_outbox where source_kind='memory_set' and processor_kind='summary'),1::bigint,'registration creates exactly one summary job');
select is((select count(*) from private.world_npc_memory_summary_leaves),1::bigint,'registration derives the authorized leaf hash and ledger coordinate');
select lives_ok($$select private.world_npc_memory_summary_validate((select id from pg_temp.s))$$,'registered set validates');
select is((select id from private.world_npc_memory_register_summary_set('episode_summary','day:1',0,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1}]'::jsonb)),(select id from pg_temp.s),'duplicate registration reuses the set');
select is((select count(*) from private.world_npc_memory_outbox where source_kind='memory_set'),1::bigint,'duplicate registration reuses its job');
select throws_ok($$select private.world_npc_memory_register_summary_set('episode_summary','bad',0,'npc_known','[{"ordinal":0,"sourceKind":"memory_set","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1}]'::jsonb)$$,'PT400',null,'recursive leaves are rejected');
select throws_ok($$select private.world_npc_memory_register_summary_set('episode_summary','gap',0,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":1,"lastLeafOrdinal":1,"leafCount":1}]'::jsonb)$$,'PT400',null,'batch gaps are rejected');
select throws_ok($$select private.world_npc_memory_register_summary_set('episode_summary','overlap',0,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1},{"batchOrdinal":1,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1}]'::jsonb)$$,'PT400',null,'batch overlaps are rejected');
select throws_ok($$select private.world_npc_memory_register_summary_set('episode_summary','negative',0,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":-1,"lastLeafOrdinal":0,"leafCount":2}]'::jsonb)$$,'PT400',null,'negative batch ranges are rejected');
select throws_ok($$select private.world_npc_memory_register_summary_set('episode_summary','overflow',0,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":1,"leafCount":2}]'::jsonb)$$,'PT400',null,'overflow batch ranges are rejected');
select throws_ok($$select private.world_npc_memory_register_summary_set('episode_summary','disclosure',0,'npc_private','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1}]'::jsonb)$$,'PT409',null,'disclosure mismatch is rejected from the ledger');
select throws_ok($$select private.world_npc_memory_register_summary_set('episode_summary','cutoff',-1,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1}]'::jsonb)$$,'PT400',null,'cutoff mismatch is rejected');
select throws_ok($$update private.world_npc_memory_summary_leaves set source_hash=repeat('a',64) where set_id=(select id from pg_temp.s)$$,'PT409',null,'leaves are append-only');
select throws_ok($$update private.world_npc_memory_summary_sets set cutoff_ledger_sequence=1 where id=(select id from pg_temp.s)$$,'PT409',null,'identity fields are append-only');
set local role service_role; set local request.jwt.claim.role='service_role';
create temporary table pg_temp.claim as select public.world_npc_memory_claim('summary','npc-memory-v1') claim;
select ok((select claim is not null from pg_temp.claim),'summary work is claimed through the service seam');
reset role;
update private.world_npc_memory_outbox set source_hash=repeat('a',64) where id=(select (claim->>'id')::uuid from pg_temp.claim);
set local role service_role; set local request.jwt.claim.role='service_role';
select throws_ok($$select public.world_npc_memory_complete((select (claim->>'id')::uuid from pg_temp.claim),(select (claim->>'fence')::uuid from pg_temp.claim),'[]'::jsonb,null)$$,'PT409',null,'tampered summary job hash is rejected');
reset role;
update private.world_npc_memory_outbox set source_hash=(select set_hash from pg_temp.s) where id=(select (claim->>'id')::uuid from pg_temp.claim);
set local role service_role; set local request.jwt.claim.role='service_role';
select throws_ok($$select public.world_npc_memory_complete((select (claim->>'id')::uuid from pg_temp.claim),extensions.gen_random_uuid(),'[]'::jsonb,null)$$,'PT409',null,'stale summary fence is rejected');
reset role;
update private.world_npc_memory_summary_sets set closure_status='invalidated',invalidated_at=clock_timestamp() where id=(select id from pg_temp.s);
set local role service_role; set local request.jwt.claim.role='service_role';
select throws_ok($$select public.world_npc_memory_complete((select (claim->>'id')::uuid from pg_temp.claim),(select (claim->>'fence')::uuid from pg_temp.claim),'[]'::jsonb,null)$$,'PT409',null,'invalidated set cannot be completed');
reset role;
update private.world_npc_memory_outbox set status='invalidated',lease_until=null where id=(select (claim->>'id')::uuid from pg_temp.claim);
create temporary table pg_temp.valid as select (private.world_npc_memory_register_summary_set('episode_summary','day:2',0,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1}]'::jsonb)).*;
set local role service_role; set local request.jwt.claim.role='service_role';
create temporary table pg_temp.valid_claim as select public.world_npc_memory_claim('summary','npc-memory-v1') claim;
reset role;
select set_config('test.valid_summary_artifact',(with source as (select j.*,s.summary_kind,s.disclosure_class,s.set_version,s.set_hash,s.id set_id,e.revision_id from private.world_npc_memory_outbox j join private.world_npc_memory_summary_sets s on s.id=j.source_id join private.prompt_release_entries e on e.release_id=j.prompt_release_id and e.prompt_key='npc_memory.summary' where j.id=(select (claim->>'id')::uuid from pg_temp.valid_claim)), payload as (select source.*,jsonb_build_object('version','npc-memory-summary-v1','mode','extractive-v1','summary','Extractive summary.','citations',jsonb_build_array(jsonb_build_object('leafOrdinal',0)),'protectedRefs','[]'::jsonb,'leaves',(select jsonb_agg(jsonb_build_object('ordinal',l.ordinal,'sourceKind',l.source_kind,'sourceId',l.source_id,'sourceVersion',l.source_version,'sourceHash',l.source_hash,'ledgerSequence',l.ledger_sequence) order by l.ordinal) from private.world_npc_memory_summary_leaves l where l.set_id=source.set_id),'batches',(select jsonb_agg(jsonb_build_object('ordinal',b.batch_ordinal,'firstLeafOrdinal',b.first_leaf_ordinal,'lastLeafOrdinal',b.last_leaf_ordinal,'leafCount',b.leaf_count) order by b.batch_ordinal) from private.world_npc_memory_summary_batches b where b.set_id=source.set_id)) content from source) select jsonb_build_array(jsonb_build_object('artifactKind',summary_kind,'sourceKind','memory_set','sourceIds',jsonb_build_array(set_id),'sourceVersions',jsonb_build_array(set_version),'sourceHash',set_hash,'processorVersion',processor_version,'disclosureClass',disclosure_class,'content',content,'contentHash',encode(extensions.digest(private.world_canonical_json(content),'sha256'),'hex'),'promptReleaseId',prompt_release_id,'promptRevisionId',revision_id,'promptKey','npc_memory.summary','contractId','npc-memory-summary-v1','contractHash','2a28c283d9fada5bc5e8b501356b6fc423305fb7cd6e5b1c1e686b038e45745e','fallback','extractive-v1')) from payload)::text,true);
set local role service_role; set local request.jwt.claim.role='service_role';
select lives_ok($$select public.world_npc_memory_complete((select (claim->>'id')::uuid from pg_temp.valid_claim),(select (claim->>'fence')::uuid from pg_temp.valid_claim),current_setting('test.valid_summary_artifact')::jsonb,null)$$,'valid provider-free summary completion succeeds');
reset role;
select is((select contiguous_sequence from private.world_npc_memory_watermarks where instance_id=(select instance_id from pg_temp.f) and processor_kind='summary' and processor_version='npc-memory-v1'),0::bigint,'summary watermark records its exact cutoff sequence');
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result)
select '18700000-0000-4000-8000-000000000011',save_id,instance_id,npc_id,version_id,'18700000-0000-4000-8000-000000000001','Second summary fixture.',1,revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Second reply."}' from pg_temp.f;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18700000-0000-4000-8000-000000000011';
create temporary table pg_temp.two_leaf as select (private.world_npc_memory_register_summary_set('episode_summary','day:two',1,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1},{"ordinal":1,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000011","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1},{"batchOrdinal":1,"firstLeafOrdinal":1,"lastLeafOrdinal":1,"leafCount":1}]'::jsonb)).*;
select is((select array_agg(ordinal order by ordinal) from private.world_npc_memory_summary_leaves where set_id=(select id from pg_temp.two_leaf)),array[0,1]::integer[],'two authoritative leaves preserve exact ordinal order');
select is((select array_agg(jsonb_build_array(first_leaf_ordinal,last_leaf_ordinal) order by batch_ordinal) from private.world_npc_memory_summary_batches where set_id=(select id from pg_temp.two_leaf)),array['[0,0]'::jsonb,'[1,1]'::jsonb],'two bounded batches cover exactly [0] and [1]');
select is((select set_hash from pg_temp.two_leaf),(select private.world_npc_memory_summary_hash(summary_kind,set_version,closure_key,cutoff_ledger_sequence,disclosure_class,jsonb_agg(jsonb_build_object('ordinal',ordinal,'sourceKind',source_kind,'sourceId',source_id,'sourceVersion',source_version,'sourceHash',source_hash,'ledgerSequence',ledger_sequence) order by ordinal)) from private.world_npc_memory_summary_sets s join private.world_npc_memory_summary_leaves l on l.set_id=s.id where s.id=(select id from pg_temp.two_leaf) group by s.id),'two-leaf canonical hash includes ordered authoritative leaves');
create temporary table pg_temp.leaf_set as select (private.world_npc_memory_register_summary_set('episode_summary','day:leaf',0,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1}]'::jsonb)).*;
set local role service_role; set local request.jwt.claim.role='service_role';
create temporary table pg_temp.leaf_claim as select public.world_npc_memory_claim('summary','npc-memory-v1') claim;
reset role;
update private.world_npc_memory_sources set source_hash=repeat('b',64) where source_kind='dialogue_turn' and source_id='18700000-0000-4000-8000-000000000010';
set local role service_role; set local request.jwt.claim.role='service_role';
select throws_ok($$select public.world_npc_memory_complete((select (claim->>'id')::uuid from pg_temp.leaf_claim),(select (claim->>'fence')::uuid from pg_temp.leaf_claim),'[]'::jsonb,null)$$,'PT409',null,'changed ledger leaf hash rejects summary completion');
reset role;
update private.world_npc_memory_sources set source_hash=private.world_npc_memory_source_hash('dialogue_turn','18700000-0000-4000-8000-000000000010') where source_kind='dialogue_turn' and source_id='18700000-0000-4000-8000-000000000010';
update private.world_npc_memory_outbox set status='invalidated',lease_until=null where id=(select (claim->>'id')::uuid from pg_temp.leaf_claim);
create temporary table pg_temp.purge_set as select (private.world_npc_memory_register_summary_set('episode_summary','day:3',0,'npc_known','[{"ordinal":0,"sourceKind":"dialogue_turn","sourceId":"18700000-0000-4000-8000-000000000010","sourceVersion":1}]'::jsonb,'[{"batchOrdinal":0,"firstLeafOrdinal":0,"lastLeafOrdinal":0,"leafCount":1}]'::jsonb)).*;
set local role service_role; set local request.jwt.claim.role='service_role';
create temporary table pg_temp.purge_claim as select public.world_npc_memory_claim('summary','npc-memory-v1') claim;
reset role;
delete from private.world_npc_instances where id=(select instance_id from pg_temp.f);
select is((select count(*) from private.world_npc_memory_summary_sets where id=(select id from pg_temp.purge_set)),0::bigint,'resident purge cascades summary sets');
select ok(exists(select 1 from private.world_npc_memory_invalidations i where i.job_id=(select (claim->>'id')::uuid from pg_temp.purge_claim) and i.fence=(select (claim->>'fence')::uuid from pg_temp.purge_claim)),'resident purge records the active summary fence');
set local role service_role; set local request.jwt.claim.role='service_role';
select throws_ok($$select public.world_npc_memory_complete((select (claim->>'id')::uuid from pg_temp.purge_claim),(select (claim->>'fence')::uuid from pg_temp.purge_claim),'[]'::jsonb,null)$$,'PT409',null,'late summary completion after purge is stale');
reset role;
select * from finish();
rollback;
