begin;
create extension if not exists pgtap with schema extensions;
select plan(43);
insert into auth.users(id,email,role,aud) values ('18800000-0000-4000-8000-000000000001','closure-owner@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18800000-0000-4000-8000-000000000001'; select public.create_tavern(); reset role;
create temporary table pg_temp.f as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid instance_id,(snapshot->'roster'->0->>'npcId')::uuid npc_id,(snapshot->'roster'->0->>'versionId')::uuid version_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result) select '18800000-0000-4000-8000-000000000010',save_id,instance_id,npc_id,version_id,'18800000-0000-4000-8000-000000000001','Hello.',0,revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Welcome."}' from pg_temp.f;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18800000-0000-4000-8000-000000000010';
update public.tavern_saves set current_day=2 where id=(select save_id from pg_temp.f);
select throws_ok($$select private.world_npc_memory_request_episode((select instance_id from pg_temp.f),2,0)$$,'PT409',null,'current episode day is not closed');
select throws_ok($$select private.world_npc_memory_request_episode((select instance_id from pg_temp.f),3,0)$$,'PT409',null,'future episode day is not requestable');
select throws_ok($$select private.world_npc_memory_request_episode((select instance_id from pg_temp.f),1,999)$$,'PT409',null,'divergent episode cutoff is rejected');
select is((private.world_npc_memory_request_episode((select instance_id from pg_temp.f),1,0)).reason,'no_summary','greeting-only episode records no-summary closure');
select is((select count(*) from private.world_npc_memory_summary_sets where instance_id=(select instance_id from pg_temp.f)),0::bigint,'greeting-only episode creates no set');
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id) select id,instance_id,'interaction','Meaningful event','Meaningful event','npc',2,'{}',save_id,extensions.gen_random_uuid(),1,'dialogue_turn',id,1,private.world_npc_memory_source_hash('dialogue_turn',id),1,0,1,0,'attributed','npc_known',instance_id from private.world_npc_dialogue_turns where id='18800000-0000-4000-8000-000000000010';
select is((private.world_npc_memory_request_episode((select instance_id from pg_temp.f),1,0)).status,'registered','existing no-summary request remains immutable');
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.f) and summary_kind='episode_summary' and closed_day=1),1::bigint,'duplicate episode delivery has one request');
update private.world_npc_memory_outbox set status='completed',completed_at=clock_timestamp(),lease_until=null where source_id='18800000-0000-4000-8000-000000000010';
select private.world_npc_memory_refresh_watermark((select instance_id from pg_temp.f),'extract','npc-memory-v1');
select is(private.world_npc_memory_schedule_closures((select instance_id from pg_temp.f)),0,'no-summary request does not schedule a provider job');
select throws_ok($$select private.world_npc_memory_request_quest('18800000-0000-4000-8000-000000000010')$$,'PT409',null,'non-quest terminal request is rejected');
insert into private.world_quest_events(id,quest_id,save_id,instance_id,day_number,step_index,action,approach,skill,difficulty,preparation_before,preparation_after,hospitality,readiness,chance,draw,outcome,narration,public_news)
select '18800000-0000-4000-8000-000000000020',q.id,f.save_id,f.instance_id,3,0,'prepare','scouting',1,q.difficulty,0,1,0,0,null,null,'prepared','Still preparing.',false from pg_temp.f f join lateral (select * from private.world_quests where instance_id=f.instance_id limit 1) q on true;
select throws_ok($$select private.world_npc_memory_request_quest('18800000-0000-4000-8000-000000000020')$$,'PT409',null,'prepared quest cannot request closure');
insert into private.world_quest_events(id,quest_id,save_id,instance_id,day_number,step_index,action,approach,skill,difficulty,preparation_before,preparation_after,hospitality,readiness,chance,draw,outcome,narration,public_news)
select '18800000-0000-4000-8000-000000000021',q.id,f.save_id,f.instance_id,4,1,'attempt','scouting',1,q.difficulty,1,1,0,0,50,99,'failed','The quest failed.',false from pg_temp.f f join lateral (select * from private.world_quests where instance_id=f.instance_id limit 1) q on true;
select is((private.world_npc_memory_request_quest('18800000-0000-4000-8000-000000000021')).status,'pending','failed terminal quest registers a closure request');
select is((select count(*) from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.f) and summary_kind='quest_summary' and terminal_event_id='18800000-0000-4000-8000-000000000021'),1::bigint,'failed terminal request is idempotent');
-- Fresh second save: sequence zero remains a real extract gap while sequence
-- one is already examined; completing zero through the public service seam
-- unblocks exactly one closure registration.
insert into auth.users(id,email,role,aud) values ('18800000-0000-4000-8000-000000000002','closure-second@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18800000-0000-4000-8000-000000000002'; select public.create_tavern(); reset role;
create temporary table pg_temp.f2 as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid instance_id,(snapshot->'roster'->0->>'npcId')::uuid npc_id,(snapshot->'roster'->0->>'versionId')::uuid version_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result) select '18800000-0000-0000-0000-000000000010',save_id,instance_id,npc_id,version_id,'18800000-0000-4000-8000-000000000002','Gap source.',0,revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Gap reply."}' from pg_temp.f2;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18800000-0000-0000-0000-000000000010';
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result) select '18800000-0000-0000-0000-000000000011',save_id,instance_id,npc_id,version_id,'18800000-0000-4000-8000-000000000002','Later source.',1,revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Later reply."}' from pg_temp.f2;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18800000-0000-0000-0000-000000000011';
update public.tavern_saves set current_day=2 where id=(select save_id from pg_temp.f2);
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id) select '18800000-0000-0000-0000-000000000010',instance_id,'interaction','Meaningful gap','Gap reply.','npc',2,'{}',save_id,extensions.gen_random_uuid(),1,'dialogue_turn','18800000-0000-0000-0000-000000000010',1,private.world_npc_memory_source_hash('dialogue_turn','18800000-0000-0000-0000-000000000010'),1,0,1,0,'attributed','npc_known',instance_id from pg_temp.f2;
select is((private.world_npc_memory_request_episode((select instance_id from pg_temp.f2),1,1)).status,'pending','second instance request is initially pending before gap simulation');
update private.world_npc_memory_closure_requests set status='pending',reason='pending' where instance_id=(select instance_id from pg_temp.f2);
update private.world_npc_memory_outbox set status='pending',lease_until=null where instance_id=(select instance_id from pg_temp.f2) and source_id='18800000-0000-0000-0000-000000000010';
update private.world_npc_memory_outbox set status='completed',lease_until=null,completed_at=clock_timestamp() where instance_id=(select instance_id from pg_temp.f2) and source_id='18800000-0000-0000-0000-000000000011';
select is(private.world_npc_memory_schedule_closures((select instance_id from pg_temp.f2)),0,'extract gap blocks second-instance closure scheduling');
select is((select status from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.f2)),'blocked_gap','pending gap is recorded conservatively');
update private.world_npc_memory_outbox set status='completed',lease_until=null,completed_at=clock_timestamp() where instance_id<>(select instance_id from pg_temp.f2) and status='pending';
set local role service_role; set local request.jwt.claim.role='service_role';
create temporary table pg_temp.gap_claim as select public.world_npc_memory_claim('extract','npc-memory-v1') claim;
select is((select claim->>'sourceId' from pg_temp.gap_claim),'18800000-0000-0000-0000-000000000010','gap claim belongs to the second-instance fixture source');
select lives_ok($$select public.world_npc_memory_complete((select (claim->>'id')::uuid from pg_temp.gap_claim),(select (claim->>'fence')::uuid from pg_temp.gap_claim),'[]'::jsonb,null)$$,'service completion of gap source succeeds');
reset role;
select is((private.world_npc_memory_schedule_closures((select instance_id from pg_temp.f2))),0,'completion wrapper schedules the closure before explicit retry');
select is((select status from private.world_npc_memory_closure_requests where instance_id=(select instance_id from pg_temp.f2)),'registered','gap completion registers the closure exactly once');
select is((select count(*) from private.world_npc_memory_summary_sets where instance_id=(select instance_id from pg_temp.f2)),1::bigint,'gap retry creates exactly one summary set');
-- Public completion is service-only; the same valid processing job succeeds
-- through the service role seam.
update private.world_npc_memory_outbox set status='processing',fence='18800000-0000-4000-8000-000000000022',lease_until=clock_timestamp()+interval '5 minutes'
where instance_id=(select instance_id from pg_temp.f2) and source_id='18800000-0000-0000-0000-000000000011';
create temporary table pg_temp.auth_job as select id from private.world_npc_memory_outbox where instance_id=(select instance_id from pg_temp.f2) and source_id='18800000-0000-0000-0000-000000000011';
grant select on pg_temp.auth_job to authenticated,service_role;
set local role authenticated; set local request.jwt.claim.role='authenticated';
select throws_ok($$select public.world_npc_memory_complete((select id from pg_temp.auth_job),'18800000-0000-4000-8000-000000000022','[]'::jsonb,null)$$,'42501',null,'authenticated completion is denied before the service-only seam');
reset role;
set local role service_role; set local request.jwt.claim.role='service_role';
select lives_ok($$select public.world_npc_memory_complete((select id from pg_temp.auth_job),'18800000-0000-4000-8000-000000000022','[]'::jsonb,null)$$,'service completion succeeds for the valid job');
reset role;
create temporary table pg_temp.stale_counts as select (select count(*) from private.world_npc_memory_closure_requests) requests,(select count(*) from private.world_npc_memory_summary_sets) sets,(select count(*) from private.world_npc_memory_outbox where source_kind='memory_set') jobs;
set local role service_role; set local request.jwt.claim.role='service_role';
select throws_ok($$select public.world_npc_memory_complete('18800000-0000-4000-8000-000000000099','18800000-0000-4000-8000-000000000022','[]'::jsonb,null)$$,'PT409',null,'stale delegated completion is rejected before scheduling');
reset role;
select is((select jsonb_build_array((select count(*) from private.world_npc_memory_closure_requests),(select count(*) from private.world_npc_memory_summary_sets),(select count(*) from private.world_npc_memory_outbox where source_kind='memory_set'))), (select jsonb_build_array(requests,sets,jobs) from pg_temp.stale_counts),'failed completion leaves closure requests, sets, and jobs unchanged');
-- One closed day with three authoritative disclosure classes.  The dialogue
-- is NPC-known, public quest receipt player-visible, and settlement evolution
-- NPC-private; scheduler partitions them before calling the 087 set seam.
insert into auth.users(id,email,role,aud) values ('18800000-0000-4000-8000-000000000003','closure-disclosure@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18800000-0000-4000-8000-000000000003'; select public.create_tavern(); reset role;
create temporary table pg_temp.f3 as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid instance_id,(snapshot->'roster'->0->>'npcId')::uuid npc_id,(snapshot->'roster'->0->>'versionId')::uuid version_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result) select '18800000-0000-4000-8000-000000000030',save_id,instance_id,npc_id,version_id,'18800000-0000-4000-8000-000000000003','Important disclosure.',0,revision,1,'processing',clock_timestamp()+interval '5 minutes','{"reply":"Remember this."}' from pg_temp.f3;
update private.world_npc_dialogue_turns set status='completed',completed_at=clock_timestamp() where id='18800000-0000-4000-8000-000000000030';
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id) select id,instance_id,'interaction','Important disclosure','Remember this.','npc',2,'{}',save_id,extensions.gen_random_uuid(),1,'dialogue_turn',id,1,private.world_npc_memory_source_hash('dialogue_turn',id),1,0,1,0,'attributed','npc_known',instance_id from private.world_npc_dialogue_turns where id='18800000-0000-4000-8000-000000000030';
insert into private.world_quest_events(id,quest_id,save_id,instance_id,day_number,step_index,action,approach,skill,difficulty,preparation_before,preparation_after,hospitality,readiness,chance,draw,outcome,narration,public_news) select '18800000-0000-4000-8000-000000000031',q.id,f.save_id,f.instance_id,1,0,'prepare','scouting',1,q.difficulty,0,1,0,0,null,null,'prepared','Public quest receipt.',true from pg_temp.f3 f join lateral(select * from private.world_quests where instance_id=f.instance_id limit 1) q on true;
insert into private.world_settlements(id,save_id,day_number,source_revision,input_fingerprint,status,deadline_at,input_snapshot,input_version) select '18800000-0000-4000-8000-000000000032',save_id,1,revision,'closure-disclosure-settlement','completed',clock_timestamp(),'{}','fixture-v1' from pg_temp.f3;
insert into private.world_settlement_jobs(id,settlement_id,ordinal,job_kind,subject_instance_id,status,input_fingerprint,input_snapshot,input_version) select '18800000-0000-4000-8000-000000000033','18800000-0000-4000-8000-000000000032',1,'resident',instance_id,'completed','closure-disclosure-job','{}','fixture-v1' from pg_temp.f3;
insert into private.resident_evolution_entries(job_id,instance_id,save_id,day_number,profile_revision,disposition) select '18800000-0000-4000-8000-000000000033',instance_id,save_id,1,1,'{"summary":"Private evolution."}' from pg_temp.f3;
update public.tavern_saves set current_day=2 where id=(select save_id from pg_temp.f3);
update private.world_npc_memory_outbox set status='completed',completed_at=clock_timestamp(),lease_until=null where instance_id=(select instance_id from pg_temp.f3);
select private.world_npc_memory_refresh_watermark((select instance_id from pg_temp.f3),'extract','npc-memory-v1');
select is((private.world_npc_memory_request_episode((select instance_id from pg_temp.f3),1,2)).status,'pending','meaningful disclosure day queues one closure request');
select is(private.world_npc_memory_schedule_closures((select instance_id from pg_temp.f3)),1,'closed disclosure day schedules its closure');
select is((select count(*) from private.world_npc_memory_summary_sets where instance_id=(select instance_id from pg_temp.f3)),3::bigint,'one set is created for each disclosure class');
select is((select array_agg(disclosure_class order by disclosure_class) from private.world_npc_memory_summary_sets where instance_id=(select instance_id from pg_temp.f3)),array['npc_known','npc_private','player_visible']::text[],'disclosure sets are exactly class partitioned');
select ok(not exists(select 1 from private.world_npc_memory_summary_sets s join private.world_npc_memory_summary_leaves l on l.set_id=s.id join private.world_npc_memory_sources x on x.source_kind=l.source_kind and x.source_id=l.source_id and x.source_version=l.source_version where s.instance_id=(select instance_id from pg_temp.f3) and s.disclosure_class<>x.disclosure_class),'no summary set mixes or omits its authoritative disclosure class');
-- Historical/backfill seam: 65 completed, meaningful dialogue sources must
-- retain every ordered leaf rather than silently clipping at a batch boundary.
insert into auth.users(id,email,role,aud) values ('18800000-0000-4000-8000-000000000004','closure-65@example.test','authenticated','authenticated');
set local role authenticated; set local request.jwt.claim.role='authenticated'; set local request.jwt.claim.sub='18800000-0000-4000-8000-000000000004'; select public.create_tavern(); reset role;
create temporary table pg_temp.f4 as select (snapshot#>>'{save,id}')::uuid save_id,(snapshot->'roster'->0->>'instanceId')::uuid instance_id,(snapshot->'roster'->0->>'npcId')::uuid npc_id,(snapshot->'roster'->0->>'versionId')::uuid version_id,(snapshot#>>'{save,revision}')::bigint revision from (select public.npc_bar_snapshot() snapshot) x;
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at)
select ('18800000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid,f.save_id,f.instance_id,f.npc_id,f.version_id,'18800000-0000-4000-8000-000000000004','Backfill source '||g,g,f.revision,1,'completed',clock_timestamp()+interval '5 minutes',jsonb_build_object('reply','Backfill reply '||g),clock_timestamp() from pg_temp.f4 f cross join generate_series(0,64) g;
select private.world_npc_memory_project_source('dialogue_turn',('18800000-0000-4001-8000-'||lpad(g::text,12,'0'))::uuid) from generate_series(0,64) g;
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id)
select t.id,t.instance_id,'interaction','Meaningful backfill '||t.input_sequence,'Backfill reply','npc',2,'{}',t.save_id,extensions.gen_random_uuid(),1,'dialogue_turn',t.id,1,private.world_npc_memory_source_hash('dialogue_turn',t.id),1,t.input_sequence,1,t.input_sequence,'attributed','npc_known',t.instance_id from private.world_npc_dialogue_turns t where t.instance_id=(select instance_id from pg_temp.f4);
update public.tavern_saves set current_day=2 where id=(select save_id from pg_temp.f4);
update private.world_npc_memory_outbox set status='completed',completed_at=clock_timestamp(),lease_until=null where instance_id=(select instance_id from pg_temp.f4);
select private.world_npc_memory_refresh_watermark((select instance_id from pg_temp.f4),'extract','npc-memory-v1');
select is((private.world_npc_memory_request_episode((select instance_id from pg_temp.f4),1,64)).status,'pending','65-source historical closure request is pending');
select is(private.world_npc_memory_schedule_closures((select instance_id from pg_temp.f4)),1,'65-source closure schedules once');
select is((select count(*) from private.world_npc_memory_summary_leaves l join private.world_npc_memory_summary_sets s on s.id=l.set_id where s.instance_id=(select instance_id from pg_temp.f4)),65::bigint,'65-source set has no clipped leaves');
select is((select array_agg(jsonb_build_array(first_leaf_ordinal,last_leaf_ordinal) order by batch_ordinal) from private.world_npc_memory_summary_batches b join private.world_npc_memory_summary_sets s on s.id=b.set_id where s.instance_id=(select instance_id from pg_temp.f4)),array['[0,63]'::jsonb,'[64,64]'::jsonb],'65-source set has complete bounded batches');
select ok((select array_agg(ordinal order by ordinal)=array(select generate_series(0,64)) from private.world_npc_memory_summary_leaves l join private.world_npc_memory_summary_sets s on s.id=l.set_id where s.instance_id=(select instance_id from pg_temp.f4)),'65-source leaf order is stable');
select is(private.world_npc_memory_schedule_closures((select instance_id from pg_temp.f4)),0,'duplicate schedule leaves one set and job unchanged');
-- Clone a valid in-scope quest as a generated successor: both terminal
-- receipts share the resident/save, so selection must use quest identity.
insert into private.world_quest_events(id,quest_id,save_id,instance_id,day_number,step_index,action,approach,skill,difficulty,preparation_before,preparation_after,hospitality,readiness,chance,draw,outcome,narration,public_news)
select '18800000-0000-4002-8000-000000000009',q.id,q.save_id,q.instance_id,2,0,'attempt','scouting',1,q.difficulty,0,0,0,0,50,99,'failed','Parent terminal prerequisite.',false from private.world_quests q where q.instance_id=(select instance_id from pg_temp.f3) and q.origin='authored_milestone' limit 1;
update private.world_quests set state='failed',terminal_day=2,terminal_event_id='18800000-0000-4002-8000-000000000009' where instance_id=(select instance_id from pg_temp.f3) and origin='authored_milestone';
insert into private.world_quests(id,save_id,instance_id,package_id,package_hash,version_id,origin,authored_milestone_index,authored_milestone_key,parent_quest_id,title,objective,motivation,constraints,target_refs,difficulty,definition_plan,current_plan,plan_revision,state,current_step,preparation,scheduled_for_day,activated_day,terminal_day)
select '18800000-0000-4002-8000-000000000001',save_id,instance_id,package_id,package_hash,version_id,'generated_successor',null,null,id,title||' successor',objective,motivation,constraints,target_refs,difficulty,definition_plan,current_plan,plan_revision,'failed',0,preparation,scheduled_for_day,1,1 from private.world_quests where instance_id=(select instance_id from pg_temp.f3) limit 1;
insert into private.world_quest_events(id,quest_id,save_id,instance_id,day_number,step_index,action,approach,skill,difficulty,preparation_before,preparation_after,hospitality,readiness,chance,draw,outcome,narration,public_news)
select '18800000-0000-4002-8000-000000000010',q.id,q.save_id,q.instance_id,3,0,'attempt','scouting',1,q.difficulty,0,0,0,0,50,99,'failed','Quest A terminal.',false from private.world_quests q where q.instance_id=(select instance_id from pg_temp.f3) and q.origin='authored_milestone' limit 1;
insert into private.world_quest_events(id,quest_id,save_id,instance_id,day_number,step_index,action,approach,skill,difficulty,preparation_before,preparation_after,hospitality,readiness,chance,draw,outcome,narration,public_news)
select '18800000-0000-4002-8000-000000000011',q.id,q.save_id,q.instance_id,1,0,'attempt','scouting',1,q.difficulty,0,0,0,0,50,99,'failed','Quest B terminal.',false from private.world_quests q where q.id='18800000-0000-4002-8000-000000000001';
-- The first dialogue source predates A's terminal receipt; attach an
-- immutable correction/commitment record to it.  A second dialogue source
-- is registered only after the terminal receipt and must miss A's cutoff.
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,commitment_status,observer_instance_id,related_quest_id)
select '18800000-0000-4000-8000-000000000030',f.instance_id,'promise','Pre-terminal A commitment','Remember this.','npc',3,'{}',f.save_id,extensions.gen_random_uuid(),1,'dialogue_turn','18800000-0000-4000-8000-000000000030',1,private.world_npc_memory_source_hash('dialogue_turn','18800000-0000-4000-8000-000000000030'),1,0,1,0,'attributed','npc_known','unresolved',f.instance_id,q.id from pg_temp.f3 f join private.world_quests q on q.instance_id=f.instance_id and q.origin='authored_milestone';
insert into private.world_npc_dialogue_turns(id,save_id,instance_id,npc_id,version_id,actor_id,message,input_sequence,source_revision,day_number,status,lease_until,result,completed_at) select '18800000-0000-4002-8000-000000000012',save_id,instance_id,npc_id,version_id,'18800000-0000-4000-8000-000000000003','Post-cutoff A source.',1,revision,1,'completed',clock_timestamp()+interval '5 minutes','{"reply":"Too late."}',clock_timestamp() from pg_temp.f3;
select private.world_npc_memory_project_source('dialogue_turn','18800000-0000-4002-8000-000000000012');
insert into private.world_npc_memories(turn_id,instance_id,kind,text,quote,speaker,importance,entity_refs,save_id,record_root_id,record_version,source_kind,source_id,source_version,source_hash,occurred_day,occurred_sequence,learned_day,learned_sequence,truth_class,disclosure_class,observer_instance_id,related_quest_id)
select '18800000-0000-4002-8000-000000000012',f.instance_id,'interaction','Post-cutoff A link','Too late.','npc',3,'{}',f.save_id,extensions.gen_random_uuid(),1,'dialogue_turn','18800000-0000-4002-8000-000000000012',1,private.world_npc_memory_source_hash('dialogue_turn','18800000-0000-4002-8000-000000000012'),1,1,1,1,'attributed','npc_known',f.instance_id,q.id from pg_temp.f3 f join private.world_quests q on q.instance_id=f.instance_id and q.origin='authored_milestone';
update private.world_npc_memory_outbox set status='completed',completed_at=clock_timestamp(),lease_until=null where instance_id=(select instance_id from pg_temp.f3) and source_kind='quest_event';
select private.world_npc_memory_refresh_watermark((select instance_id from pg_temp.f3),'extract','npc-memory-v1');
select is((private.world_npc_memory_request_quest('18800000-0000-4002-8000-000000000010')).status,'pending','terminal quest A requests its own closure');
select is(private.world_npc_memory_schedule_closures((select instance_id from pg_temp.f3)),3,'all same-instance terminal quest closures schedule once');
select ok(exists(select 1 from private.world_npc_memory_summary_sets s join private.world_npc_memory_summary_leaves l on l.set_id=s.id where s.instance_id=(select instance_id from pg_temp.f3) and s.summary_kind='quest_summary' and s.closure_key like '%18800000-0000-4002-8000-000000000010:%' and l.source_kind='quest_event' and l.source_id='18800000-0000-4002-8000-000000000010'),'quest A terminal evidence is included');
select ok(not exists(select 1 from private.world_npc_memory_summary_sets s join private.world_npc_memory_summary_leaves l on l.set_id=s.id where s.instance_id=(select instance_id from pg_temp.f3) and s.summary_kind='quest_summary' and s.closure_key like '%18800000-0000-4002-8000-000000000010:%' and l.source_kind='quest_event' and l.source_id='18800000-0000-4002-8000-000000000011'),'quest A set excludes same-instance quest B evidence');
select ok(exists(select 1 from private.world_npc_memory_summary_sets s join private.world_npc_memory_summary_leaves l on l.set_id=s.id where s.instance_id=(select instance_id from pg_temp.f3) and s.summary_kind='quest_summary' and s.closure_key like '%18800000-0000-4002-8000-000000000010:%' and l.source_id='18800000-0000-4000-8000-000000000030'),'A-linked pre-cutoff commitment source is included');
select ok(not exists(select 1 from private.world_npc_memory_summary_sets s join private.world_npc_memory_summary_leaves l on l.set_id=s.id where s.instance_id=(select instance_id from pg_temp.f3) and s.summary_kind='quest_summary' and s.closure_key like '%18800000-0000-4002-8000-000000000010:%' and l.source_id='18800000-0000-4002-8000-000000000012'),'post-cutoff A-linked source is excluded');
select is((select commitment_status from private.world_npc_memories where text='Pre-terminal A commitment'),'unresolved','closure scheduling does not mutate commitment/correction gameplay state');
select throws_ok($$delete from private.world_npc_memory_closure_requests$$,'PT409',null,'closure requests are append-only');
select * from finish(); rollback;
