<script lang="ts">
  import type { PageProps } from './$types';
  import NpcSheetEditor from '$lib/components/community/NpcSheetEditor.svelte';
  let { data, form }: PageProps = $props();
  let detail: any = $derived(data.detail as any);
  let sandboxJobs: any[] = $derived((detail.jobs as any[]).filter((job: any) => job.kind === 'sandbox'));
</script>
<main class="page-shell community-page"><a href="/authoring/npcs">← Creator studio</a><header><p class="eyebrow">Draft workspace</p><h1>{detail.sheet.identity.name}</h1><p>Revision {detail.revision} · {detail.state}</p></header>
<NpcSheetEditor sheet={detail.sheet} revision={detail.revision} editable={detail.state === 'open'} message={form?.message} conflict={form?.conflict} />
<section class="community-grid two"><article class="community-card"><h2>Assistance</h2><p>Requests are narrowly scoped to one section. A queued job never changes your draft.</p><form method="POST" action="?/assist"><input type="hidden" name="revision" value={detail.revision} /><label>Section <select name="section"><option>identity</option><option>appearance</option><option>personality</option><option>lore</option><option>skills</option><option>campaign</option></select></label><label>Instruction <textarea name="instruction" minlength="1" maxlength="2000" required></textarea></label><button>Request assistance</button></form>{#each detail.assistance as event}<div class="community-row"><small>{event.sectionPath} · {event.disposition}</small>{#if event.proposal}<details><summary>View proposed replacement</summary><pre>{JSON.stringify(event.proposal, null, 2)}</pre></details>{#if event.disposition === 'proposed'}<form method="POST" action="?/disposition"><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="revision" value={detail.revision}/><button name="accept" value="true">Apply proposal</button><button name="accept" value="false">Discard proposal</button></form>{/if}{/if}</div>{/each}</article>
<article class="community-card"><h2>Scene candidates</h2><p>Local workers read ignored source assets and add storage keys. This page never manufactures art.</p><form method="POST" action="?/scene"><input type="hidden" name="revision" value={detail.revision}/><label>Scene prompt <textarea name="prompt" minlength="10" maxlength="2000" required></textarea></label><label>Alternative <input name="alternative" type="number" min="1" max="4" value="1" /></label><button>Queue scene</button></form>{#each detail.assets as asset}<form method="POST" action="?/selectScene" class="community-row"><input type="hidden" name="revision" value={detail.revision}/><input type="hidden" name="assetId" value={asset.id}/><strong>{asset.storageKey}</strong><p>{asset.altText}</p>{#if asset.previewUrl}<img class="community-scene-preview" src={asset.previewUrl} alt={asset.altText} />{:else}<p role="status">Preview unavailable: run <code>npm run fixtures:users:local</code> after placing an approved derivative in the ignored local media folder.</p>{/if}<button disabled={detail.selectedSceneAssetId === asset.id}>{detail.selectedSceneAssetId === asset.id ? 'Selected' : 'Select scene'}</button></form>{/each}<h3>Generation jobs</h3>{#each detail.jobs as job}<p class="community-row"><strong>{job.kind}</strong><span>{job.status}{job.errorCode ? ` · ${job.errorCode}` : ''}</span><small>{job.completedAt ? `Completed ${job.completedAt}` : 'Awaiting the local worker'}</small></p>{/each}</article></section>
<section class="community-grid two"><article class="community-card"><h2>Sandbox</h2><p>Sandbox conversations are isolated and are invalidated after a draft change.</p><form method="POST" action="?/sandbox"><input type="hidden" name="revision" value={detail.revision}/><textarea name="message" minlength="1" maxlength="2000" required placeholder="Try a keeper message…"></textarea><button>Queue sandbox turn</button></form>{#each sandboxJobs as job}<p class="community-row"><strong>Sandbox {job.status}</strong><span>{job.result?.reply ?? (job.errorCode ? job.errorCode : 'Awaiting the local worker')}</span></p>{/each}</article><article class="community-card"><h2>Review and history</h2><form method="POST" action="?/submit"><input type="hidden" name="revision" value={detail.revision}/><p>Submitting creates an immutable version for reviewer and evaluation checks.</p><button class="primary-action">Submit immutable version</button></form><pre>{JSON.stringify(detail.versions, null, 2)}</pre>{#each detail.comments as comment}<form method="POST" action="?/resolveComment" class="community-row"><p>{comment.sectionPath}: {comment.body}</p><input type="hidden" name="commentId" value={comment.id}/>{#if !comment.resolvedAt}<button>Resolve comment</button>{/if}</form>{/each}<form method="POST" action="?/retire"><label>Retirement rationale <textarea name="reason" minlength="3" required></textarea></label><button>Request retirement</button></form></article></section></main>
