<script lang="ts">
  import { onMount } from 'svelte';
  import { AUTHORING_EXPRESSION_SLOTS, type AuthoringExpressionSlot, type AuthoringPortraitCandidate, type AuthoringPortraitWorkspace } from '$lib/game/authoring-workspace';
  const labels: Record<AuthoringExpressionSlot, string> = { neutral: 'Neutral', happy: 'Happy', sad: 'Sad', angry: 'Angry', engaged: 'Engaged', leaving: 'Leaving' };
  type VisualSummary = Array<{ label: string; values: string[] }>;
  type Alternative = { ordinal: number; stage: string; status: string; candidateId: string | null; errorCode: string | null };
  type Snapshot = { jobId: string; slot: AuthoringExpressionSlot; status: string; pollAfterMs: number; alternatives: Alternative[]; candidates: Array<{ candidateId: string; slot: AuthoringExpressionSlot; source: 'author_upload' | 'ai_generated'; state: string; previewUrl: string | null; altText: string; width: number | null; height: number | null; hasAlpha: boolean | null; mimeType: string | null; staleNeutralAnchor: boolean }> };
  let { revision, editable, portrait, visualSummary, itemOptions = [], npcId = '' }: { revision: number; editable: boolean; portrait: AuthoringPortraitWorkspace; visualSummary: VisualSummary; itemOptions?: string[]; npcId?: string } = $props();
  let activeSlot = $state<AuthoringExpressionSlot>('neutral'); let chosenBySlot = $state<Partial<Record<AuthoringExpressionSlot, string>>>({}); let requestedCount = $state('2'); let message = $state(''); let confirmStale = $state(false); let confirmNeutral = $state(false); let discardId = $state<string | null>(null); let candidates = $state<AuthoringPortraitCandidate[]>([]); let jobs = $state<Record<string, { slot: AuthoringExpressionSlot; status: string; alternatives: Alternative[] }>>({}); let selections = $state<Partial<Record<AuthoringExpressionSlot, string>>>({}); let panel: HTMLElement; let stream: EventSource | undefined; let timer: ReturnType<typeof setTimeout> | undefined; let watchedJobId: string | null = null; let previousRevision = $state(-1);
  const neutralSelected = $derived(Boolean(selections.neutral || portrait.selectedCandidateId));
  const optionalLocked = $derived(activeSlot !== 'neutral' && !neutralSelected);
  const slotCandidates = $derived(candidates.filter((candidate) => candidate.slot === activeSlot));
  const selectedSlotCandidate = $derived(selections[activeSlot] ?? (activeSlot === 'neutral' ? portrait.selectedCandidateId : null));
  const chosen = $derived(chosenBySlot[activeSlot] ?? null);
  const chosenCandidate = $derived(candidates.find((candidate) => candidate.id === chosen) ?? null);
  const activeAlternatives = $derived(Object.values(jobs).filter((job) => job.slot === activeSlot && !terminal(job.status)).flatMap((job) => job.alternatives));
  $effect(() => { if (!candidates.length && portrait.candidates.length) candidates = [...portrait.candidates]; if (!Object.keys(selections).length && Object.keys(portrait.selectedCandidateIds).length) selections = { ...portrait.selectedCandidateIds }; if (revision !== previousRevision) { previousRevision = revision; candidates = [...portrait.candidates]; selections = { ...portrait.selectedCandidateIds }; chosenBySlot = {}; discardId = null; confirmStale = false; confirmNeutral = false; } });
  function terminal(status: string) { return ['completed', 'failed', 'cancelled', 'expired'].includes(status); }
  function selectable(candidate: AuthoringPortraitCandidate) { return ['ready', 'selected', 'stale'].includes(candidate.state); }
  function candidateLabel(candidate: AuthoringPortraitCandidate) { if (candidate.id === selectedSlotCandidate) return 'selected'; if (candidate.staleNeutralAnchor || candidate.state === 'stale') return 'stale Neutral anchor'; return candidate.state; }
  function switchSlot(slot: AuthoringExpressionSlot) { activeSlot = slot; confirmStale = false; confirmNeutral = false; discardId = null; }
  function merge(snapshot: Snapshot) { jobs = { ...jobs, [snapshot.jobId]: { slot: snapshot.slot, status: snapshot.status, alternatives: snapshot.alternatives } }; const errors = new Map(snapshot.alternatives.filter((alternative) => alternative.candidateId && alternative.errorCode).map((alternative) => [alternative.candidateId!, alternative.errorCode!])); const existing = new Map(candidates.map((entry) => [entry.id, entry])); for (const incoming of snapshot.candidates) { const prior = existing.get(incoming.candidateId); existing.set(incoming.candidateId, { id: incoming.candidateId, assetId: prior?.assetId ?? incoming.candidateId, ordinal: prior?.ordinal ?? 0, state: incoming.state === 'failed' ? 'failed' : incoming.state === 'ready' ? 'ready' : 'generating', previewUrl: incoming.previewUrl ?? prior?.previewUrl ?? null, altText: incoming.altText, width: incoming.width, height: incoming.height, hasAlpha: incoming.hasAlpha, mimeType: incoming.mimeType, failureReason: errors.get(incoming.candidateId) ?? prior?.failureReason ?? null, styleVersion: prior?.styleVersion ?? null, visualInputHash: prior?.visualInputHash ?? null, createdAt: prior?.createdAt ?? null, slot: incoming.slot, source: incoming.source, staleNeutralAnchor: incoming.staleNeutralAnchor, neutralAnchorHash: prior?.neutralAnchorHash ?? null }); } candidates = [...existing.values()]; }
  function mergeWorkspace(workspace: Partial<AuthoringPortraitWorkspace>) { if (workspace.selectedCandidateIds) selections = { ...workspace.selectedCandidateIds }; if (workspace.candidates) { candidates = [...workspace.candidates]; const remaining = new Set(candidates.map((candidate) => candidate.id)); chosenBySlot = Object.fromEntries(Object.entries(chosenBySlot).filter(([_, id]) => remaining.has(id))) as Partial<Record<AuthoringExpressionSlot, string>>; if (discardId && !remaining.has(discardId)) discardId = null; } }
  async function snapshot(jobId: string) { if (!npcId) return null; const response = await fetch(`/api/npcs/authoring/${npcId}/portrait-jobs/${jobId}`, { credentials: 'same-origin', cache: 'no-store' }); if (!response.ok) return null; const data = await response.json() as Snapshot; merge(data); return data; }
  function watch(jobId: string) { watchedJobId = jobId; stream?.close(); if (timer) clearTimeout(timer); if (typeof document !== 'undefined' && document.hidden) return; const poll = async () => { if (document.hidden) return; const data = await snapshot(jobId); if (!data || terminal(data.status)) return; timer = setTimeout(poll, Math.max(1000, Math.min(data.pollAfterMs || 2000, 5000))); }; if (!npcId || typeof EventSource === 'undefined') { void poll(); return; } stream = new EventSource(`/api/npcs/authoring/${npcId}/portrait-jobs/${jobId}/events`); stream.addEventListener('portrait-job', () => { void snapshot(jobId).then((data) => { if (data && terminal(data.status)) stream?.close(); }); }); stream.onerror = () => { stream?.close(); void poll(); }; void snapshot(jobId); }
  function result(event: Event) { const data = (event as CustomEvent<{ action?: string; message?: string; jobId?: string; portrait?: Snapshot; spriteWorkspace?: Partial<AuthoringPortraitWorkspace> }>).detail; if (!data || data.action !== 'portrait') return; message = data.message ?? ''; if (data.portrait) merge(data.portrait); if (data.spriteWorkspace) mergeWorkspace(data.spriteWorkspace); if (data.jobId) watch(data.jobId); }
  function tabs(event: KeyboardEvent) { const index = AUTHORING_EXPRESSION_SLOTS.indexOf(activeSlot); const movement = event.key === 'ArrowRight' ? 1 : event.key === 'ArrowLeft' ? -1 : event.key === 'Home' ? -index : event.key === 'End' ? AUTHORING_EXPRESSION_SLOTS.length - 1 - index : 0; if (!movement && !['Home', 'End'].includes(event.key)) return; event.preventDefault(); const next = AUTHORING_EXPRESSION_SLOTS[(index + movement + AUTHORING_EXPRESSION_SLOTS.length) % AUTHORING_EXPRESSION_SLOTS.length]; switchSlot(next); requestAnimationFrame(() => panel.querySelector<HTMLButtonElement>(`[data-slot="${next}"]`)?.focus()); }
  onMount(() => { const form = panel.closest('form'); const visibility = () => { if (document.hidden) { stream?.close(); if (timer) clearTimeout(timer); return; } if (watchedJobId) watch(watchedJobId); }; form?.addEventListener('portrait-action-result', result); document.addEventListener('visibilitychange', visibility); if (portrait.activeBatch?.status === 'generating') watch(portrait.activeBatch.id); return () => { form?.removeEventListener('portrait-action-result', result); document.removeEventListener('visibilitychange', visibility); stream?.close(); if (timer) clearTimeout(timer); }; });
</script>

<section bind:this={panel} class="workspace-panel portrait-panel" id="portrait-artwork" aria-labelledby="portrait-heading">
  <div class="workspace-panel-heading"><span class="workspace-step">02</span><div><p class="eyebrow">Character artwork</p><h2 id="portrait-heading">Character sprites</h2><p>Select Neutral first. Missing optional expressions resolve to Neutral in the scene preview and at runtime.</p></div></div>
  <div class="sprite-tabs" role="tablist" tabindex="-1" aria-label="Expression sprite slots" onkeydown={tabs}>{#each AUTHORING_EXPRESSION_SLOTS as slot}{@const locked = slot !== 'neutral' && !neutralSelected}<button type="button" role="tab" data-slot={slot} aria-selected={activeSlot === slot} aria-controls={`sprite-${slot}`} tabindex={activeSlot === slot ? 0 : -1} aria-disabled={locked} onclick={() => switchSlot(slot)}>{labels[slot]}{#if selections[slot]}<small>selected</small>{:else if locked}<small>select Neutral</small>{/if}</button>{/each}</div>
  <div id={`sprite-${activeSlot}`} role="tabpanel" aria-label={`${labels[activeSlot]} sprite`}>
    {#if optionalLocked}<div class="workspace-callout unavailable" role="status"><strong>Neutral comes first</strong><span>Select a Neutral sprite before creating optional expressions.</span></div>{:else if !editable}<div class="workspace-callout unavailable" role="status"><strong>Sprite selection is read-only</strong></div>{:else}<div class="sprite-create-grid"><div class="sprite-create-path"><h3>Upload artwork</h3><p>Upload one transparent PNG. The upload adds a candidate and never replaces a selected sprite.</p><input type="hidden" name="revision" value={revision} /><label>PNG sprite <input name="sprite" type="file" accept="image/png" /></label><button class="secondary-action" type="submit" formaction="?/uploadSprite" name="slot" value={activeSlot} data-portrait-action="upload">Upload {labels[activeSlot]}</button></div><div class="sprite-create-path"><h3>Generate alternatives</h3>{#if portrait.available}<div class="portrait-direction-grid"><label>Expression <select name="expression"><option value="from_sheet">From sheet</option><option value="warm">Warm</option><option value="wary">Wary</option><option value="determined">Determined</option><option value="thoughtful">Thoughtful</option><option value="stern">Stern</option></select></label><label>Alternatives <select name="count" bind:value={requestedCount}><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label><label>Pose <select name="pose"><option value="automatic">From sheet</option><option value="relaxed">Relaxed</option><option value="confident">Confident</option><option value="guarded">Guarded</option><option value="working">Working</option></select></label><label>Clothing <select name="clothingCondition"><option value="from_sheet">From sheet</option><option value="well_kept">Well-kept</option><option value="patched">Patched</option><option value="road_worn">Road-worn</option></select></label></div><input type="hidden" name="revision" value={revision} /><label>Named detail <select name="item"><option value="">No additional detail</option>{#each itemOptions as item}<option value={item}>{item}</option>{/each}</select></label><label>Composition note <textarea name="note" maxlength="240"></textarea></label><button class="primary-action" type="submit" formaction="?/portrait" name="slot" value={activeSlot} data-portrait-action="generate">Generate {requestedCount} alternative{requestedCount === '1' ? '' : 's'}</button>{:else}<p class="workspace-muted">{portrait.reason ?? 'Portrait generation is unavailable.'}</p>{/if}</div></div>{/if}
    {#if message}<p class="workspace-callout portrait-live-status" role="status" aria-live="polite">{message}</p>{/if}{#if activeAlternatives.length}<div class="sprite-progress" aria-live="polite"><strong>Generation progress</strong>{#each activeAlternatives as alternative}<span>Alternative {alternative.ordinal}: {alternative.stage.replaceAll('_', ' ')}{alternative.errorCode ? ` (${alternative.errorCode.replaceAll('_', ' ')})` : ''}</span>{/each}</div>{/if}
    <fieldset class="portrait-candidate-fieldset" disabled={!editable || optionalLocked}><legend>{labels[activeSlot]} candidates</legend><p class="workspace-muted">Pick one candidate, then explicitly select it. Uploaded and generated sprites share this grid.</p><div class="portrait-candidate-grid" aria-live="polite">{#each slotCandidates as candidate (candidate.id)}<label class:selected={candidate.id === selectedSlotCandidate} class:current-choice={candidate.id === chosen} class:stale={candidate.staleNeutralAnchor || candidate.state === 'stale'} class:unavailable={!selectable(candidate)} class="portrait-candidate"><input type="radio" name="candidateId" value={candidate.id} checked={candidate.id === chosen} onchange={() => { chosenBySlot = { ...chosenBySlot, [activeSlot]: candidate.id }; confirmStale = false; }} disabled={!selectable(candidate)} /><span class="portrait-preview checkerboard">{#if candidate.previewUrl}<img src={candidate.previewUrl} alt={candidate.altText} />{:else}<span class="portrait-preview-empty">{candidate.state === 'generating' ? 'Preparing preview…' : candidate.state === 'failed' ? 'No usable image returned' : 'Preview unavailable'}</span>{/if}</span><span class="portrait-candidate-copy"><span><strong>{candidate.source === 'author_upload' ? 'Uploaded sprite' : `Alternative ${candidate.ordinal || 'pending'}`}</strong><span class="status-pill">{candidateLabel(candidate)}</span></span><small>{candidate.source === 'author_upload' ? 'Author upload' : 'AI generated'} · {candidate.hasAlpha ? 'Transparency verified' : 'Transparency pending'}</small>{#if candidate.failureReason}<small>{candidate.failureReason.replaceAll('_', ' ')}</small>{/if}</span></label>{:else}<p class="workspace-empty">No {labels[activeSlot].toLowerCase()} candidates yet.</p>{/each}</div></fieldset>
    {#if chosenCandidate}<div class="portrait-select-footer"><input type="hidden" name="revision" value={revision} />{#if activeSlot === 'neutral' && neutralSelected && chosenCandidate.id !== selectedSlotCandidate}<label class="confirmation"><input type="checkbox" bind:checked={confirmNeutral} /> I understand changing Neutral clears optional selections.</label>{/if}{#if chosenCandidate.staleNeutralAnchor}<label class="confirmation"><input type="checkbox" name="confirmStale" value="true" bind:checked={confirmStale} /> I reviewed this sprite against the current Neutral anchor.</label>{/if}<button class="primary-action" type="submit" formaction="?/selectPortrait" name="slot" value={activeSlot} data-portrait-action="select" disabled={!selectable(chosenCandidate) || (activeSlot === 'neutral' && neutralSelected && chosenCandidate.id !== selectedSlotCandidate && !confirmNeutral) || (chosenCandidate.staleNeutralAnchor && !confirmStale)}>{chosenCandidate.id === selectedSlotCandidate ? `${labels[activeSlot]} selected` : `Select ${labels[activeSlot]}`}</button>{#if chosenCandidate.id !== selectedSlotCandidate}<button type="button" class="quiet-danger" onclick={() => discardId = chosenCandidate.id}>Discard candidate</button>{/if}</div>{/if}
    {#if discardId}<div class="workspace-callout warning" role="alert"><strong>Discard this candidate?</strong><span>This is permanent. The server refuses candidates that are selected or pinned by a version.</span><input type="hidden" name="candidateId" value={discardId} /><input type="hidden" name="revision" value={revision} /><div><button type="submit" class="quiet-danger" formaction="?/discardPortrait" data-portrait-action="discard">Discard permanently</button><button type="button" class="secondary-action" onclick={() => discardId = null}>Keep candidate</button></div></div>{/if}
  </div>
</section>
<style>
  .sprite-tabs { display: grid; grid-template-columns: repeat(6, minmax(0, 1fr)); gap: .45rem; margin: 1rem 0; }
  .sprite-tabs button { min-height: 44px; border: 1px solid rgba(212, 164, 62, .42); background: rgba(27, 20, 8, .8); color: #ebd38d; cursor: pointer; padding: .45rem; }
  .sprite-tabs button[aria-selected="true"] { border-color: #e5ba58; background: linear-gradient(135deg, #344425, #162113); }
  .sprite-tabs button[aria-disabled="true"] { opacity: .7; }
  .sprite-tabs small { display: block; font-size: .68rem; }
  .sprite-create-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 1rem; margin: 1rem 0; }
  .sprite-create-path { border: 1px solid rgba(212, 164, 62, .26); padding: 1rem; background: rgba(12, 9, 4, .35); }
  .sprite-create-path h3 { margin: 0 0 .35rem; color: #efd180; font-family: Georgia, serif; }
  .sprite-create-path label { display: block; margin: .55rem 0; }
  .sprite-create-path input, .sprite-create-path select, .sprite-create-path textarea { width: 100%; box-sizing: border-box; }
  .portrait-direction-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: .5rem; }
  .sprite-progress { display: grid; gap: .25rem; margin: 1rem 0; padding: .8rem; border-left: 3px solid #d6ad49; background: rgba(65, 49, 14, .25); }
  .portrait-preview { pointer-events: none; }
  .portrait-select-footer { display: flex; flex-wrap: wrap; align-items: center; gap: .7rem; margin-top: 1rem; }
  .confirmation { flex-basis: 100%; color: #ecd99c; }
  @media (max-width: 700px) { .sprite-tabs { grid-template-columns: repeat(3, minmax(0, 1fr)); } .sprite-create-grid { grid-template-columns: 1fr; } }
  @media (prefers-reduced-motion: reduce) { .portrait-candidate, .sprite-tabs button { transition: none !important; } }
</style>
