import type { NpcMemoryEmbeddingProvider } from './contracts';

type RpcError = { message: string; code?: string } | null;
export type NpcMemoryEvidenceClient = { rpc(name: string, args?: Record<string, unknown>, signal?: AbortSignal): Promise<{ data: unknown; error: RpcError }> };
export type NpcMemoryEvidenceInput = Readonly<{ actorId: string; instanceId: string; view: 'speech' | 'review' | 'deliberation' | 'transition'; cutoffLedgerSequence: number | null; query: string; knownRefs: readonly string[]; budget: Readonly<{ limit: number; candidateLimit: number; fallbackLimit: number }>; signal: AbortSignal }>;
export type NpcMemoryEvidenceResult = Readonly<{ evidence: Readonly<Record<string, unknown>>; querySemantic: 'ready' | 'not_configured' | 'no_active_profile' | 'profile_unavailable' | 'provider_failed' | 'profile_rotated' }>;
type Profile = Readonly<{ id: string; processorVersion: string; model: string; dimensions: number }>;
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const object = (value: unknown): value is Record<string, unknown> => !!value && typeof value === 'object' && !Array.isArray(value);
const exact = (value: unknown, keys: readonly string[]): value is Record<string, unknown> => object(value) && Object.keys(value).length === keys.length && keys.every((key) => key in value);
const freeze = <T>(value: T): T => { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value as object)) freeze(child); } return value; };
const scalars = (value: string, limit: number) => Array.from(value.normalize('NFC')).slice(0, limit).join('');
export const normalizeNpcMemoryQuery = (value: string) => scalars(value.replace(/\s+/gu, ' ').trim(), 400);
export const normalizeNpcMemoryRefs = (values: readonly string[]) => {
  const unique = new Map<string, string>();
  for (const raw of values) { const value = scalars(raw.replace(/\s+/gu, ' ').trim(), 120); if (value && !unique.has(value.toLocaleLowerCase('en-US'))) unique.set(value.toLocaleLowerCase('en-US'), value); }
  return [...unique.values()].slice(0, 32);
};
function validate(input: NpcMemoryEvidenceInput) {
  if (!input || typeof input.query!=='string' || !Array.isArray(input.knownRefs) || !input.knownRefs.every((ref)=>typeof ref==='string') || !input.budget || !input.signal || typeof input.signal.aborted!=='boolean' || !UUID.test(input.actorId) || !UUID.test(input.instanceId) || !['speech', 'review', 'deliberation', 'transition'].includes(input.view) || (input.cutoffLedgerSequence !== null && (!Number.isSafeInteger(input.cutoffLedgerSequence) || input.cutoffLedgerSequence < 0)) || !Number.isSafeInteger(input.budget.limit) || input.budget.limit < 1 || input.budget.limit > 32 || !Number.isSafeInteger(input.budget.candidateLimit) || input.budget.candidateLimit < input.budget.limit || input.budget.candidateLimit > 128 || !Number.isSafeInteger(input.budget.fallbackLimit) || input.budget.fallbackLimit < 0 || input.budget.fallbackLimit > 16) throw new Error('NPC memory evidence input is invalid.');
  if (input.signal.aborted) throw new DOMException('Aborted', 'AbortError');
}
function profile(value: unknown): Profile | null {
  if (!exact(value, ['semanticAvailable', 'profile'])) throw new Error('NPC memory profile response is malformed.');
  if (value.semanticAvailable === false && value.profile === null) return null;
  if (!exact(value.profile, ['id', 'processorVersion', 'model', 'dimensions']) || value.semanticAvailable !== true || typeof value.profile.id !== 'string' || !UUID.test(value.profile.id) || typeof value.profile.processorVersion !== 'string' || !value.profile.processorVersion || typeof value.profile.model !== 'string' || !value.profile.model || typeof value.profile.dimensions !== 'number' || !Number.isSafeInteger(value.profile.dimensions) || value.profile.dimensions < 1 || value.profile.dimensions > 4096) throw new Error('NPC memory profile response is malformed.');
  return value.profile as Profile;
}
function evidence(value: unknown): Readonly<Record<string, unknown>> {
  const item = (x: unknown) => {if(!exact(x,['id','recordRootId','recordVersion','kind','text','quote','speaker','truthClass','disclosureClass','status','relatedQuestId','correctionMemoryId','entityRefs','importance','occurredDay','occurredSequence','learnedDay','learnedSequence','sourceKind','sourceId','sourceVersion','sourceHash','ledgerSequence','channelRanks','fusedScore','selectionReasons']))return false;const y=x as Record<string,any>, ranks=y.channelRanks as Record<string,any>, reasons=y.selectionReasons as unknown[];return typeof y.id==='string'&&UUID.test(y.id)&&typeof y.recordRootId==='string'&&UUID.test(y.recordRootId)&&Number.isSafeInteger(y.recordVersion)&&y.recordVersion>0&&typeof y.kind==='string'&&y.kind.trim().length>0&&y.kind.length<=120&&typeof y.text==='string'&&y.text.length>0&&typeof y.quote==='string'&&typeof y.speaker==='string'&&y.speaker.trim().length>0&&['canonical','attributed','belief','derived'].includes(y.truthClass)&&['player_visible','npc_known','npc_private'].includes(y.disclosureClass)&&(y.status===null||['unresolved','fulfilled','withdrawn','disputed','superseded'].includes(y.status))&&(y.relatedQuestId===null||(typeof y.relatedQuestId==='string'&&UUID.test(y.relatedQuestId)))&&(y.correctionMemoryId===null||(typeof y.correctionMemoryId==='string'&&UUID.test(y.correctionMemoryId)))&&Array.isArray(y.entityRefs)&&y.entityRefs.every((r:unknown)=>typeof r==='string')&&['dialogue_turn','quest_event','hospitality','resident_evolution'].includes(y.sourceKind)&&typeof y.sourceId==='string'&&UUID.test(y.sourceId)&&Number.isSafeInteger(y.sourceVersion)&&y.sourceVersion>0&&typeof y.sourceHash==='string'&&/^[0-9a-f]{64}$/.test(y.sourceHash)&&Number.isSafeInteger(y.importance)&&y.importance>=1&&y.importance<=3&&Number.isSafeInteger(y.occurredDay)&&y.occurredDay>0&&Number.isSafeInteger(y.learnedDay)&&y.learnedDay>=0&&Number.isSafeInteger(y.occurredSequence)&&y.occurredSequence>=0&&Number.isSafeInteger(y.learnedSequence)&&y.learnedSequence>=0&&Number.isSafeInteger(y.ledgerSequence)&&y.ledgerSequence>=0&&object(ranks)&&Object.keys(ranks).every(k=>['relational','lexical','semantic','recent'].includes(k)&&Number.isSafeInteger(ranks[k])&&(ranks[k] as number)>=1)&&typeof y.fusedScore==='number'&&Number.isFinite(y.fusedScore)&&y.fusedScore>=0&&Array.isArray(reasons)&&reasons.length>0&&reasons.every((r:unknown)=>typeof r==='string'&&['unresolved_commitment','exact_reference','important_recent','lexical','semantic_exact'].includes(r))&&new Set(reasons).size===reasons.length;};
  const member = (x: unknown) => object(x) && item({ ...x, channelRanks:{relational:1}, fusedScore:0, selectionReasons:['important_recent'] });
  const bundle = (x: unknown) => { if (!exact(x,['selectedId','members','coverage']) || typeof x.selectedId!=='string'||!UUID.test(x.selectedId)||!Array.isArray(x.members)||x.members.length>12||!x.members.every(member)||!exact(x.coverage,['requiredTotal','requiredIncluded','missingRequiredIds','optionalTruncated','complete'])) return false; const c=x.coverage as Record<string,any>,missing=c.missingRequiredIds as unknown[]; return Number.isSafeInteger(c.requiredTotal)&&c.requiredTotal>=0&&Number.isSafeInteger(c.requiredIncluded)&&c.requiredIncluded>=0&&c.requiredIncluded<=c.requiredTotal&&Array.isArray(missing)&&missing.every((id)=>typeof id==='string'&&UUID.test(id))&&new Set(missing).size===missing.length&&c.requiredTotal-c.requiredIncluded===missing.length&&typeof c.optionalTruncated==='boolean'&&typeof c.complete==='boolean'&&c.complete===(missing.length===0); };
  const sourceKind = (value: unknown) => ['dialogue_turn','quest_event','hospitality','resident_evolution'].includes(String(value));
  const fallback = (x: unknown) => { if(!exact(x,['sourceKind','sourceId','sourceVersion','sourceHash','ledgerSequence','envelope']))return false; const y=x as Record<string,any>;return sourceKind(y.sourceKind)&&typeof y.sourceId==='string'&&UUID.test(y.sourceId)&&Number.isSafeInteger(y.sourceVersion)&&y.sourceVersion>0&&typeof y.sourceHash==='string'&&/^[0-9a-f]{64}$/.test(y.sourceHash)&&Number.isSafeInteger(y.ledgerSequence)&&y.ledgerSequence>=0&&object(y.envelope);};
  const manifest = (x: unknown) => { if(!exact(x,['sourceKind','sourceId','sourceVersion','sourceHash','ledgerSequence']))return false;const y=x as Record<string,any>;return sourceKind(y.sourceKind)&&typeof y.sourceId==='string'&&UUID.test(y.sourceId)&&Number.isSafeInteger(y.sourceVersion)&&y.sourceVersion>0&&typeof y.sourceHash==='string'&&/^[0-9a-f]{64}$/.test(y.sourceHash)&&Number.isSafeInteger(y.ledgerSequence)&&y.ledgerSequence>=0;};
  const semantic = exact(value,['retrievalVersion', 'cutoffLedgerSequence', 'semantic', 'items', 'bundles', 'sourceFallback', 'sourceManifest', 'coverage']) ? value.semantic : null;
  const semanticOk = (()=>{if(!exact(semantic,['available','availability','profile']))return false;const s=semantic as Record<string,any>;if(s.available===false)return s.availability==='disabled'&&s.profile===null;if(s.available!==true||!['ready','no_candidates'].includes(s.availability)||!exact(s.profile,['id','processorVersion','model','dimensions']))return false;const p=s.profile as Record<string,any>;return typeof p.id==='string'&&UUID.test(p.id)&&typeof p.processorVersion==='string'&&p.processorVersion.length>0&&typeof p.model==='string'&&p.model.length>0&&Number.isSafeInteger(p.dimensions)&&p.dimensions>=1&&p.dimensions<=4096;})();
  const coverage = object(value) ? value.coverage : null;
  const fallbackCoverage = (()=>{if(!exact(coverage,['complete','sourceFallback','watermarks']))return false;const c=coverage as Record<string,any>,f=c.sourceFallback as Record<string,any>;const total=f.total as number,included=f.included as number;if(typeof c.complete!=='boolean'||!exact(f,['total','included','truncated','complete'])||!Number.isSafeInteger(total)||total<0||!Number.isSafeInteger(included)||included<0||included>total||typeof f.truncated!=='boolean'||typeof f.complete!=='boolean'||f.complete!==(included===total)||f.truncated!==(included<total)||!Array.isArray(c.watermarks))return false;return c.watermarks.every((w:unknown)=>{if(!exact(w,['processorKind','processorVersion','contiguousSequence','examinedThroughSequence','gapSequence']))return false;const z=w as Record<string,any>;return ['extract','summary','embedding'].includes(z.processorKind)&&typeof z.processorVersion==='string'&&z.processorVersion.length>0&&Number.isSafeInteger(z.contiguousSequence)&&z.contiguousSequence>=-1&&Number.isSafeInteger(z.examinedThroughSequence)&&z.examinedThroughSequence>=-1&&(z.gapSequence===null||(Number.isSafeInteger(z.gapSequence)&&z.gapSequence>=0));});})();
  const cutoff=exact(value,['retrievalVersion', 'cutoffLedgerSequence', 'semantic', 'items', 'bundles', 'sourceFallback', 'sourceManifest', 'coverage']) ? value.cutoffLedgerSequence as number : -2;
  const topComplete = exact(value,['retrievalVersion', 'cutoffLedgerSequence', 'semantic', 'items', 'bundles', 'sourceFallback', 'sourceManifest', 'coverage']) && object(value.coverage) ? value.coverage.complete : undefined;
  if (!exact(value, ['retrievalVersion', 'cutoffLedgerSequence', 'semantic', 'items', 'bundles', 'sourceFallback', 'sourceManifest', 'coverage']) || value.retrievalVersion !== 'npc-memory-evidence-v4' || !Number.isSafeInteger(cutoff)||cutoff<-1 || !semanticOk || !Array.isArray(value.items) || value.items.length>32 || !value.items.every(item) || !Array.isArray(value.bundles)||value.bundles.length>32 || !value.bundles.every(bundle) || !Array.isArray(value.sourceFallback)||value.sourceFallback.length>16 || !value.sourceFallback.every(fallback) || !Array.isArray(value.sourceManifest)||value.sourceManifest.length>512 || !value.sourceManifest.every(manifest) || !fallbackCoverage || topComplete !== ((coverage as Record<string,any>).sourceFallback.complete && value.bundles.every((b: any)=>b.coverage.complete))) throw new Error('NPC memory evidence response is malformed.');
  return freeze(value);
}
function args(input: NpcMemoryEvidenceInput, query: string, refs: string[], semantic?: Profile & { vector: string }) {
  return { p_actor: input.actorId, p_instance_id: input.instanceId, p_view: input.view, p_cutoff_ledger_sequence: input.cutoffLedgerSequence, p_query: query, p_known_refs: refs, p_limit: input.budget.limit, p_candidate_limit: input.budget.candidateLimit, p_fallback_limit: input.budget.fallbackLimit, p_profile_id: semantic?.id ?? null, p_processor_version: semantic?.processorVersion ?? null, p_model: semantic?.model ?? null, p_dimensions: semantic?.dimensions ?? null, p_query_embedding: semantic?.vector ?? null };
}
async function retrieve(client: NpcMemoryEvidenceClient, request: Record<string, unknown>, signal: AbortSignal) { const result = await client.rpc('npc_memory_evidence_retrieve_for_actor', request, signal); if (result.error) throw Object.assign(new Error(result.error.message), { code: result.error.code }); return evidence(result.data); }

/** One server-only evidence boundary. Semantic enrichment is optional and never changes fallback scope. */
export async function retrieveNpcMemoryEvidence(client: NpcMemoryEvidenceClient, input: NpcMemoryEvidenceInput, embeddingProvider?: NpcMemoryEmbeddingProvider): Promise<NpcMemoryEvidenceResult> {
  validate(input); const query = normalizeNpcMemoryQuery(input.query), refs = normalizeNpcMemoryRefs(input.knownRefs);
  const lexical = async (status: NpcMemoryEvidenceResult['querySemantic']) => freeze({ evidence: await retrieve(client, args(input, query, refs), input.signal), querySemantic: status });
  if (!embeddingProvider) return lexical('not_configured');
  let active: Profile | null;
  try {
    const result = await client.rpc('npc_memory_active_embedding_profile', {}, input.signal);
    if (result.error) { if (result.error.code) throw Object.assign(new Error(result.error.message), { code: result.error.code }); return lexical('profile_unavailable'); }
    active = profile(result.data);
  } catch (error) { if ((error as { code?: string }).code || (error as Error).message.includes('malformed')) throw error; return lexical('profile_unavailable'); }
  if (input.signal.aborted) throw new DOMException('Aborted', 'AbortError');
  if (!active) return lexical('no_active_profile');
  let vector: string;
  try {
    if (input.signal.aborted) throw new DOMException('Aborted', 'AbortError');
    const prepared = embeddingProvider.preflight({ inputText: query, model: active.model, dimensions: active.dimensions });
    const embedded = await embeddingProvider.embed(prepared, input.signal);
    if (embedded.model !== active.model || embedded.dimensions !== active.dimensions) throw new Error('Embedding identity is invalid.');
    vector = embedded.vector;
  } catch (error) { if ((error as { name?: string }).name === 'AbortError') throw error; return lexical('provider_failed'); }
  try { return freeze({ evidence: await retrieve(client, args(input, query, refs, { ...active, vector }), input.signal), querySemantic: 'ready' }); }
  catch (error) { if ((error as { code?: string }).code === 'PT400' && (error as Error).message === 'Evidence embedding identity is invalid') return lexical('profile_rotated'); throw error; }
}
