#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

banner "Media storage cutover"

stage "Hosted project and operator key"
say "We'll save the hosted Supabase URL and a server-only secret key in the ignored root .env."
open_url "https://supabase.com/dashboard/projects"
step "Open the hosted project, then copy its Project URL from Connect or Settings → API Keys."
ask MEDIA_SUPABASE_URL "Paste the hosted Project URL:"
if [[ ! "$MEDIA_SUPABASE_URL" =~ ^https://[a-z0-9-]+\.supabase\.co/?$ ]]; then
  warn "expected a hosted https://<project-ref>.supabase.co URL; refusing a local or malformed URL"
  exit 1
fi
SUPABASE_PROJECT_REF="${MEDIA_SUPABASE_URL#https://}"
SUPABASE_PROJECT_REF="${SUPABASE_PROJECT_REF%%.supabase.co*}"
step "On API Keys, create or reveal a secret key (preferred, starts sb_secret_). Do not use a publishable/anon key."
ask_secret MEDIA_SUPABASE_SECRET_KEY "Paste the server-only secret key:"
if [[ ! "$MEDIA_SUPABASE_SECRET_KEY" =~ ^sb_secret_ ]]; then
  warn "this does not look like a current Supabase secret key; no value was written"
  exit 1
fi
write_env MEDIA_SUPABASE_URL "$MEDIA_SUPABASE_URL"
write_env MEDIA_SUPABASE_SECRET_KEY "$MEDIA_SUPABASE_SECRET_KEY"
if _existing MEDIA_SUPABASE_SERVICE_ROLE_KEY >/dev/null 2>&1; then
  LEGACY_ENV_TMP="$(mktemp)"
  grep -vE '^MEDIA_SUPABASE_SERVICE_ROLE_KEY=' "$ENV_FILE" > "$LEGACY_ENV_TMP" || true
  mv "$LEGACY_ENV_TMP" "$ENV_FILE"
  note "Removed the legacy MEDIA_SUPABASE_SERVICE_ROLE_KEY entry from $ENV_FILE."
fi
chmod 600 "$ENV_FILE"
export MEDIA_SUPABASE_URL MEDIA_SUPABASE_SECRET_KEY
note "The key stays local. These media workflows do not need or receive a GitHub Actions secret."
pause "Credentials saved. Press Enter to provision the buckets."

stage "Link and provision storage"
say "The migration creates separate source-masters and review-evidence buckets with no browser write policy."
if ! command -v supabase >/dev/null 2>&1; then
  SKIPPED+=("Install the Supabase CLI, then re-run this wizard to provision the buckets")
  warn "Supabase CLI is not installed; skipping hosted provisioning"
else
  step "Complete the Supabase CLI browser login if prompted."
  supabase login
  step "Linking this checkout to project $SUPABASE_PROJECT_REF. A database password may be requested."
  supabase link --project-ref "$SUPABASE_PROJECT_REF"
  say "Dry-running pending hosted database migrations:"
  supabase db push --dry-run
  if confirm "Apply the displayed migrations to this hosted project?"; then
    supabase db push
    note "Storage migration applied. Browser clients have no master access and no evidence write policy."
  else
    SKIPPED+=("Apply the hosted migration with: supabase db push")
    warn "bucket provisioning was not applied"
  fi
fi
pause "Press Enter when the storage migration has been applied."

stage "Verify and ingest the 20 masters"
DEFAULT_MASTER_SOURCE="${CODEX_HOME:-${HOME}/.codex}/generated_images/01a07a19-440d-7091-9a4c-a71dbcf9257f"
printf '  %sMaster source directory%s [%s]: ' "$BOLD" "$RESET" "$DEFAULT_MASTER_SOURCE"
read -r MASTER_SOURCE_DIR || true
MASTER_SOURCE_DIR="${MASTER_SOURCE_DIR:-$DEFAULT_MASTER_SOURCE}"
if [[ ! -d "$MASTER_SOURCE_DIR" ]]; then
  warn "directory does not exist: $MASTER_SOURCE_DIR"
  exit 1
fi
shopt -s nullglob
MASTER_FILES=("$MASTER_SOURCE_DIR"/*.png)
shopt -u nullglob
if (( ${#MASTER_FILES[@]} != 20 )); then
  warn "expected exactly 20 PNG masters, found ${#MASTER_FILES[@]}; refusing a partial import"
  exit 1
fi
say "Each object is signature/size/dimension checked, uploaded without overwrite, downloaded, and hash-verified."
if confirm "Upload and verify all 20 cataloged masters now?"; then
  for master_file in "${MASTER_FILES[@]}"; do
    master_name="$(basename "$master_file")"
    master_id="${master_name%.png}"
    npm run media:master:ingest -- --file "$master_file" --id "$master_id"
  done
  npm run media:masters:status || warn "objects are verified; release eligibility remains incomplete until the ZIP receipt is created"
else
  SKIPPED+=("Ingest and verify all 20 source masters")
  warn "master import skipped"
fi
pause "Press Enter after all catalog records report verified."

stage "Archive, restore-check, and off-machine copy"
say "The archive command downloads every object from Supabase and creates a deterministic ZIP plus checksum."
if ! command -v zip >/dev/null 2>&1 || ! command -v unzip >/dev/null 2>&1; then
  warn "Info-ZIP's zip and unzip commands are required for deterministic archive creation and verification"
  exit 1
fi
ARCHIVE_OUTPUT=""
if ARCHIVE_OUTPUT="$(npm run media:masters:archive 2>&1)"; then
  printf '%s\n' "$ARCHIVE_OUTPUT"
  ARCHIVE_PATH="$(printf '%s\n' "$ARCHIVE_OUTPUT" | sed -n 's/^created //p' | tail -n1)"
else
  printf '%s\n' "$ARCHIVE_OUTPUT"
  warn "archive creation did not complete; this may be a safe non-overwrite on a re-run"
  printf '  %sExisting ZIP path to verify%s: ' "$BOLD" "$RESET"
  read -r ARCHIVE_PATH || true
fi
if [[ -z "${ARCHIVE_PATH:-}" || ! -f "$ARCHIVE_PATH" || ! -f "${ARCHIVE_PATH}.sha256" ]]; then
  warn "both a ZIP and its .sha256 companion are required"
  exit 1
fi
npm run media:masters:verify -- --archive "$ARCHIVE_PATH"
ARCHIVE_ID="$(basename "$ARCHIVE_PATH" .zip)"
open_url "https://drive.google.com/drive/my-drive"
step "Create or open ByRookAndCrook/media-master-backups/."
step "Upload $(basename "$ARCHIVE_PATH") and $(basename "${ARCHIVE_PATH}.sha256"). Do not upload the .env file."
if confirm "Have both files finished uploading to Google Drive?"; then
  npm run media:masters:confirm-drive -- --archive "$ARCHIVE_ID"
else
  SKIPPED+=("Copy $ARCHIVE_PATH and ${ARCHIVE_PATH}.sha256 to ByRookAndCrook/media-master-backups/ on Google Drive")
  warn "local restore is verified, but off-machine disaster recovery remains incomplete"
fi
npm run media:masters:status

finish
