import type { ProviderStage } from './settlement-contracts';
export const SETTLEMENT_PROMPTS: Record<ProviderStage, string> = {
  proposer: 'You propose one structured NPC/world evolution from the frozen game snapshot. Use only supplied IDs, facts, capabilities, and typed commands. Belief operations are attributed NPC knowledge, never canon: cite frozen evidence fingerprints and never invent database IDs. Never claim that an action has been applied. Put the full versioned proposal JSON in proposalJson.',
  critic: 'You independently check a proposed NPC/world evolution against the frozen schema, profile, capabilities, and world snapshot. Return accept, reject, or repair. A repair must be narrow and testable. Include an empty instructions array unless the outcome is repair. Return JSON only.',
  repair: 'Repair the proposed NPC/world evolution according to the critic instructions. Use only frozen input, existing IDs, and supported typed commands. Beliefs remain attributed knowledge and must cite frozen evidence without database IDs. Do not claim any effect was applied. Put the full versioned proposal JSON in proposalJson.',
  final_critic: 'Independently approve or reject this repaired NPC/world evolution against the frozen game snapshot. Do not request another repair. Include an empty instructions array. Return JSON only.',
  digest: 'Write a public morning digest from the supplied public facts only. Do not reveal private beliefs, motives, pressure, prompts, rolls, hidden plans, or provider reasoning. Return JSON only.',
  canon_proposer: 'Propose at most one public world-canon-event-v1 from the frozen day-close worldSnapshot. Use only registeredTemplateKeys and IDs in worldSnapshot.entityKinds; do not infer participants, templates, world facts, or outcomes outside that snapshot. Emit eventJson containing exactly version, kind=world_event, templateKey, participantEntityIds, title, summary, payload={template,participants,visibility:"public"}, and optional reuseKey. payload must exactly repeat the selected template and participant IDs. Never claim the event has been applied, reveal private reasoning, or emit code, routes, tools, or extra fields.',
  canon_critic: 'Independently check one proposed public world-canon-event-v1 against the frozen day-close worldSnapshot. Accept only an exact event using a registered template and known allowed participants; reject invented world facts and mismatched payload fields. Return accept, reject, or repair. A repair must be narrow and testable. Include an empty instructions array unless the outcome is repair. Return JSON only.',
  canon_repair: 'Repair one proposed public world-canon-event-v1 only according to the critic instructions and the frozen day-close worldSnapshot. Use only its registeredTemplateKeys and entityKinds. Keep exactly one event and the exact public payload shape; do not add facts, participants, templates, code, or internal reasoning. Emit the full repaired event JSON in eventJson. Never claim it has been applied.',
  canon_final_critic: 'Independently accept or reject the repaired public world-canon-event-v1 against the frozen day-close worldSnapshot. Do not request another repair. Reject any event that adds unsupported facts, uses unregistered templates or unknown participants, or has a mismatched payload. Include an empty instructions array. Return JSON only.'
};
