export const WORLD_DEVELOPER_INSPECTOR_VERSION = 'world-developer-inspector-v1' as const;

export type DeveloperInspector = {
  version: typeof WORLD_DEVELOPER_INSPECTOR_VERSION;
  entities: Array<{ id:string; kind:string; key:string; origin:string; sourceVersion:string; lifecycle:string; discoveredDay:number|null; retiredDay:number|null; createdAt:string; relevance:number; history:Array<{ eventKind:string; sourceVersion:string; createdAt:string }> }>;
  settlements: Array<{ id:string; dayNumber:number; status:string; deadlineAt:string; failureCode:string|null; createdAt:string; completedAt:string|null; jobs:Array<{ id:string; ordinal:number; kind:string; status:string; failureCode:string|null; createdAt:string; completedAt:string|null; attempts:Array<{ attempt:number; status:string; leaseUntil:string; failureCode:string|null; startedAt:string; finishedAt:string|null }>; checkpoints:Array<{ stage:string; model:string; promptVersion:string; createdAt:string }> }> }>;
  artJobs: Array<{ id:string; entityId:string; status:string; attempt:number; appearanceVersion:string; failureCode:string|null; createdAt:string; completedAt:string|null; renderId:string|null }>;
  overrides: Array<{ id:string; saveId:string; targetKind:string; targetId:string; operation:string; beforeHash:string; outcome:string; actorId:string; createdAt:string }>;
};

const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const hash=/^[0-9a-f]{64}$/;
const failureCodes=new Set(['ATTEMPTS_EXHAUSTED','LEASE_EXPIRED','TIMEOUT','WORKER_FAILED','failed_moderated','failed_provider','failed_storage']);
type RecordValue=Record<string,unknown>;
const object=(v:unknown):v is RecordValue=>!!v&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:RecordValue,keys:string[])=>Object.keys(v).length===keys.length&&Object.keys(v).every((key)=>keys.includes(key));
const text=(v:unknown,max=240):v is string=>typeof v==='string'&&v.length>0&&v.length<=max;
const nullableText=(v:unknown,max=240)=>v===null||text(v,max);
const nullableFailureCode=(v:unknown)=>v===null||(typeof v==='string'&&failureCodes.has(v));
const integer=(v:unknown,min=0):v is number=>Number.isSafeInteger(v)&&typeof v==='number'&&v>=min;
const nullableInteger=(v:unknown)=>v===null||integer(v);

function history(v:unknown) { if(!Array.isArray(v)||v.length>100) return null; const parsed=v.map((entry)=>{ if(!object(entry)||!exact(entry,['eventKind','sourceVersion','createdAt'])||!text(entry.eventKind,80)||!text(entry.sourceVersion,128)||!text(entry.createdAt,64)) return null; return entry as DeveloperInspector['entities'][number]['history'][number]; }); return parsed.some((v)=>!v)?null:parsed as DeveloperInspector['entities'][number]['history']; }
function entities(v:unknown) { if(!Array.isArray(v)||v.length>150)return null; const parsed=v.map((entry)=>{if(!object(entry)||!exact(entry,['id','kind','key','origin','sourceVersion','lifecycle','discoveredDay','retiredDay','createdAt','relevance','history'])||!uuid.test(String(entry.id))||!text(entry.kind,32)||!text(entry.key,80)||!text(entry.origin,32)||!text(entry.sourceVersion,128)||!text(entry.lifecycle,32)||!nullableInteger(entry.discoveredDay)||!nullableInteger(entry.retiredDay)||!text(entry.createdAt,64)||!integer(entry.relevance)||!history(entry.history))return null;return entry as DeveloperInspector['entities'][number];});return parsed.some((v)=>!v)?null:parsed as DeveloperInspector['entities'];}
function settlements(v:unknown) { if(!Array.isArray(v)||v.length>20)return null; const parsed=v.map((s)=>{if(!object(s)||!exact(s,['id','dayNumber','status','deadlineAt','failureCode','createdAt','completedAt','jobs'])||!uuid.test(String(s.id))||!integer(s.dayNumber,1)||!text(s.status,32)||!text(s.deadlineAt,64)||!nullableFailureCode(s.failureCode)||!text(s.createdAt,64)||!nullableText(s.completedAt,64)||!Array.isArray(s.jobs)||s.jobs.length>64)return null;const jobs=s.jobs.map((j)=>{if(!object(j)||!exact(j,['id','ordinal','kind','status','failureCode','createdAt','completedAt','attempts','checkpoints'])||!uuid.test(String(j.id))||!integer(j.ordinal,1)||!text(j.kind,80)||!text(j.status,32)||!nullableFailureCode(j.failureCode)||!text(j.createdAt,64)||!nullableText(j.completedAt,64)||!Array.isArray(j.attempts)||j.attempts.length>3||!Array.isArray(j.checkpoints)||j.checkpoints.length>12)return null;const attempts=j.attempts.map((a)=>object(a)&&exact(a,['attempt','status','leaseUntil','failureCode','startedAt','finishedAt'])&&integer(a.attempt,1)&&text(a.status,32)&&text(a.leaseUntil,64)&&nullableFailureCode(a.failureCode)&&text(a.startedAt,64)&&nullableText(a.finishedAt,64)?a:null);const checkpoints=j.checkpoints.map((c)=>object(c)&&exact(c,['stage','model','promptVersion','createdAt'])&&text(c.stage,80)&&text(c.model,160)&&text(c.promptVersion,160)&&text(c.createdAt,64)?c:null);return attempts.some((a)=>!a)||checkpoints.some((c)=>!c)?null:j as DeveloperInspector['settlements'][number]['jobs'][number];});return jobs.some((j)=>!j)?null:s as DeveloperInspector['settlements'][number];});return parsed.some((s)=>!s)?null:parsed as DeveloperInspector['settlements'];}
function artJobs(v:unknown) {if(!Array.isArray(v)||v.length>150)return null;const parsed=v.map((j)=>object(j)&&exact(j,['id','entityId','status','attempt','appearanceVersion','failureCode','createdAt','completedAt','renderId'])&&uuid.test(String(j.id))&&uuid.test(String(j.entityId))&&text(j.status,32)&&integer(j.attempt)&&text(j.appearanceVersion,128)&&nullableFailureCode(j.failureCode)&&text(j.createdAt,64)&&nullableText(j.completedAt,64)&&(j.renderId===null||uuid.test(String(j.renderId)))?j:null);return parsed.some((j)=>!j)?null:parsed as DeveloperInspector['artJobs'];}
function overrides(v:unknown) {if(!Array.isArray(v)||v.length>100)return null;const parsed=v.map((o)=>object(o)&&exact(o,['id','saveId','targetKind','targetId','operation','beforeHash','outcome','actorId','createdAt'])&&uuid.test(String(o.id))&&uuid.test(String(o.saveId))&&text(o.targetKind,32)&&uuid.test(String(o.targetId))&&['requeue_settlement_job','requeue_runtime_art_job','set_runtime_art_appearance'].includes(String(o.operation))&&hash.test(String(o.beforeHash))&&text(o.outcome,240)&&uuid.test(String(o.actorId))&&text(o.createdAt,64)?o:null);return parsed.some((o)=>!o)?null:parsed as DeveloperInspector['overrides'];}

/** Reject an entire projection if a future SQL change widens the browser surface. */
export function parseDeveloperInspector(value:unknown):DeveloperInspector { if(!object(value)||!exact(value,['version','entities','settlements','artJobs','overrides'])||value.version!==WORLD_DEVELOPER_INSPECTOR_VERSION)throw new Error('Invalid developer inspector projection'); const parsed={entities:entities(value.entities),settlements:settlements(value.settlements),artJobs:artJobs(value.artJobs),overrides:overrides(value.overrides)};if(!parsed.entities||!parsed.settlements||!parsed.artJobs||!parsed.overrides)throw new Error('Invalid developer inspector projection');return {version:WORLD_DEVELOPER_INSPECTOR_VERSION,entities:parsed.entities as DeveloperInspector['entities'],settlements:parsed.settlements as DeveloperInspector['settlements'],artJobs:parsed.artJobs as DeveloperInspector['artJobs'],overrides:parsed.overrides as DeveloperInspector['overrides']}; }
