begin;
create table private.world_npc_memory_summary_sets (
 id uuid primary key default extensions.gen_random_uuid(), save_id uuid not null references public.tavern_saves(id) on delete cascade, instance_id uuid not null references private.world_npc_instances(id) on delete cascade,
 summary_kind text not null check(summary_kind in ('episode_summary','quest_summary')), set_version bigint not null default 1 check(set_version>0), closure_key text not null, disclosure_class text not null check(disclosure_class in ('player_visible','npc_known','npc_private')),
 cutoff_ledger_sequence bigint not null check(cutoff_ledger_sequence>=0), set_hash text not null check(set_hash ~ '^[0-9a-f]{64}$'), closure_status text not null default 'registered' check(closure_status in ('registered','blocked','invalidated')), invalidated_at timestamptz, created_at timestamptz not null default clock_timestamp(), unique(instance_id,summary_kind,closure_key,disclosure_class,set_version), check((closure_status='invalidated')=(invalidated_at is not null))
);
create table private.world_npc_memory_summary_leaves (
 set_id uuid not null references private.world_npc_memory_summary_sets(id) on delete cascade, ordinal integer not null check(ordinal>=0), source_kind text not null check(source_kind in ('dialogue_turn','quest_event','hospitality','resident_evolution')), source_id uuid not null, source_version bigint not null check(source_version>0), source_hash text not null check(source_hash ~ '^[0-9a-f]{64}$'), ledger_sequence bigint not null check(ledger_sequence>=0), occurred_day integer, occurred_sequence bigint, learned_day integer, learned_sequence bigint, speaker text, observer_instance_id uuid, related_quest_id uuid, entity_refs text[] not null default '{}', primary key(set_id,ordinal), unique(set_id,source_kind,source_id,source_version)
);
create table private.world_npc_memory_summary_batches (set_id uuid not null references private.world_npc_memory_summary_sets(id) on delete cascade,batch_ordinal integer not null check(batch_ordinal>=0),first_leaf_ordinal integer not null check(first_leaf_ordinal>=0),last_leaf_ordinal integer not null check(last_leaf_ordinal>=first_leaf_ordinal),leaf_count integer not null check(leaf_count between 1 and 64),primary key(set_id,batch_ordinal),check(last_leaf_ordinal-first_leaf_ordinal+1=leaf_count));
create index world_npc_memory_summary_sets_scope on private.world_npc_memory_summary_sets(instance_id,summary_kind,created_at desc);
create function private.world_npc_memory_summary_set_guard() returns trigger language plpgsql security definer set search_path='' as $f$
begin
 if tg_op='DELETE' then if pg_trigger_depth()=1 then raise sqlstate 'PT409' using message='Summary sets are append-only'; end if; return old; end if;
 if old.save_id is distinct from new.save_id or old.instance_id is distinct from new.instance_id or old.summary_kind is distinct from new.summary_kind or old.set_version is distinct from new.set_version or old.closure_key is distinct from new.closure_key or old.disclosure_class is distinct from new.disclosure_class or old.cutoff_ledger_sequence is distinct from new.cutoff_ledger_sequence or old.set_hash is distinct from new.set_hash or old.created_at is distinct from new.created_at then raise sqlstate 'PT409' using message='Summary sets are immutable'; end if;
 if old.closure_status<>new.closure_status and not (old.closure_status in ('registered','blocked') and new.closure_status='invalidated' and new.invalidated_at is not null) then raise sqlstate 'PT409' using message='Summary set status is immutable'; end if;
 if old.closure_status=new.closure_status and old.invalidated_at is distinct from new.invalidated_at then raise sqlstate 'PT409' using message='Summary set status is immutable'; end if;
 return new;
end $f$;
create function private.world_npc_memory_summary_child_guard() returns trigger language plpgsql security definer set search_path='' as $f$
begin if pg_trigger_depth()>1 then return old; end if; raise sqlstate 'PT409' using message='Summary leaves and batches are append-only'; end $f$;
create trigger world_npc_memory_summary_sets_guard before update or delete on private.world_npc_memory_summary_sets for each row execute function private.world_npc_memory_summary_set_guard();
create trigger world_npc_memory_summary_leaves_guard before update or delete on private.world_npc_memory_summary_leaves for each row execute function private.world_npc_memory_summary_child_guard();
create trigger world_npc_memory_summary_batches_guard before update or delete on private.world_npc_memory_summary_batches for each row execute function private.world_npc_memory_summary_child_guard();
create function private.world_npc_memory_summary_hash(p_kind text,p_version bigint,p_closure text,p_cutoff bigint,p_disclosure text,p_leaves jsonb) returns text language sql immutable security definer set search_path='' as $f$
 select encode(extensions.digest(convert_to(jsonb_build_object('summaryKind',p_kind,'setVersion',p_version,'closureKey',p_closure,'cutoffLedgerSequence',p_cutoff,'disclosureClass',p_disclosure,'leaves',p_leaves)::text,'utf8'),'sha256'),'hex')
$f$;
create or replace function private.world_npc_memory_summary_validate(p_set_id uuid) returns void language plpgsql security definer set search_path='' as $f$
declare s private.world_npc_memory_summary_sets; expected text; n integer; batches integer;
begin
 select * into s from private.world_npc_memory_summary_sets where id=p_set_id for update; if not found or s.closure_status='invalidated' then raise sqlstate 'PT409' using message='Summary set is unavailable'; end if;
 select count(*) into n from private.world_npc_memory_summary_leaves where set_id=s.id;
 if n=0 or exists(select 1 from generate_series(0,n-1) g(i) left join private.world_npc_memory_summary_leaves l on l.set_id=s.id and l.ordinal=g.i where l.ordinal is null) then raise sqlstate 'PT409' using message='Summary leaves are incomplete'; end if;
 if exists(select 1 from private.world_npc_memory_summary_leaves l left join private.world_npc_memory_sources x on x.source_kind=l.source_kind and x.source_id=l.source_id and x.source_version=l.source_version where l.set_id=s.id and (x.source_id is null or x.source_hash<>l.source_hash or x.ledger_sequence<>l.ledger_sequence or x.instance_id<>s.instance_id or x.save_id<>s.save_id or x.disclosure_class<>s.disclosure_class or x.ledger_sequence>s.cutoff_ledger_sequence)) then raise sqlstate 'PT409' using message='Summary leaf changed'; end if;
 select count(*) into batches from private.world_npc_memory_summary_batches where set_id=s.id;
 if batches=0 or exists(select 1 from generate_series(0,batches-1) g(i) left join private.world_npc_memory_summary_batches b on b.set_id=s.id and b.batch_ordinal=g.i where b.batch_ordinal is null) or exists(select 1 from generate_series(0,n-1) g(i) left join private.world_npc_memory_summary_batches b on b.set_id=s.id and g.i between b.first_leaf_ordinal and b.last_leaf_ordinal group by g.i having count(b.set_id)<>1) then raise sqlstate 'PT409' using message='Summary batches are incomplete'; end if;
 select private.world_npc_memory_summary_hash(s.summary_kind,s.set_version,s.closure_key,s.cutoff_ledger_sequence,s.disclosure_class,coalesce(jsonb_agg(jsonb_build_object('ordinal',ordinal,'sourceKind',source_kind,'sourceId',source_id,'sourceVersion',source_version,'sourceHash',source_hash,'ledgerSequence',ledger_sequence) order by ordinal),'[]'::jsonb)) into expected from private.world_npc_memory_summary_leaves where set_id=s.id;
 if expected<>s.set_hash then raise sqlstate 'PT409' using message='Summary set hash changed'; end if;
end $f$;
create function private.world_npc_memory_register_summary_set(p_summary_kind text,p_closure_key text,p_cutoff_ledger_sequence bigint,p_disclosure_class text,p_leaves jsonb,p_batches jsonb,p_processor_version text default 'npc-memory-v1') returns private.world_npc_memory_summary_sets language plpgsql security definer set search_path='' as $f$
declare first_leaf jsonb; source_row private.world_npc_memory_sources; s private.world_npc_memory_summary_sets; normalized jsonb; expected text; n integer; b integer;
begin
 if p_summary_kind not in ('episode_summary','quest_summary') or p_disclosure_class not in ('player_visible','npc_known','npc_private') or p_cutoff_ledger_sequence<0 or jsonb_typeof(p_leaves)<>'array' or jsonb_typeof(p_batches)<>'array' or jsonb_array_length(p_leaves) not between 1 and 512 or jsonb_array_length(p_batches) not between 1 and 64 then raise sqlstate 'PT400' using message='Summary set input is invalid'; end if;
 select value into first_leaf from jsonb_array_elements(p_leaves) limit 1;
 if coalesce(first_leaf->>'sourceKind','')='memory_set' then raise sqlstate 'PT400' using message='Summary sets cannot be recursive'; end if;
 select x.* into source_row from private.world_npc_memory_sources x where x.source_kind=first_leaf->>'sourceKind' and x.source_id=(first_leaf->>'sourceId')::uuid and x.source_version=(first_leaf->>'sourceVersion')::bigint;
 if not found then raise sqlstate 'PT409' using message='Summary leaf changed'; end if;
 select coalesce(jsonb_agg(jsonb_build_object('ordinal',e.ordinal,'sourceKind',x.source_kind,'sourceId',x.source_id,'sourceVersion',x.source_version,'sourceHash',x.source_hash,'ledgerSequence',x.ledger_sequence) order by e.ordinal),'[]'::jsonb) into normalized from jsonb_to_recordset(p_leaves) as e(ordinal integer, "sourceKind" text, "sourceId" text, "sourceVersion" bigint) join private.world_npc_memory_sources x on x.source_kind=e."sourceKind" and x.source_id=e."sourceId"::uuid and x.source_version=e."sourceVersion" where x.instance_id=source_row.instance_id and x.save_id=source_row.save_id and x.disclosure_class=p_disclosure_class and x.ledger_sequence<=p_cutoff_ledger_sequence;
 if jsonb_array_length(normalized)<>jsonb_array_length(p_leaves) or exists(select 1 from jsonb_array_elements(p_leaves) z where z ? 'sourceHash' or z ? 'ledgerSequence') then raise sqlstate 'PT409' using message='Summary leaf changed'; end if;
 select count(*) into n from jsonb_array_elements(normalized); if (select count(distinct ordinal) from jsonb_to_recordset(normalized) q(ordinal integer))<>n or exists(select 1 from generate_series(0,n-1) g(i) left join jsonb_to_recordset(normalized) q(ordinal integer) on q.ordinal=g.i where q.ordinal is null) then raise sqlstate 'PT400' using message='Summary leaf order is invalid'; end if;
 select count(*) into b from jsonb_array_elements(p_batches); if exists(select 1 from generate_series(0,b-1) g(i) left join jsonb_to_recordset(p_batches) q("batchOrdinal" integer,"firstLeafOrdinal" integer,"lastLeafOrdinal" integer,"leafCount" integer) on q."batchOrdinal"=g.i where q."batchOrdinal" is null) or exists(select 1 from jsonb_to_recordset(p_batches) q("batchOrdinal" integer,"firstLeafOrdinal" integer,"lastLeafOrdinal" integer,"leafCount" integer) where q."batchOrdinal"<0 or q."firstLeafOrdinal"<0 or q."lastLeafOrdinal"<q."firstLeafOrdinal" or q."lastLeafOrdinal">=n or q."leafCount" not between 1 and 64 or q."lastLeafOrdinal"-q."firstLeafOrdinal"+1<>q."leafCount") or exists(select 1 from generate_series(0,n-1) g(i) left join jsonb_to_recordset(p_batches) q("firstLeafOrdinal" integer,"lastLeafOrdinal" integer) on g.i between q."firstLeafOrdinal" and q."lastLeafOrdinal" group by g.i having count(q."firstLeafOrdinal")<>1) then raise sqlstate 'PT400' using message='Summary batch coverage is invalid'; end if;
 expected:=private.world_npc_memory_summary_hash(p_summary_kind,1,p_closure_key,p_cutoff_ledger_sequence,p_disclosure_class,normalized);
 insert into private.world_npc_memory_summary_sets(save_id,instance_id,summary_kind,closure_key,disclosure_class,cutoff_ledger_sequence,set_hash) values(source_row.save_id,source_row.instance_id,p_summary_kind,p_closure_key,p_disclosure_class,p_cutoff_ledger_sequence,expected) on conflict(instance_id,summary_kind,closure_key,disclosure_class,set_version) do nothing returning * into s;
 if not found then select * into s from private.world_npc_memory_summary_sets where instance_id=source_row.instance_id and summary_kind=p_summary_kind and closure_key=p_closure_key and disclosure_class=p_disclosure_class and set_version=1 for update; if s.set_hash<>expected or s.cutoff_ledger_sequence<>p_cutoff_ledger_sequence then raise sqlstate 'PT409' using message='Summary set identity changed'; end if; return s; end if;
 insert into private.world_npc_memory_summary_leaves(set_id,ordinal,source_kind,source_id,source_version,source_hash,ledger_sequence) select s.id,q.ordinal,q."sourceKind",q."sourceId"::uuid,q."sourceVersion",q."sourceHash",q."ledgerSequence" from jsonb_to_recordset(normalized) q(ordinal integer,"sourceKind" text,"sourceId" text,"sourceVersion" bigint,"sourceHash" text,"ledgerSequence" bigint);
 insert into private.world_npc_memory_summary_batches(set_id,batch_ordinal,first_leaf_ordinal,last_leaf_ordinal,leaf_count) select s.id,q."batchOrdinal",q."firstLeafOrdinal",q."lastLeafOrdinal",q."leafCount" from jsonb_to_recordset(p_batches) q("batchOrdinal" integer,"firstLeafOrdinal" integer,"lastLeafOrdinal" integer,"leafCount" integer);
 perform private.world_npc_memory_summary_validate(s.id);
 insert into private.world_npc_memory_outbox(save_id,instance_id,source_kind,source_id,source_version,source_sequence,source_hash,processor_kind,processor_version) values(s.save_id,s.instance_id,'memory_set',s.id,s.set_version,s.cutoff_ledger_sequence,s.set_hash,'summary',p_processor_version) on conflict(source_kind,source_id,source_version,processor_kind,processor_version) do nothing;
 return s;
end $f$;
alter table private.world_npc_memory_outbox drop constraint world_npc_memory_outbox_source_kind_check;
alter table private.world_npc_memory_outbox add constraint world_npc_memory_outbox_source_kind_check check(source_kind in ('dialogue_turn','quest_event','hospitality','resident_evolution','memory_set'));
alter table private.world_npc_memory_outbox add constraint world_npc_memory_outbox_summary_source_check check((source_kind='memory_set')=(processor_kind='summary'));
create or replace function private.world_npc_memory_invalidate_instance() returns trigger language plpgsql security definer set search_path='' as $f$
begin
  insert into private.world_npc_memory_invalidations(job_id,save_id,instance_id,fence,source_kind,source_id,source_version,reason)
  select job.id,job.save_id,job.instance_id,job.fence,job.source_kind,job.source_id,job.source_version,'resident_removed' from private.world_npc_memory_outbox job where job.instance_id=old.id and job.status='processing' on conflict(job_id) do nothing;
  return old;
end $f$;
create or replace function private.world_npc_memory_complete(p_job_id uuid,p_fence uuid,p_artifacts jsonb default '[]'::jsonb,p_error_code text default null)
returns void language plpgsql security definer set search_path='' as $f$
declare job private.world_npc_memory_outbox; source_row private.world_npc_memory_sources; set_row private.world_npc_memory_summary_sets; artifact jsonb; live_hash text;
begin
 if exists(select 1 from private.world_npc_memory_invalidations i where i.job_id=p_job_id and i.fence=p_fence) then raise sqlstate 'PT409' using message='Memory work fence is stale'; end if;
 select * into job from private.world_npc_memory_outbox where id=p_job_id for update;
 if not found or job.fence<>p_fence or job.status<>'processing' or job.lease_until<=clock_timestamp() then raise sqlstate 'PT409' using message='Memory work fence is stale'; end if;
 if job.source_kind='memory_set' then
   select * into set_row from private.world_npc_memory_summary_sets where id=job.source_id for update;
   if not found or set_row.save_id<>job.save_id or set_row.instance_id<>job.instance_id or set_row.set_version<>job.source_version or set_row.set_hash<>job.source_hash or set_row.cutoff_ledger_sequence<>job.source_sequence then raise sqlstate 'PT409' using message='Summary set changed or is unavailable'; end if;
   perform private.world_npc_memory_summary_validate(set_row.id);
   if p_error_code is null and (jsonb_typeof(coalesce(p_artifacts,'[]'::jsonb))<>'array' or jsonb_array_length(coalesce(p_artifacts,'[]'::jsonb))<>0) then raise sqlstate 'PT400' using message='Summary artifacts are not accepted by this contract'; end if;
   update private.world_npc_memory_outbox set status=case when p_error_code is null then 'completed' else 'failed' end,examined_at=clock_timestamp(),completed_at=case when p_error_code is null then clock_timestamp() else null end,error_code=case when p_error_code is null then null else left(p_error_code,120) end,lease_until=null where id=job.id;
   perform private.world_npc_memory_refresh_watermark(job.instance_id,job.processor_kind,job.processor_version); return;
 end if;
 select * into source_row from private.world_npc_memory_sources where source_kind=job.source_kind and source_id=job.source_id and source_version=job.source_version;
 if not found and job.source_kind='dialogue_turn' then source_row:=private.world_npc_memory_register_source(job.source_kind,job.source_id); update private.world_npc_memory_outbox set source_sequence=source_row.ledger_sequence,source_hash=source_row.source_hash where id=job.id; select * into job from private.world_npc_memory_outbox where id=job.id; end if;
 if not found or source_row.save_id<>job.save_id or source_row.instance_id<>job.instance_id or source_row.source_hash<>job.source_hash or source_row.ledger_sequence<>job.source_sequence then raise sqlstate 'PT409' using message='Memory source changed or is unavailable'; end if;
 live_hash:=private.world_npc_memory_source_hash(job.source_kind,job.source_id); if live_hash<>source_row.source_hash then raise sqlstate 'PT409' using message='Memory source changed or is unavailable'; end if;
 if p_error_code is not null then update private.world_npc_memory_outbox set status='failed',examined_at=clock_timestamp(),error_code=left(p_error_code,120),lease_until=null where id=job.id; perform private.world_npc_memory_refresh_watermark(job.instance_id,job.processor_kind,job.processor_version); return; end if;
 if jsonb_typeof(coalesce(p_artifacts,'[]'::jsonb))<>'array' then raise sqlstate 'PT400' using message='Memory artifacts are invalid'; end if;
 for artifact in select value from jsonb_array_elements(coalesce(p_artifacts,'[]'::jsonb)) loop
   if artifact->>'artifactKind' not in ('episode_summary','quest_summary','embedding') or coalesce(artifact->>'sourceKind',job.source_kind)<>job.source_kind or coalesce(artifact->>'contentHash','') !~ '^[0-9a-f]{64}$' or coalesce(artifact->>'disclosureClass',source_row.disclosure_class)<>source_row.disclosure_class then raise sqlstate 'PT400' using message='Memory artifact does not match its source contract'; end if;
   insert into private.world_npc_memory_artifacts(save_id,instance_id,artifact_kind,source_kind,source_ids,source_versions,source_hash,processor_version,model,contract_hash,disclosure_class,content,content_hash,embedding,embedding_dimensions) values(job.save_id,job.instance_id,artifact->>'artifactKind',job.source_kind,array[job.source_id],array[job.source_version],job.source_hash,job.processor_version,artifact->>'model',artifact->>'contractHash',source_row.disclosure_class,coalesce(artifact->'content','{}'::jsonb),artifact->>'contentHash',nullif(artifact->>'embedding','')::extensions.vector,nullif(artifact->>'embeddingDimensions','')::integer) on conflict(instance_id,artifact_kind,source_hash,processor_version) do nothing;
 end loop;
 update private.world_npc_memory_outbox set status='completed',examined_at=clock_timestamp(),completed_at=clock_timestamp(),lease_until=null where id=job.id; perform private.world_npc_memory_refresh_watermark(job.instance_id,job.processor_kind,job.processor_version);
end $f$;
revoke all on table private.world_npc_memory_summary_sets,private.world_npc_memory_summary_leaves,private.world_npc_memory_summary_batches from public,anon,authenticated,service_role;
revoke all on function private.world_npc_memory_summary_set_guard(),private.world_npc_memory_summary_child_guard(),private.world_npc_memory_summary_hash(text,bigint,text,bigint,text,jsonb),private.world_npc_memory_summary_validate(uuid),private.world_npc_memory_register_summary_set(text,text,bigint,text,jsonb,jsonb,text) from public,anon,authenticated,service_role;
commit;
