begin;
alter table private.world_npc_memory_artifacts add column generation_manifest jsonb;
alter table private.world_npc_memory_artifacts drop constraint if exists world_npc_memory_summary_artifact_shape;
alter table private.world_npc_memory_artifacts add constraint world_npc_memory_summary_artifact_shape check(source_kind<>'memory_set' or (
 cardinality(source_ids)=1 and cardinality(source_versions)=1 and prompt_release_id is not null and prompt_revision_id is not null and embedding is null and embedding_dimensions is null and
 ((processor_version='npc-memory-v1' and prompt_key='npc_memory.summary' and contract_id='npc-memory-summary-v1' and contract_hash='2a28c283d9fada5bc5e8b501356b6fc423305fb7cd6e5b1c1e686b038e45745e' and generation_manifest is null and ((model is not null and fallback is null) or (model is null and fallback='extractive-v1')))
  or (processor_version='npc-memory-summary-v2' and prompt_key='npc_memory.summary.v2' and contract_id='npc-memory-summary-v2' and contract_hash='f279a108f11e212c77e4876521e9ee47092171b6d2a820d83a245d57a3c64e03' and generation_manifest is not null and ((model is not null and fallback is null) or (model is null and fallback='extractive-v2')))
 )));

create or replace function private.world_npc_memory_summary_v2_content_valid(p_content jsonb,p_set_id uuid) returns boolean language plpgsql security definer set search_path='' as $f$
declare c jsonb; l jsonb; prev_leaf integer:=-1; prev_record uuid:=null; last_leaf integer:=-1;
begin
 if p_content is null or p_set_id is null or jsonb_typeof(p_content)<>'object' or octet_length(private.world_canonical_json(p_content))>32768 or not private.world_json_keys_exact(p_content,array['version','mode','summary','citations','protectedRefs','leaves','batches']) or jsonb_typeof(p_content->'version')<>'string' or jsonb_typeof(p_content->'mode')<>'string' or p_content->>'version'<>'npc-memory-summary-v2' or p_content->>'mode' not in ('model','extractive-v2') or jsonb_typeof(p_content->'summary')<>'string' or char_length(btrim(p_content->>'summary')) not between 1 and 12000 or jsonb_typeof(p_content->'citations')<>'array' or jsonb_typeof(p_content->'protectedRefs')<>'array' or jsonb_typeof(p_content->'leaves')<>'array' or jsonb_typeof(p_content->'batches')<>'array' or jsonb_array_length(p_content->'citations')>128 then return false; end if;
 select coalesce(jsonb_agg(jsonb_build_object('ordinal',ordinal,'sourceKind',source_kind,'sourceId',source_id,'sourceVersion',source_version,'sourceHash',source_hash,'ledgerSequence',ledger_sequence) order by ordinal),'[]'::jsonb) into l from private.world_npc_memory_summary_leaves where set_id=p_set_id;
 if p_content->'leaves'<>l or p_content->'protectedRefs'<>l then return false; end if;
 select coalesce(jsonb_agg(jsonb_build_object('ordinal',batch_ordinal,'firstLeafOrdinal',first_leaf_ordinal,'lastLeafOrdinal',last_leaf_ordinal,'leafCount',leaf_count) order by batch_ordinal),'[]'::jsonb) into l from private.world_npc_memory_summary_batches where set_id=p_set_id;
 if p_content->'batches'<>l then return false; end if;
 for c in select value from jsonb_array_elements(p_content->'citations') loop
  if jsonb_typeof(c)<>'object' or not private.world_json_keys_exact(c,array['leafOrdinal','recordId','speaker','quote','sourceKind','sourceId','sourceVersion','sourceHash']) or coalesce(c->>'leafOrdinal','') !~ '^(0|[1-9][0-9]*)$' or coalesce(c->>'recordId','') !~ '^[0-9a-fA-F-]{36}$' or coalesce(c->>'sourceId','') !~ '^[0-9a-fA-F-]{36}$' or coalesce(c->>'sourceVersion','') !~ '^(0|[1-9][0-9]*)$' or coalesce(c->>'sourceHash','') !~ '^[0-9a-f]{64}$' or jsonb_typeof(c->'speaker')<>'string' or jsonb_typeof(c->'quote')<>'string' or char_length(btrim(c->>'quote'))=0 or char_length(c->>'quote')>12000 or (c->>'leafOrdinal')::integer<prev_leaf or ((c->>'leafOrdinal')::integer=prev_leaf and prev_record is not null and (c->>'recordId')::uuid<=prev_record) then return false; end if;
  if not exists(select 1 from private.world_npc_memory_summary_leaves sl join private.world_npc_memory_summary_sets s on s.id=sl.set_id join private.world_npc_memories m on m.id=(c->>'recordId')::uuid where sl.set_id=p_set_id and sl.ordinal=(c->>'leafOrdinal')::integer and s.instance_id=m.instance_id and s.save_id=m.save_id and s.disclosure_class=m.disclosure_class and m.source_kind=sl.source_kind and m.source_id=sl.source_id and m.source_version=sl.source_version and m.source_hash=sl.source_hash and m.speaker=c->>'speaker' and c->>'sourceKind'=m.source_kind and (c->>'sourceId')::uuid=m.source_id and (c->>'sourceVersion')::bigint=m.source_version and c->>'sourceHash'=m.source_hash and (c->>'quote'=m.quote or position(c->>'quote' in m.text)>0)) then return false; end if;
  prev_leaf:=(c->>'leafOrdinal')::integer; prev_record:=(c->>'recordId')::uuid;
 end loop; return true;
exception when others then return false; end $f$;

-- This deterministic reconstruction deliberately accepts a completed job.
-- Public loading stays processing-only; replay never depends on that API.
create function private.world_npc_memory_summary_v2_request_hash(p_job_id uuid,p_fence uuid,p_batch_ordinal integer) returns text language plpgsql security definer set search_path='' as $f$
declare j private.world_npc_memory_outbox; s private.world_npc_memory_summary_sets; b private.world_npc_memory_summary_batches; v uuid; payload jsonb;
begin
 select * into j from private.world_npc_memory_outbox where id=p_job_id for update;
 if not found or p_fence is null or j.source_kind<>'memory_set' or j.processor_kind<>'summary' or j.processor_version<>'npc-memory-summary-v2' or j.summary_protocol<>'v2' or j.summary_prompt_key<>'npc_memory.summary.v2' or j.status not in ('processing','completed') then raise sqlstate 'PT409' using message='Summary receipt request is stale'; end if;
 select * into s from private.world_npc_memory_summary_sets where id=j.source_id for update;
 if not found or s.closure_status='invalidated' or s.save_id<>j.save_id or s.instance_id<>j.instance_id or s.set_version<>j.source_version or s.set_hash<>j.source_hash or s.cutoff_ledger_sequence<>j.source_sequence then raise sqlstate 'PT409' using message='Summary receipt source changed'; end if;
 select * into b from private.world_npc_memory_summary_batches where set_id=s.id and batch_ordinal=p_batch_ordinal;
 if not found then raise sqlstate 'PT409' using message='Summary receipt batch is unavailable'; end if;
 select e.revision_id into v from private.prompt_release_entries e join private.prompt_revisions pr on pr.id=e.revision_id where e.release_id=j.prompt_release_id and e.prompt_key='npc_memory.summary.v2' and pr.prompt_key='npc_memory.summary.v2' and pr.contract_id='npc-memory-summary-v2' and pr.contract_hash='f279a108f11e212c77e4876521e9ee47092171b6d2a820d83a245d57a3c64e03';
 if v is null then raise sqlstate 'PT409' using message='Summary receipt prompt pin is invalid'; end if;
 perform private.world_npc_memory_summary_validate(s.id);
 payload:=jsonb_build_object('jobId',j.id,'fence',p_fence,'promptReleaseId',j.prompt_release_id,'promptKey','npc_memory.summary.v2','promptRevisionId',v,'set',jsonb_build_object('id',s.id,'summaryKind',s.summary_kind,'setVersion',s.set_version,'setHash',s.set_hash,'cutoffLedgerSequence',s.cutoff_ledger_sequence,'disclosureClass',s.disclosure_class),'batch',jsonb_build_object('ordinal',b.batch_ordinal,'firstLeafOrdinal',b.first_leaf_ordinal,'lastLeafOrdinal',b.last_leaf_ordinal,'leafCount',b.leaf_count),'leaves',coalesce((select jsonb_agg(jsonb_build_object('ordinal',l.ordinal,'sourceKind',l.source_kind,'sourceId',l.source_id,'sourceVersion',l.source_version,'sourceHash',l.source_hash,'ledgerSequence',l.ledger_sequence,'envelope',x.envelope,'records',coalesce((select jsonb_agg(jsonb_build_object('id',m.id,'recordRootId',m.record_root_id,'recordVersion',m.record_version,'kind',m.kind,'text',m.text,'quote',m.quote,'speaker',m.speaker,'truthClass',m.truth_class,'commitmentStatus',m.commitment_status,'correctionMemoryId',m.correction_memory_id,'relatedQuestId',m.related_quest_id,'occurredDay',m.occurred_day,'occurredSequence',m.occurred_sequence,'sourceKind',m.source_kind,'sourceId',m.source_id,'sourceVersion',m.source_version,'sourceHash',m.source_hash,'disclosureClass',m.disclosure_class) order by m.record_root_id,m.record_version,m.id) from private.world_npc_memories m where m.instance_id=s.instance_id and m.disclosure_class=s.disclosure_class and m.source_kind=l.source_kind and m.source_id=l.source_id and m.source_version=l.source_version and m.source_hash=l.source_hash),'[]'::jsonb)) order by l.ordinal) from private.world_npc_memory_summary_leaves l join private.world_npc_memory_sources x on x.source_kind=l.source_kind and x.source_id=l.source_id and x.source_version=l.source_version and x.source_hash=l.source_hash and x.disclosure_class=s.disclosure_class where l.set_id=s.id and l.ordinal between b.first_leaf_ordinal and b.last_leaf_ordinal),'[]'::jsonb));
 return encode(extensions.digest(private.world_canonical_json(payload),'sha256'),'hex');
end $f$;

create function private.world_npc_memory_summary_v2_fallback_units(p_set_id uuid) returns jsonb language sql stable security definer set search_path='' as $f$
 with units as (
   select l.ordinal,m.record_root_id,m.record_version,m.id,m.speaker||': '||coalesce(nullif(m.quote,''),m.text) unit
   from private.world_npc_memory_summary_leaves l join private.world_npc_memory_summary_sets s on s.id=l.set_id join private.world_npc_memories m on m.instance_id=s.instance_id and m.disclosure_class=s.disclosure_class and m.source_kind=l.source_kind and m.source_id=l.source_id and m.source_version=l.source_version and m.source_hash=l.source_hash where l.set_id=p_set_id
 ), sized as (
   select *,octet_length(unit) unit_bytes,row_number() over(order by ordinal,record_root_id,record_version,id) rn from units
 ), bounded as (
   select *,sum(unit_bytes+case when rn=1 then 0 else 1 end) over(order by ordinal,record_root_id,record_version,id) running_bytes from sized
 ) select jsonb_build_object('summary',coalesce(string_agg(unit,E'\n' order by ordinal,record_root_id,record_version,id) filter(where running_bytes<=12000),'Extractive fallback: no authorized record units.'),'includedUnitCount',count(*) filter(where running_bytes<=12000),'omittedUnitCount',count(*) filter(where running_bytes>12000),'includedUnitBytes',coalesce(sum(unit_bytes+case when rn=1 then 0 else 1 end) filter(where running_bytes<=12000),0),'omittedUnitBytes',coalesce(sum(unit_bytes+case when rn=1 then 0 else 1 end) filter(where running_bytes>12000),0),'byteCap',12000) from bounded
$f$;

-- Select only whole, ordered record units.  The fit test is against the
-- complete canonical artifact, including the duplicated immutable manifests.
create function private.world_npc_memory_summary_v2_fallback_plan(p_set_id uuid,p_leaves jsonb,p_batches jsonb) returns jsonb language sql stable security definer set search_path='' as $f$
 with units as (
   select l.ordinal,m.record_root_id,m.record_version,m.id,m.speaker||': '||coalesce(nullif(m.quote,''),m.text) unit
   from private.world_npc_memory_summary_leaves l join private.world_npc_memory_summary_sets s on s.id=l.set_id join private.world_npc_memories m on m.instance_id=s.instance_id and m.disclosure_class=s.disclosure_class and m.source_kind=l.source_kind and m.source_id=l.source_id and m.source_version=l.source_version and m.source_hash=l.source_hash where l.set_id=p_set_id
 ), prefixes as (
   select row_number() over(order by ordinal,record_root_id,record_version,id) included,string_agg(unit,E'\n') over(order by ordinal,record_root_id,record_version,id rows between unbounded preceding and current row) summary from units
 ), candidates as (
   select included,summary from prefixes where char_length(btrim(summary)) between 1 and 12000 and octet_length(private.world_canonical_json(jsonb_build_object('version','npc-memory-summary-v2','mode','extractive-v2','summary',summary,'citations','[]'::jsonb,'protectedRefs',p_leaves,'leaves',p_leaves,'batches',p_batches)))<=32768
 ), chosen as (
   select included,summary from candidates union all select 0::bigint,'Extractive fallback: no authorized record units.'::text
 ), pick as (
   select included,summary from chosen order by included desc limit 1
 ), total as (select count(*) n from units), final_content as (
   select p.included,p.summary,t.n,jsonb_build_object('version','npc-memory-summary-v2','mode','extractive-v2','summary',p.summary,'citations','[]'::jsonb,'protectedRefs',p_leaves,'leaves',p_leaves,'batches',p_batches) content from pick p cross join total t
 ) select jsonb_build_object('summary',summary,'includedUnitCount',included,'omittedUnitCount',n-included,'canonicalContentBytes',octet_length(private.world_canonical_json(content)),'byteCap',32768,'fits',octet_length(private.world_canonical_json(content))<=32768) from final_content
$f$;

create or replace function private.world_npc_memory_summary_v2_received_valid(p_result jsonb,p_set_id uuid,p_batch integer) returns boolean language plpgsql security definer set search_path='' as $f$
declare n integer; max_summary integer;
begin select count(*) into n from private.world_npc_memory_summary_batches where set_id=p_set_id; max_summary:=floor((12000-2*(n-1))/n);
 return coalesce(n>0 and max_summary>0 and jsonb_typeof(p_result)='object' and jsonb_typeof(p_result->'citations')='array' and private.world_json_keys_exact(p_result,array['version','mode','summary','citations','protectedRefs','leaves']) and p_result->>'version'='npc-memory-summary-v2' and p_result->>'mode'='model' and jsonb_typeof(p_result->'summary')='string' and char_length(btrim(p_result->>'summary')) between 1 and max_summary and jsonb_array_length(p_result->'citations')<=floor(128/n) and private.world_npc_memory_summary_v2_batch_result_valid(p_result-'summary',p_set_id,p_batch),false);
exception when others then return false; end $f$;

alter function private.world_npc_memory_complete(uuid,uuid,jsonb,text) rename to world_npc_memory_complete_094;
create function private.world_npc_memory_complete(p_job_id uuid,p_fence uuid,p_artifacts jsonb default '[]'::jsonb,p_error_code text default null) returns void language plpgsql security definer set search_path='' as $f$
declare j private.world_npc_memory_outbox;
begin select * into j from private.world_npc_memory_outbox where id=p_job_id; if j.summary_protocol='v2' then raise sqlstate 'PT400' using message='V2 summaries require database finalization'; end if; perform private.world_npc_memory_complete_094(p_job_id,p_fence,p_artifacts,p_error_code); end $f$;

create function public.world_npc_memory_summary_finalize_v2(p_job_id uuid,p_fence uuid) returns jsonb language plpgsql security definer set search_path='' as $f$
declare j private.world_npc_memory_outbox; s private.world_npc_memory_summary_sets; n integer; r record; assembled text:=''; cites jsonb:='[]'; leaves jsonb; batches jsonb; content jsonb; manifest jsonb; fallback_units jsonb; model_name text; fallback boolean:=false; v uuid; h text; existing private.world_npc_memory_artifacts; unit text; identity jsonb; request_payload jsonb; receipt_ok boolean:=true;
begin
 perform private.world_settlement_assert_service(); select * into j from private.world_npc_memory_outbox where id=p_job_id for update;
 if not found or j.source_kind<>'memory_set' or j.processor_kind<>'summary' or j.processor_version<>'npc-memory-summary-v2' or j.summary_protocol<>'v2' or j.summary_prompt_key<>'npc_memory.summary.v2' or j.fence<>p_fence or exists(select 1 from private.world_npc_memory_invalidations where job_id=j.id and fence=p_fence) or (j.status='processing' and j.lease_until<=clock_timestamp()) or j.status not in ('processing','completed') then raise sqlstate 'PT409' using message='Summary finalization fence is stale'; end if;
 select * into s from private.world_npc_memory_summary_sets where id=j.source_id for update; if not found or s.closure_status='invalidated' or s.save_id<>j.save_id or s.instance_id<>j.instance_id or s.set_hash<>j.source_hash or s.set_version<>j.source_version or s.cutoff_ledger_sequence<>j.source_sequence then raise sqlstate 'PT409' using message='Summary set changed or is unavailable'; end if; perform private.world_npc_memory_summary_validate(s.id);
 select count(*) into n from private.world_npc_memory_summary_batches where set_id=s.id; select e.revision_id into v from private.prompt_release_entries e join private.prompt_revisions pr on pr.id=e.revision_id where e.release_id=j.prompt_release_id and e.prompt_key='npc_memory.summary.v2' and pr.contract_id='npc-memory-summary-v2' and pr.contract_hash='f279a108f11e212c77e4876521e9ee47092171b6d2a820d83a245d57a3c64e03'; if v is null then raise sqlstate 'PT409' using message='Summary prompt pin is invalid'; end if; select jsonb_agg(jsonb_build_object('ordinal',ordinal,'sourceKind',source_kind,'sourceId',source_id,'sourceVersion',source_version,'sourceHash',source_hash,'ledgerSequence',ledger_sequence) order by ordinal) into leaves from private.world_npc_memory_summary_leaves where set_id=s.id; select jsonb_agg(jsonb_build_object('ordinal',batch_ordinal,'firstLeafOrdinal',first_leaf_ordinal,'lastLeafOrdinal',last_leaf_ordinal,'leafCount',leaf_count) order by batch_ordinal) into batches from private.world_npc_memory_summary_batches where set_id=s.id;
 if n=0 or exists(select 1 from private.world_npc_memory_summary_dispatches d where d.job_id=j.id and not exists(select 1 from private.world_npc_memory_summary_batches b where b.set_id=s.id and b.batch_ordinal=d.batch_ordinal)) or (select count(*) from private.world_npc_memory_summary_dispatches where job_id=j.id)<>n or exists(select 1 from private.world_npc_memory_summary_batches b left join private.world_npc_memory_summary_dispatches d on d.job_id=j.id and d.batch_ordinal=b.batch_ordinal where b.set_id=s.id and d.job_id is null) then fallback:=true; end if;
 if not fallback then for r in select d.* from private.world_npc_memory_summary_batches b join private.world_npc_memory_summary_dispatches d on d.job_id=j.id and d.batch_ordinal=b.batch_ordinal where b.set_id=s.id order by b.batch_ordinal loop
   identity:=jsonb_build_object('jobId',j.id,'fence',r.fence,'batchOrdinal',r.batch_ordinal,'sourceHash',j.source_hash,'sourceVersion',j.source_version,'processorVersion',j.processor_version,'promptReleaseId',j.prompt_release_id,'summaryProtocol','v2','summaryPromptKey','npc_memory.summary.v2');
   if r.state<>'received' or r.fence is null or char_length(btrim(coalesce(r.model,''))) not between 1 and 120 or (r.provider_request_id is not null and char_length(r.provider_request_id)>200) or not private.world_npc_memory_summary_v2_received_valid(r.result,s.id,r.batch_ordinal) or r.result_hash<>encode(extensions.digest(private.world_canonical_json(r.result),'sha256'),'hex') or r.identity_hash<>encode(extensions.digest(private.world_canonical_json(identity),'sha256'),'hex') or r.request_hash<>private.world_npc_memory_summary_v2_request_hash(j.id,r.fence,r.batch_ordinal) or (model_name is not null and model_name<>r.model) then fallback:=true; exit; end if; model_name:=coalesce(model_name,r.model);
 end loop; end if;
 if not fallback then for r in select * from private.world_npc_memory_summary_dispatches where job_id=j.id order by batch_ordinal loop
   if model_name is null then model_name:=r.model; end if;
   assembled:=assembled||case when assembled='' then '' else E'\n\n' end||(r.result->>'summary'); cites:=cites||coalesce(r.result->'citations','[]'::jsonb);
  end loop; if not fallback then manifest:=jsonb_build_object('version','v2-receipts-1','mode','model','batches',(select jsonb_agg(jsonb_build_object('batchOrdinal',batch_ordinal,'fence',fence,'resultHash',result_hash,'model',model,'providerRequestId',provider_request_id,'identityHash',identity_hash,'requestHash',request_hash) order by batch_ordinal) from private.world_npc_memory_summary_dispatches where job_id=j.id)); content:=jsonb_build_object('version','npc-memory-summary-v2','mode','model','summary',assembled,'citations',cites); end if;
 else fallback_units:=private.world_npc_memory_summary_v2_fallback_plan(s.id,leaves,batches); if coalesce((fallback_units->>'fits')::boolean,false) is not true then raise sqlstate 'PT413' using message='Summary fallback cannot fit immutable coverage'; end if; assembled:=fallback_units->>'summary'; manifest:=jsonb_build_object('version','v2-receipts-1','mode','extractive-v2','batches',(select jsonb_agg(jsonb_strip_nulls(jsonb_build_object('batchOrdinal',b.batch_ordinal,'state',coalesce(d.state,'missing'),'fence',d.fence,'resultHash',d.result_hash,'model',d.model,'providerRequestId',d.provider_request_id,'identityHash',d.identity_hash,'requestHash',d.request_hash)) order by b.batch_ordinal) from private.world_npc_memory_summary_batches b left join private.world_npc_memory_summary_dispatches d on d.job_id=j.id and d.batch_ordinal=b.batch_ordinal where b.set_id=s.id),'includedUnitCount',fallback_units->'includedUnitCount','omittedUnitCount',fallback_units->'omittedUnitCount','canonicalContentBytes',fallback_units->'canonicalContentBytes','byteCap',fallback_units->'byteCap'); content:=jsonb_build_object('version','npc-memory-summary-v2','mode','extractive-v2','summary',assembled,'citations','[]'::jsonb); end if;
 select jsonb_agg(jsonb_build_object('ordinal',ordinal,'sourceKind',source_kind,'sourceId',source_id,'sourceVersion',source_version,'sourceHash',source_hash,'ledgerSequence',ledger_sequence) order by ordinal) into leaves from private.world_npc_memory_summary_leaves where set_id=s.id; select jsonb_agg(jsonb_build_object('ordinal',batch_ordinal,'firstLeafOrdinal',first_leaf_ordinal,'lastLeafOrdinal',last_leaf_ordinal,'leafCount',leaf_count) order by batch_ordinal) into batches from private.world_npc_memory_summary_batches where set_id=s.id; content:=content||jsonb_build_object('protectedRefs',leaves,'leaves',leaves,'batches',batches);
 if not fallback and not private.world_npc_memory_summary_v2_content_valid(content,s.id) then fallback:=true; fallback_units:=private.world_npc_memory_summary_v2_fallback_plan(s.id,leaves,batches); if coalesce((fallback_units->>'fits')::boolean,false) is not true then raise sqlstate 'PT413' using message='Summary fallback cannot fit immutable coverage'; end if; assembled:=fallback_units->>'summary'; manifest:=jsonb_build_object('version','v2-receipts-1','mode','extractive-v2','reason','model_content_byte_cap','batches',(select jsonb_agg(jsonb_strip_nulls(jsonb_build_object('batchOrdinal',b.batch_ordinal,'state',coalesce(d.state,'missing'),'fence',d.fence,'resultHash',d.result_hash,'model',d.model,'providerRequestId',d.provider_request_id,'identityHash',d.identity_hash,'requestHash',d.request_hash)) order by b.batch_ordinal) from private.world_npc_memory_summary_batches b left join private.world_npc_memory_summary_dispatches d on d.job_id=j.id and d.batch_ordinal=b.batch_ordinal where b.set_id=s.id),'includedUnitCount',fallback_units->'includedUnitCount','omittedUnitCount',fallback_units->'omittedUnitCount','canonicalContentBytes',fallback_units->'canonicalContentBytes','byteCap',fallback_units->'byteCap'); content:=jsonb_build_object('version','npc-memory-summary-v2','mode','extractive-v2','summary',assembled,'citations','[]'::jsonb,'protectedRefs',leaves,'leaves',leaves,'batches',batches); end if; h:=encode(extensions.digest(private.world_canonical_json(content),'sha256'),'hex');
 if not private.world_npc_memory_summary_v2_content_valid(content,s.id) then raise sqlstate 'PT409' using message='Summary final content is invalid'; end if;
 insert into private.world_npc_memory_artifacts(save_id,instance_id,artifact_kind,source_kind,source_ids,source_versions,source_hash,processor_version,prompt_release_id,prompt_key,prompt_revision_id,model,contract_id,contract_hash,fallback,disclosure_class,content,content_hash,generation_manifest) values(j.save_id,j.instance_id,s.summary_kind,'memory_set',array[s.id],array[s.set_version],s.set_hash,j.processor_version,j.prompt_release_id,'npc_memory.summary.v2',v,case when fallback then null else model_name end,'npc-memory-summary-v2','f279a108f11e212c77e4876521e9ee47092171b6d2a820d83a245d57a3c64e03',case when fallback then 'extractive-v2' else null end,s.disclosure_class,content,h,manifest) on conflict(instance_id,artifact_kind,source_hash,processor_version) do nothing;
 select * into existing from private.world_npc_memory_artifacts where instance_id=j.instance_id and artifact_kind=s.summary_kind and source_hash=s.set_hash and processor_version=j.processor_version; if not found or existing.save_id<>j.save_id or existing.instance_id<>j.instance_id or existing.artifact_kind<>s.summary_kind or existing.source_kind<>'memory_set' or existing.source_ids<>array[s.id] or existing.source_versions<>array[s.set_version] or existing.source_hash<>s.set_hash or existing.processor_version<>j.processor_version or existing.prompt_release_id<>j.prompt_release_id or existing.prompt_key<>'npc_memory.summary.v2' or existing.prompt_revision_id<>v or existing.contract_id<>'npc-memory-summary-v2' or existing.contract_hash<>'f279a108f11e212c77e4876521e9ee47092171b6d2a820d83a245d57a3c64e03' or existing.disclosure_class<>s.disclosure_class or existing.content<>content or existing.content_hash<>h or existing.generation_manifest<>manifest or existing.model is distinct from (case when fallback then null else model_name end) or existing.fallback is distinct from (case when fallback then 'extractive-v2' else null end) or existing.embedding is not null or existing.embedding_dimensions is not null then raise sqlstate 'PT409' using message='Summary artifact replay conflicts'; end if;
 if j.status='processing' then update private.world_npc_memory_outbox set status='completed',examined_at=clock_timestamp(),completed_at=clock_timestamp(),lease_until=null where id=j.id; perform private.world_npc_memory_refresh_watermark(j.instance_id,j.processor_kind,j.processor_version); end if; return jsonb_build_object('status',case when j.status='completed' then 'reused' else 'completed' end,'fallback',fallback,'contentHash',h);
end; $f$;
revoke all on function private.world_npc_memory_complete(uuid,uuid,jsonb,text),private.world_npc_memory_complete_094(uuid,uuid,jsonb,text),private.world_npc_memory_summary_v2_content_valid(jsonb,uuid),private.world_npc_memory_summary_v2_received_valid(jsonb,uuid,integer),private.world_npc_memory_summary_v2_request_hash(uuid,uuid,integer),private.world_npc_memory_summary_v2_fallback_units(uuid),private.world_npc_memory_summary_v2_fallback_plan(uuid,jsonb,jsonb),public.world_npc_memory_summary_finalize_v2(uuid,uuid) from public,anon,authenticated;
grant execute on function public.world_npc_memory_summary_finalize_v2(uuid,uuid) to service_role;
commit;
