import { describe, expect, it, vi } from 'vitest';
import { normalizeNpcMemoryQuery, normalizeNpcMemoryRefs, retrieveNpcMemoryEvidence } from '$lib/server/npc-memory/retrieval';

const id='20300000-0000-4000-8000-000000000001', instance='20300000-0000-4000-8000-000000000002';
const input=()=>({actorId:id,instanceId:instance,view:'speech' as const,cutoffLedgerSequence:null,query:'  e\u0301  fox 🦊 ',knownRefs:[' Moonwell ','moonwell','🧑‍🚀'.repeat(130)],budget:{limit:12,candidateLimit:24,fallbackLimit:6},signal:new AbortController().signal});
const payload={retrievalVersion:'npc-memory-evidence-v4',cutoffLedgerSequence:-1,semantic:{available:false,availability:'disabled',profile:null},items:[],bundles:[],sourceFallback:[],sourceManifest:[],coverage:{complete:true,sourceFallback:{total:0,included:0,truncated:false,complete:true},watermarks:[]}};
const hash='a'.repeat(64), validItem={id,recordRootId:instance,recordVersion:1,kind:'promise',text:'evidence',quote:'quote',speaker:'npc',truthClass:'attributed',disclosureClass:'npc_known',status:null,relatedQuestId:null,correctionMemoryId:null,entityRefs:[],importance:1,occurredDay:1,occurredSequence:0,learnedDay:1,learnedSequence:0,sourceKind:'dialogue_turn',sourceId:id,sourceVersion:1,sourceHash:hash,ledgerSequence:0,channelRanks:{relational:1},fusedScore:1,selectionReasons:['important_recent']};
const validNested=()=>({retrievalVersion:'npc-memory-evidence-v4',cutoffLedgerSequence:0,semantic:{available:false,availability:'disabled',profile:null},items:[structuredClone(validItem)],bundles:[{selectedId:id,members:[{...validItem}],coverage:{requiredTotal:0,requiredIncluded:0,missingRequiredIds:[],optionalTruncated:false,complete:true}}],sourceFallback:[],sourceManifest:[{sourceKind:'dialogue_turn',sourceId:id,sourceVersion:1,sourceHash:hash,ledgerSequence:0}],coverage:{complete:true,sourceFallback:{total:0,included:0,truncated:false,complete:true},watermarks:[{processorKind:'extract',processorVersion:'v',contiguousSequence:-1,examinedThroughSequence:-1,gapSequence:null}]}});
const profile={semanticAvailable:true,profile:{id,processorVersion:'v1',model:'m',dimensions:2}};
describe('npc memory evidence adapter',()=>{
  it('normalizes Unicode scalars and case-insensitive refs',()=>{expect(normalizeNpcMemoryQuery('  e\u0301  fox 🦊 ')).toBe('é fox 🦊');expect(normalizeNpcMemoryRefs([' Moonwell ','moonwell','🧑‍🚀'.repeat(130)])).toEqual(['Moonwell',Array.from('🧑‍🚀'.repeat(130)).slice(0,120).join('')]);});
  it('validates before I/O',async()=>{const rpc=vi.fn();await expect(retrieveNpcMemoryEvidence({rpc} as any,{...input(),actorId:'bad'})).rejects.toThrow('input is invalid');expect(rpc).not.toHaveBeenCalled();});
  it('uses exactly one lexical RPC without a provider and freezes evidence',async()=>{const rpc=vi.fn(async()=>({data:payload,error:null}));const result=await retrieveNpcMemoryEvidence({rpc} as any,input());expect(result.querySemantic).toBe('not_configured');expect(rpc).toHaveBeenCalledTimes(1);expect(rpc).toHaveBeenCalledWith('npc_memory_evidence_retrieve_for_actor',expect.objectContaining({p_query:'é fox 🦊',p_known_refs:['Moonwell',expect.any(String)],p_profile_id:null,p_candidate_limit:24}),expect.any(AbortSignal));expect(Object.isFrozen(result.evidence)).toBe(true);});
  it('uses active profile and one provider embedding',async()=>{const rpc=vi.fn(async(name:string)=>({data:name==='npc_memory_active_embedding_profile'?profile:payload,error:null}));const provider={preflight:vi.fn(()=>({body:{}})),embed:vi.fn(async()=>({vector:'[1,0]',model:'m',dimensions:2,providerRequestId:'secret',promptTokens:1,totalTokens:1}))};const result=await retrieveNpcMemoryEvidence({rpc} as any,input(),provider as any);expect(result.querySemantic).toBe('ready');expect(provider.embed).toHaveBeenCalledOnce();expect(rpc).toHaveBeenLastCalledWith('npc_memory_evidence_retrieve_for_actor',expect.objectContaining({p_profile_id:id,p_query_embedding:'[1,0]'}),expect.any(AbortSignal));});
  it('falls back for profile/provider faults and retries rotation once without semantic',async()=>{const unavailable=vi.fn(async(name:string)=>({data:name==='npc_memory_active_embedding_profile'?{semanticAvailable:false,profile:null}:payload,error:null}));expect((await retrieveNpcMemoryEvidence({rpc:unavailable} as any,input(),{} as any)).querySemantic).toBe('no_active_profile');const rotated=vi.fn(async(name:string)=>name==='npc_memory_active_embedding_profile'?{data:profile,error:null}:rotated.mock.calls.filter(x=>x[0]==='npc_memory_evidence_retrieve_for_actor').length===1?{data:null,error:{code:'PT400',message:'Evidence embedding identity is invalid'}}:{data:payload,error:null});const provider={preflight:()=>({body:{}}),embed:async()=>({vector:'[1,0]',model:'m',dimensions:2})};expect((await retrieveNpcMemoryEvidence({rpc:rotated} as any,input(),provider as any)).querySemantic).toBe('profile_rotated');expect(rotated.mock.calls.filter(x=>x[0]==='npc_memory_evidence_retrieve_for_actor')).toHaveLength(2);});
  it('rejects malformed evidence and honors abort',async()=>{const rpc=vi.fn(async()=>({data:{},error:null}));await expect(retrieveNpcMemoryEvidence({rpc} as any,input())).rejects.toThrow('malformed');const nested=structuredClone(payload) as any;nested.coverage.sourceFallback.total='zero';await expect(retrieveNpcMemoryEvidence({rpc:vi.fn(async()=>({data:nested,error:null}))} as any,input())).rejects.toThrow('malformed');const controller=new AbortController();controller.abort();await expect(retrieveNpcMemoryEvidence({rpc} as any,{...input(),signal:controller.signal})).rejects.toMatchObject({name:'AbortError'});});
  it('does not fall back after profile authorization or malformed-profile errors',async()=>{const denied=vi.fn(async()=>({data:null,error:{code:'42501',message:'denied'}}));await expect(retrieveNpcMemoryEvidence({rpc:denied} as any,input(),{} as any)).rejects.toThrow('denied');expect(denied).toHaveBeenCalledOnce();const malformed=vi.fn(async()=>({data:{semanticAvailable:true,profile:null},error:null}));await expect(retrieveNpcMemoryEvidence({rpc:malformed} as any,input(),{} as any)).rejects.toThrow('malformed');expect(malformed).toHaveBeenCalledOnce();});
  it('uses one lexical fallback for an uncoded profile outage and provider failure',async()=>{const outage=vi.fn(async(name:string)=>name==='npc_memory_active_embedding_profile'?{data:null,error:{message:'offline'}}:{data:payload,error:null});expect((await retrieveNpcMemoryEvidence({rpc:outage} as any,input(),{} as any)).querySemantic).toBe('profile_unavailable');expect(outage).toHaveBeenCalledTimes(2);const rpc=vi.fn(async(name:string)=>({data:name==='npc_memory_active_embedding_profile'?profile:payload,error:null}));const provider={preflight:()=>{throw new Error('offline');},embed:vi.fn()};expect((await retrieveNpcMemoryEvidence({rpc} as any,input(),provider as any)).querySemantic).toBe('provider_failed');expect(rpc).toHaveBeenCalledTimes(2);expect(provider.embed).not.toHaveBeenCalled();});
  it('does not retry non-rotation semantic errors',async()=>{const rpc=vi.fn(async(name:string)=>name==='npc_memory_active_embedding_profile'?{data:profile,error:null}:{data:null,error:{code:'42501',message:'denied'}});const provider={preflight:()=>({body:{}}),embed:async()=>({vector:'[1,0]',model:'m',dimensions:2})};await expect(retrieveNpcMemoryEvidence({rpc} as any,input(),provider as any)).rejects.toThrow('denied');expect(rpc.mock.calls.filter(x=>x[0]==='npc_memory_evidence_retrieve_for_actor')).toHaveLength(1);});
  it('passes cancellation into RPC calls and stops after a profile response aborts',async()=>{const controller=new AbortController(),rpc=vi.fn(async(name:string)=>{if(name==='npc_memory_active_embedding_profile')controller.abort();return {data:profile,error:null};}),provider={preflight:vi.fn(),embed:vi.fn()};await expect(retrieveNpcMemoryEvidence({rpc} as any,{...input(),signal:controller.signal},provider as any)).rejects.toMatchObject({name:'AbortError'});expect(rpc).toHaveBeenCalledWith('npc_memory_active_embedding_profile',{},controller.signal);expect(provider.preflight).not.toHaveBeenCalled();expect(rpc).toHaveBeenCalledOnce();});
  it.each([
    (x:any)=>x.semantic={available:true,availability:'disabled',profile:null},(x:any)=>x.items[0].channelRanks.relational=0,(x:any)=>x.items[0].selectionReasons=['unknown'],(x:any)=>x.items[0].selectionReasons=['lexical','lexical'],(x:any)=>x.items[0].sourceId='bad',(x:any)=>x.items[0].sourceHash='bad',(x:any)=>x.bundles[0].coverage.requiredTotal=1,(x:any)=>x.bundles[0].coverage.missingRequiredIds=['bad'],(x:any)=>x.bundles[0].coverage.complete=false,(x:any)=>x.sourceManifest[0].sourceKind='bad',(x:any)=>x.sourceManifest[0].sourceVersion=0,(x:any)=>x.coverage.watermarks[0].processorKind='bad',(x:any)=>x.coverage.watermarks[0].contiguousSequence=-2
  ])('rejects malformed nonempty nested contracts',async(mutate)=>{const malformed=validNested();mutate(malformed);await expect(retrieveNpcMemoryEvidence({rpc:vi.fn(async()=>({data:malformed,error:null}))} as any,input())).rejects.toThrow('malformed');});
});
